// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Payment Method/Placeholder/48.svg

import type { IconProps } from "../../types";

export const Icon48 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 70 48"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2215" fill="white">
      <path d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z" />
    </mask>
    <path
      d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z"
      fill="#5A31F4"
    />
    <path
      d="M8 0V1H62V0V-1H8V0ZM70 8H69V40H70H71V8H70ZM62 48V47H8V48V49H62V48ZM0 40H1V8H0H-1V40H0ZM8 48V47C4.13 47 1 43.87 1 40H0H-1C-1 44.97 3.03 49 8 49V48ZM70 40H69C69 43.87 65.87 47 62 47V48V49C66.97 49 71 44.97 71 40H70ZM62 0V1C65.87 1 69 4.13 69 8H70H71C71 3.03 66.97 -1 62 -1V0ZM8 0V-1C3.03 -1 -1 3.03 -1 8H0H1C1 4.13 4.13 1 8 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2215)"
    />
  </svg>
);
