// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/suite/shape/general/book.svg

import type { IconProps } from "../../types";

export const IconBook = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.5 4.13C17.67 4.13 18.63 5.08 18.63 6.25V18.75C18.63 19.37 18.12 19.88 17.5 19.88H7.5C6.33 19.88 5.38 18.92 5.38 17.75V6.25C5.38 5.08 6.33 4.13 7.5 4.13H16.5ZM7.5 16.88C7.02 16.88 6.63 17.27 6.63 17.75C6.63 18.23 7.02 18.63 7.5 18.63H17.38V16.88H7.5ZM7.5 5.38C7.02 5.38 6.63 5.77 6.63 6.25V15.81C6.89 15.69 7.19 15.63 7.5 15.63H17.38V6.25C17.38 5.77 16.98 5.38 16.5 5.38H7.5ZM14.25 7.63C14.6 7.63 14.88 7.9 14.88 8.25C14.88 8.6 14.6 8.88 14.25 8.88H9.75C9.4 8.88 9.13 8.6 9.13 8.25C9.13 7.9 9.4 7.63 9.75 7.63H14.25Z"
      fill="#116682"
    />
  </svg>
);
