// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/prompt-library/usecase/prompt_library/meaning-2.svg

import type { IconProps } from "../../types";

export const IconBriefcaseGraphic2 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13.57 3.21C14.23 3.21 14.88 3.44 15.37 3.87C15.85 4.31 16.15 4.91 16.15 5.56V7.1H18.64C19.92 7.1 21.02 8.1 21.02 9.4V17.75C21.02 19.04 19.92 20.04 18.64 20.04H4.61C3.33 20.04 2.23 19.04 2.23 17.75V9.4C2.23 8.1 3.33 7.1 4.61 7.1H7.1V5.56C7.1 4.91 7.39 4.31 7.88 3.87C8.37 3.44 9.02 3.21 9.68 3.21H13.57ZM16.15 18.79H18.64C19.29 18.79 19.77 18.3 19.77 17.75V9.4C19.77 8.85 19.29 8.35 18.64 8.35H16.15V18.79ZM8.35 18.79H14.9V8.35H8.35V18.79ZM4.61 8.35C3.96 8.35 3.48 8.85 3.48 9.4V17.75C3.48 18.3 3.96 18.79 4.61 18.79H7.1V8.35H4.61ZM9.68 4.46C9.3 4.46 8.96 4.59 8.71 4.81C8.47 5.02 8.35 5.3 8.35 5.56V7.1H14.9V5.56C14.9 5.3 14.78 5.02 14.54 4.81C14.29 4.59 13.95 4.46 13.57 4.46H9.68Z"
      fill="#6B8000"
    />
  </svg>
);
