// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/toast/processing/deferred.svg

import type { IconProps } from "../../types";

export const IconDeferred = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 32 32"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <circle cx="16" cy="11" r="2" fill="#BEBEBE" />
    <circle cx="16" cy="11" r="2" fill="#BEBEBE" />
    <circle cx="16" cy="21" r="2" fill="#404040" />
  </svg>
);
