// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/suite/shape/general/document.svg

import type { IconProps } from "../../types";

export const IconDocument = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13.05 4.38C13.48 4.38 13.88 4.56 14.16 4.87L17.18 8.16C17.47 8.48 17.62 8.9 17.63 9.33V16.9C17.62 18.34 16.57 19.63 15.13 19.63H8.88C7.43 19.63 6.38 18.34 6.38 16.9V7.1C6.38 5.66 7.43 4.38 8.88 4.38H13.05ZM8.88 5.63C8.25 5.63 7.63 6.22 7.63 7.1V16.9C7.63 17.78 8.25 18.38 8.88 18.38H15.13C15.75 18.38 16.37 17.78 16.38 16.9V10.29H13.65C12.72 10.29 12.09 9.47 12.09 8.62V5.63H8.88ZM13.34 8.62C13.34 8.92 13.54 9.04 13.65 9.04H16.29C16.28 9.03 16.27 9.01 16.26 9L13.34 5.83V8.62Z"
      fill="#82612E"
    />
  </svg>
);
