// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/suite/shape/general/flag.svg

import type { IconProps } from "../../types";

export const IconFlagGraphic = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M17.52 4.63C18.52 4.63 19.02 5.84 18.32 6.55L15.11 9.75L18.32 12.95C19.02 13.66 18.52 14.87 17.52 14.88H6.98C6.85 14.88 6.72 14.86 6.6 14.83V18.75C6.6 19.1 6.32 19.38 5.98 19.38C5.63 19.38 5.35 19.1 5.35 18.75V6.25C5.35 5.35 6.08 4.63 6.98 4.63H17.52ZM6.98 5.88C6.77 5.88 6.6 6.04 6.6 6.25V13.25C6.6 13.46 6.77 13.63 6.98 13.63H17.22L14.14 10.55C13.73 10.13 13.7 9.48 14.06 9.04L14.14 8.95L17.22 5.88H6.98Z"
      fill="#5555A3"
    />
  </svg>
);
