// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-11.svg

import type { IconProps } from "../../types";

export const IconFrame11 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_6231"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_6231)">
      <path d="M27 0H-3V20H27V0Z" fill="#E01A20" />
      <path
        d="M8.9 13.95C3.67 13.95 3.67 6.05 8.9 6.05C10.02 6.05 11.03 6.51 11.75 7.26C10.86 5.93 9.35 5.05 7.62 5.05C1.08 5.05 1.07 14.95 7.62 14.95C9.35 14.95 10.86 14.07 11.75 12.74C11.03 13.49 10.02 13.95 8.9 13.95V13.95Z"
        fill="white"
      />
      <path
        d="M16.16 8.46L14.39 9.05L13.29 7.55L13.31 9.42L11.54 10.01L13.32 10.58L13.34 12.44L14.42 10.93L16.19 11.49L15.08 9.98L16.16 8.46Z"
        fill="white"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
