// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-12.svg

import type { IconProps } from "../../types";

export const IconFrame12 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3268"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3268)">
      <path d="M25 0H8.33V7.79H25V0Z" fill="#EB3536" />
      <path d="M25 12.27H8.33V20H25V12.27Z" fill="#EB3536" />
      <path d="M3.85 12.27H-5V20H3.85V12.27Z" fill="#EB3536" />
      <path d="M3.85 0H-5V7.79H3.85V0Z" fill="#EB3536" />
      <path
        d="M25 7.79V12.27H8.33V20H3.85V12.27H-5V7.79H3.85V0H8.33V7.79H25Z"
        fill="white"
      />
      <path
        d="M25 8.93V11.12H7.18V20H4.99V11.12H-5V8.93H4.99V0H7.18V8.93H25Z"
        fill="#101967"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
