// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-1.svg

import type { IconProps } from "../../types";

export const IconFrame1 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3133"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3133)">
      <path d="M25 0H-5V4H25V0Z" fill="#0035BC" />
      <path d="M25 16H-5V20H25V16Z" fill="#0035BC" />
      <path d="M25 4H-5V16H25V4Z" fill="white" />
      <path
        d="M10 6.36L13.17 11.82H6.83L10 6.36M10 4.68L5.36 12.67H14.64L10 4.68Z"
        fill="#0035BC"
      />
      <path
        d="M13.17 8.18L10 13.64L6.83 8.18H13.17M14.64 7.33H5.36L10 15.32L14.64 7.33Z"
        fill="#0035BC"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
