// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-8.svg

import type { IconProps } from "../../types";

export const IconFrame8 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3110"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3110)">
      <path d="M29.17 0H-0.83V2.22H29.17V0Z" fill="#2B54AF" />
      <path d="M29.17 2.22H-0.83V4.45H29.17V2.22Z" fill="white" />
      <path d="M29.17 4.44H-0.83V6.67H29.17V4.44Z" fill="#2B54AF" />
      <path d="M29.17 6.67H-0.83V8.89H29.17V6.67Z" fill="white" />
      <path d="M29.17 8.89H-0.83V11.11H29.17V8.89Z" fill="#2B54AF" />
      <path d="M29.17 11.11H-0.83V13.33H29.17V11.11Z" fill="white" />
      <path d="M29.17 13.33H-0.83V15.56H29.17V13.33Z" fill="#2B54AF" />
      <path d="M29.17 15.56H-0.83V17.78H29.17V15.56Z" fill="white" />
      <path d="M29.17 17.78H-0.83V20H29.17V17.78Z" fill="#2B54AF" />
      <path d="M10.27 0H-0.83V11.11H10.27V0Z" fill="#2B54AF" />
      <path
        d="M10.27 4.44H5.83V0H3.61V4.44H-0.83V6.67H3.61V11.11H5.83V6.67H10.27V4.44Z"
        fill="white"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
