// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-25.svg

import type { IconProps } from "../../types";

export const IconFrame25 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_2917"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_2917)">
      <path d="M-3.33 20V0L11.67 10L-3.33 20Z" fill="#1F3D7E" />
      <path
        d="M11.67 10L-3.33 20C1.87 20 23.43 20 26.67 20V10H11.67Z"
        fill="#D42025"
      />
      <path d="M-3.33 0L11.67 10H26.67V0H-3.33Z" fill="white" />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
