// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-7.svg

import type { IconProps } from "../../types";

export const IconFrame7 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_2820"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_2820)">
      <path d="M25.85 0V6.66H11.85L1.86 0H25.85Z" fill="#DD4238" />
      <path d="M25.85 13.34V20H1.86L11.85 13.34H25.85Z" fill="#180088" />
      <path d="M4.82 10L-4.17 15.99V4.01L4.82 10Z" fill="currentColor" />
      <path
        d="M7.26 10L-4.17 17.61V15.99L4.82 10L-4.17 4.01V2.39L7.26 10Z"
        fill="#F8BE2E"
      />
      <path
        d="M25.85 6.66V13.34H11.85L1.86 20H-4.17V17.61L7.26 10L-4.17 2.39V0H1.86L11.85 6.66H25.85Z"
        fill="white"
      />
      <path
        d="M25.85 8.01V11.99H11.45L-0.58 20H-4.17V17.61L7.26 10L-4.17 2.39V0H-0.58L11.45 8.01H25.85Z"
        fill="#007947"
      />
      <path
        d="M19 10C19 5.03 14.97 1 10 1C5.03 1 1 5.03 1 10C1 14.97 5.03 19 10 19V20C4.48 20 0 15.52 0 10C0 4.48 4.48 0 10 0C15.52 0 20 4.48 20 10C20 15.52 15.52 20 10 20V19C14.97 19 19 14.97 19 10Z"
        fill="#DDE1EB"
      />
    </g>
  </svg>
);
