// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-38.svg

import type { IconProps } from "../../types";

export const IconFrame38 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3052"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3052)">
      <path d="M27.78 0H-7.5V20H27.78V0Z" fill="#120D68" />
      <path d="M7.23 13.28V13.88L-3.57 20H-4.95L6.9 13.28H7.23Z" fill="white" />
      <path d="M25.22 0L13.38 6.72H13.05V6.12L23.85 0H25.22Z" fill="white" />
      <path
        d="M27.78 17.77V18.55L18.48 13.28H19.86L27.78 17.77Z"
        fill="white"
      />
      <path d="M1.79 6.72H0.42L-7.5 2.23V1.45L1.79 6.72Z" fill="white" />
      <path d="M27.78 18.55V20L15.93 13.28H18.48L27.78 18.55Z" fill="#C61A33" />
      <path d="M27.78 0L15.93 6.72H13.38L25.22 0H27.78Z" fill="#C61A33" />
      <path d="M27.78 0V2.23L19.86 6.72H15.93L27.78 0Z" fill="white" />
      <path d="M6.9 13.28L-4.95 20H-7.5L4.35 13.28H6.9Z" fill="#C61A33" />
      <path d="M4.35 13.28L-7.5 20V17.77L0.42 13.28H4.35Z" fill="white" />
      <path d="M7.23 6.13V6.72H4.34L-7.5 0H-3.57L7.23 6.13Z" fill="white" />
      <path
        d="M27.78 20H23.85L13.05 13.88V13.28H15.93L27.78 20Z"
        fill="white"
      />
      <path d="M4.34 6.72H1.79L-7.5 1.45V0L4.34 6.72Z" fill="#C61A33" />
      <path
        d="M27.78 13.28H13.05V20H7.23V13.28H-7.5V6.72H7.23V0H13.05V6.72H27.77V13.28H27.78Z"
        fill="white"
      />
      <path
        d="M27.78 8.03V11.97H11.89V20H8.39V11.97H-7.5V8.03H8.39V0H11.89V8.03H27.78Z"
        fill="#C61A33"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
