// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-34.svg

import type { IconProps } from "../../types";

export const IconFrame34 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3256"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3256)">
      <path d="M25.02 -1H-5V19H25.02V-1Z" fill="#DA321F" />
      <path
        d="M6.88 5.07H4.68L4 2.97L3.33 5.07H1.12L2.9 6.37L2.23 8.48L4 7.18L5.77 8.48L5.1 6.37L6.88 5.07Z"
        fill="#F7E424"
      />
      <path
        d="M9.43 2L8.92 2.59L8.2 2.28L8.6 2.95L8.09 3.53L8.85 3.37L9.25 4.03L9.32 3.26L10.08 3.09L9.37 2.78L9.43 2Z"
        fill="#F7E424"
      />
      <path
        d="M11.77 4.26L11.07 4.6L10.53 4.03L10.64 4.81L9.94 5.15L10.71 5.29L10.82 6.06L11.19 5.37L11.95 5.51L11.41 4.94L11.77 4.26Z"
        fill="#F7E424"
      />
      <path
        d="M12.01 7.64L11.23 7.67L10.96 6.94L10.75 7.69L9.97 7.72L10.62 8.16L10.41 8.91L11.02 8.43L11.66 8.86L11.4 8.13L12.01 7.64Z"
        fill="#F7E424"
      />
      <path
        d="M10.08 10.04L9.35 9.77L9.38 8.99L8.9 9.6L8.17 9.33L8.6 9.98L8.12 10.6L8.87 10.39L9.3 11.03L9.33 10.25L10.08 10.04Z"
        fill="#F7E424"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
