// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-26.svg

import type { IconProps } from "../../types";

export const IconFrame26 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3232"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3232)">
      <path d="M30 0H10V1.43H30V0Z" fill="#AD1B1B" />
      <path d="M30 1.43H10V2.86H30V1.43Z" fill="white" />
      <path d="M30 2.86H10V4.28H30V2.86Z" fill="#AD1B1B" />
      <path d="M30 4.28H10V5.71H30V4.28Z" fill="white" />
      <path d="M30 5.71H10V7.14H30V5.71Z" fill="#AD1B1B" />
      <path d="M30 7.14H10V8.57H30V7.14Z" fill="white" />
      <path d="M30 8.57H10V10H30V8.57Z" fill="#AD1B1B" />
      <path d="M30 10H-2.5V11.67H30V10Z" fill="white" />
      <path d="M30 11.43H-10V12.86H30V11.43Z" fill="#AD1B1B" />
      <path d="M30 12.86H-10V14.28H30V12.86Z" fill="white" />
      <path d="M30 14.28H-10V15.71H30V14.28Z" fill="#AD1B1B" />
      <path d="M30 15.71H-10V17.14H30V15.71Z" fill="white" />
      <path d="M30 17.14H-10V18.57H30V17.14Z" fill="#AD1B1B" />
      <path d="M30 18.57H-10V20H30V18.57Z" fill="white" />
      <path d="M11 0H0V11H11V0Z" fill="#0E0063" />
      <path
        d="M4.58 3.67C5.18 3.67 5.73 3.86 6.18 4.18C5.88 4.04 5.54 3.97 5.19 3.97C3.84 3.97 2.75 5.07 2.75 6.42C2.75 7.77 3.84 8.86 5.19 8.86C5.54 8.86 5.88 8.79 6.18 8.66C5.73 8.98 5.18 9.17 4.58 9.17C3.06 9.17 1.83 7.94 1.83 6.42C1.83 4.9 3.07 3.67 4.58 3.67ZM7.54 5.55L8.31 4.4L7.9 5.72L9.09 5.02L8.15 6.03L9.52 5.92L8.24 6.42L9.52 6.91L8.15 6.8L9.09 7.81L7.9 7.11L8.32 8.43L7.54 7.29L7.35 8.65L7.15 7.29L6.38 8.43L6.79 7.12L5.6 7.82L6.54 6.81L5.17 6.92L6.45 6.42L5.17 5.93L6.54 6.03L5.59 5.03L6.79 5.72L6.37 4.41L7.14 5.55L7.34 4.19L7.54 5.55Z"
        fill="#EED23D"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
