// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-17.svg

import type { IconProps } from "../../types";

export const IconFrame17 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_6246"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_6246)">
      <path d="M25 0H-5V20H25V0Z" fill="#FC2016" />
      <path
        d="M16.09 8.62H11.43L10 4.2L8.57 8.62H3.91L7.67 11.37L6.25 15.79L10 13.07L13.75 15.79L12.33 11.37L16.09 8.62Z"
        fill="#FFFF00"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
