// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-3.svg

import type { IconProps } from "../../types";

export const IconFrame3 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_6221"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_6221)">
      <path d="M25.03 3.33H-5V6.67H25.03V3.33Z" fill="white" />
      <path d="M25.03 0H-5V3.33H25.03V0Z" fill="#A31B32" />
      <path d="M25.03 16.67H-5V20H25.03V16.67Z" fill="#A31B32" />
      <path d="M25.03 13.33H-5V16.67H25.03V13.33Z" fill="white" />
      <path d="M25.03 6.67H-5V13.33H25.03V6.67Z" fill="#2D2248" />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
