// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-27.svg

import type { IconProps } from "../../types";

export const IconFrame27 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3195"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3195)">
      <path d="M25.02 0H-5V20H25.02V0Z" fill="white" />
      <path
        d="M13.02 11.96C13.56 11.13 13.32 10.01 12.49 9.47C11.65 8.93 10.53 9.16 9.99 10C9.45 10.83 8.33 11.07 7.5 10.53C6.66 9.99 6.42 8.87 6.97 8.04C8.05 6.37 10.28 5.89 11.95 6.97C13.63 8.06 14.1 10.29 13.02 11.96Z"
        fill="#CA333E"
      />
      <path
        d="M13.02 11.96C11.94 13.63 9.7 14.11 8.03 13.02C6.36 11.94 5.88 9.71 6.97 8.04C6.43 8.87 6.66 9.99 7.5 10.53C8.34 11.07 9.45 10.83 9.99 10C10.54 9.16 11.65 8.92 12.49 9.47C13.32 10.01 13.56 11.12 13.02 11.96V11.96Z"
        fill="#26399F"
      />
      <path
        d="M14.02 5.16L13.5 5.5L14.41 6.86L14.92 6.52L14.02 5.16Z"
        fill="currentColor"
      />
      <path
        d="M15.09 6.77L14.58 7.11L15.49 8.46L16 8.12L15.09 6.77Z"
        fill="currentColor"
      />
      <path
        d="M16.75 7.65L16.24 7.99C13.49 3.86 16.84 8.89 14.25 5.01L14.77 4.67C16.96 7.97 15.52 5.8 16.75 7.65Z"
        fill="currentColor"
      />
      <path
        d="M15.51 4.17L15 4.51L15.9 5.86L16.41 5.52L15.51 4.17Z"
        fill="currentColor"
      />
      <path
        d="M16.59 5.79L16.08 6.13L16.98 7.49L17.5 7.15L16.59 5.79Z"
        fill="currentColor"
      />
      <path
        d="M5.98 5.18L4 8.17L4.51 8.51L6.5 5.52L5.98 5.18Z"
        fill="currentColor"
      />
      <path
        d="M5.24 4.68L3.25 7.67L3.76 8.01L5.75 5.02L5.24 4.68Z"
        fill="currentColor"
      />
      <path
        d="M4.48 4.17L2.49 7.16L3.01 7.5L4.99 4.52L4.48 4.17Z"
        fill="currentColor"
      />
      <path
        d="M14.41 13.14L13.51 14.49L14.02 14.84L14.93 13.48L14.41 13.14Z"
        fill="currentColor"
      />
      <path
        d="M15.49 11.51L14.59 12.86L15.1 13.2L16 11.85L15.49 11.51Z"
        fill="currentColor"
      />
      <path
        d="M15.17 13.65L14.27 15.01L14.78 15.35L15.68 13.99L15.17 13.65Z"
        fill="currentColor"
      />
      <path
        d="M16.25 12.02L15.35 13.38L15.86 13.72L16.77 12.36L16.25 12.02Z"
        fill="currentColor"
      />
      <path
        d="M15.9 14.13L15 15.49L15.51 15.83L16.42 14.47L15.9 14.13Z"
        fill="currentColor"
      />
      <path
        d="M17 12.52L16.1 13.87L16.61 14.21L17.51 12.86L17 12.52Z"
        fill="currentColor"
      />
      <path
        d="M6.48 14.49L5.97 14.83C4.55 12.7 6.39 15.47 3.98 11.85L4.49 11.51C5.33 12.76 4.36 11.3 6.48 14.49Z"
        fill="currentColor"
      />
      <path
        d="M3.74 11.99L3.23 12.33L4.13 13.68L4.64 13.34L3.74 11.99Z"
        fill="currentColor"
      />
      <path
        d="M4.82 13.61L4.31 13.95L5.21 15.31L5.73 14.97L4.82 13.61Z"
        fill="currentColor"
      />
      <path
        d="M4.99 15.49L4.48 15.83C3.64 14.58 4.61 16.03 2.49 12.84L3 12.5C4.17 14.26 2.82 12.23 4.99 15.49Z"
        fill="currentColor"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
