// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-31.svg

import type { IconProps } from "../../types";

export const IconFrame31 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3160"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3160)">
      <path d="M25.84 0H9.16V7.79H25.84V0Z" fill="#23479D" />
      <path d="M25.84 12.27H9.16V20H25.84V12.27Z" fill="#23479D" />
      <path d="M4.68 12.27H-4.17V20H4.68V12.27Z" fill="#23479D" />
      <path d="M4.68 0H-4.17V7.79H4.68V0Z" fill="#23479D" />
      <path
        d="M25.83 7.79V12.27H9.16V20H4.68V12.27H-4.17V7.79H4.68V0H9.16V7.79H25.83Z"
        fill="white"
      />
      <path
        d="M25.83 8.93V11.12H8.01V20H5.83V11.12H-4.17V8.93H5.83V0H8.01V8.93H25.83Z"
        fill="#DA2238"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
