// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-45.svg

import type { IconProps } from "../../types";

export const IconFrame45 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_2872"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_2872)">
      <path d="M-5 20H25V0H-5V20Z" fill="#DC241F" />
      <path
        d="M25 0H22.33L10 8.24L-2.34 0H-5V1.74L7.36 10L-5 18.26V20H-2.34L10 11.76L22.33 20H25V18.26L12.63 10L25 1.74V0Z"
        fill="#009543"
      />
      <path d="M25 8.46H-5V11.54H25V8.46Z" fill="white" />
      <path d="M11.29 0H8.71V20H11.29V0Z" fill="white" />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
