// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-44.svg

import type { IconProps } from "../../types";

export const IconFrame44 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_2880"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_2880)">
      <path d="M25 0H-5V20H25V0Z" fill="#006A4C" />
      <path
        d="M8.5 16.87C12.29 16.87 15.37 13.79 15.37 10C15.37 6.21 12.29 3.13 8.5 3.13C4.71 3.13 1.63 6.21 1.63 10C1.63 13.79 4.71 16.87 8.5 16.87Z"
        fill="#F03348"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
