// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-21.svg

import type { IconProps } from "../../types";

export const IconFrame21 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_4604"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_4604)">
      <path d="M28 0H-2V6.67H28V0Z" fill="white" />
      <path d="M28 13.33H-2V20H28V13.33Z" fill="#AC353A" />
      <path d="M28 6.67H-2V13.33H28V6.67Z" fill="#413999" />
      <path
        d="M6.88 15.29C4.23 14.13 2.62 11.86 2.69 9.36L2.81 4.7H11.19L11.32 9.36C11.38 11.86 9.77 14.13 7.12 15.29L7 15.34L6.88 15.29H6.88Z"
        fill="white"
      />
      <path
        d="M10.19 12.36C9.47 13.52 8.33 14.44 7 15.02C5.67 14.44 4.53 13.52 3.81 12.36C4.82 10.64 5.72 12.14 5.72 12.14C5.91 11.46 6.57 10.97 7 10.97C7.43 10.97 8.09 11.46 8.28 12.14C8.28 12.14 9.18 10.64 10.19 12.36Z"
        fill="#413999"
      />
      <path
        d="M10.19 12.36C9.18 10.64 8.28 12.14 8.28 12.14C8.09 11.46 7.43 10.97 7 10.97C6.57 10.97 5.91 11.46 5.72 12.14C5.72 12.14 4.82 10.64 3.81 12.36C3.26 11.48 2.95 10.46 2.98 9.36L3.09 4.99H10.91L11.02 9.36C11.05 10.46 10.74 11.48 10.19 12.36H10.19Z"
        fill="#AC353A"
      />
      <path
        d="M6.66 9.45V11.05C6.78 11 6.9 10.97 7 10.97C7.1 10.97 7.22 11 7.35 11.05V9.45H8.1L9.44 9.69V8.53L8.1 8.76H7.35V7.63H7.65L8.99 7.86V6.71L7.65 6.94H7.35V6.88L7.58 5.36H6.42L6.65 6.88V6.94H6.35L5.01 6.71V7.86L6.35 7.63H6.65V8.76H5.9L4.56 8.53V9.69L5.9 9.45H6.65H6.66Z"
        fill="white"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
