// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-19.svg

import type { IconProps } from "../../types";

export const IconFrame19 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3083"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3083)">
      <path d="M25.83 0H-4.17V20H25.83V0Z" fill="white" />
      <path
        d="M26.67 7.57V12.43H9.72V20H4.85V12.43H-3.33V7.57H4.85V0H9.72V7.57H26.67Z"
        fill="#192780"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
