// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-43.svg

import type { IconProps } from "../../types";

export const IconFrame43 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_2944"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_2944)">
      <path d="M27.78 0H-7.5V20H27.78V0Z" fill="#1E0067" />
      <path d="M10 2H0V9.14H10V2Z" fill="#1E0067" />
      <path d="M4.18 6.74V6.96L1.11 9.14H0.72L4.08 6.74H4.18Z" fill="white" />
      <path d="M9.28 2L5.92 4.4H5.82V4.19L8.89 2H9.28Z" fill="white" />
      <path d="M10 8.35V8.63L7.37 6.74H7.76L10 8.35Z" fill="white" />
      <path d="M2.63 4.4H2.24L0 2.8V2.52L2.63 4.4Z" fill="white" />
      <path d="M10 8.63V9.14L6.64 6.74H7.37L10 8.63Z" fill="#E03145" />
      <path d="M10 2L6.64 4.4H5.92L9.28 2H10Z" fill="#E03145" />
      <path d="M10 2V2.8L7.76 4.4H6.64L10 2Z" fill="white" />
      <path d="M4.08 6.74L0.72 9.14H0L3.36 6.74H4.08Z" fill="#E03145" />
      <path d="M3.36 6.74L0 9.14V8.35L2.24 6.74H3.36Z" fill="white" />
      <path d="M4.18 4.19V4.4H3.36L0 2H1.11L4.18 4.19Z" fill="white" />
      <path d="M10 9.14H8.89L5.82 6.96V6.74H6.64L10 9.14Z" fill="white" />
      <path d="M3.36 4.4H2.63L0 2.52V2L3.36 4.4Z" fill="#E03145" />
      <path
        d="M10 6.74H5.82V9.14H4.18V6.74H0V4.4H4.18V2H5.82V4.4H10V6.74Z"
        fill="white"
      />
      <path
        d="M10 4.87V6.28H5.5V9.14H4.5V6.28H0V4.87H4.5V2H5.5V4.87H10Z"
        fill="#E03145"
      />
      <path
        d="M4.51 11.5L5.03 13L6.52 12.47L5.67 13.81L7.02 14.65L5.44 14.82L5.63 16.39L4.51 15.26L3.39 16.39L3.58 14.82L2 14.65L3.35 13.81L2.5 12.47L3.99 13L4.51 11.5Z"
        fill="white"
      />
      <path
        d="M12.44 9.83L12.7 10.59L13.46 10.33L13.03 11.01L13.72 11.43L12.91 11.52L13.01 12.32L12.44 11.75L11.87 12.32L11.97 11.52L11.17 11.43L11.85 11.01L11.42 10.33L12.18 10.59L12.44 9.83Z"
        fill="white"
      />
      <path
        d="M15.77 14.83L16.04 15.6L16.8 15.33L16.37 16.01L17.05 16.43L16.25 16.52L16.34 17.32L15.77 16.75L15.21 17.32L15.3 16.52L14.5 16.43L15.18 16.01L14.75 15.33L15.51 15.6L15.77 14.83Z"
        fill="white"
      />
      <path
        d="M16.61 4L16.87 4.76L17.63 4.49L17.2 5.17L17.88 5.6L17.08 5.68L17.17 6.48L16.61 5.91L16.04 6.48L16.13 5.68L15.33 5.6L16.02 5.17L15.59 4.49L16.34 4.76L16.61 4Z"
        fill="white"
      />
      <path
        d="M20.14 10.67L20.33 11.1L20.79 11.14L20.44 11.45L20.54 11.91L20.14 11.68L19.73 11.91L19.83 11.45L19.48 11.14L19.95 11.1L20.14 10.67Z"
        fill="white"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
