// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-40.svg

import type { IconProps } from "../../types";

export const IconFrame40 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3170"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3170)">
      <path d="M-5 0V10H25V0H-5Z" fill="#FB1F1F" />
      <path d="M-5 10V20H25V10H-5Z" fill="white" />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
