// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/frame-28.svg

import type { IconProps } from "../../types";

export const IconFrame28 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask
      id="mask0_1_3096"
      style={{ maskType: "alpha" }}
      maskUnits="userSpaceOnUse"
      x="0"
      y="0"
      width="20"
      height="20"
    >
      <circle cx="10" cy="10" r="10" fill="#D9D9D9" />
    </mask>
    <g mask="url(#mask0_1_3096)">
      <rect width="24" height="24" fill="#F7F7F7" />
      <rect
        x="-2.22"
        y="4.73"
        width="5.97"
        height="25.64"
        transform="rotate(-53.82 -2.22 4.73)"
        fill="#4392C1"
      />
      <path
        d="M12 6L13.65 10.73L18.66 10.84L14.66 13.87L16.11 18.66L12 15.8L7.89 18.66L9.34 13.87L5.34 10.84L10.35 10.73L12 6Z"
        fill="#C22F28"
      />
      <circle cx="10" cy="10" r="9.5" stroke="#DDE1EB" />
    </g>
  </svg>
);
