// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/brand/shape/brand/gemini.svg

import type { IconProps } from "../../types";

export const IconGemini = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 14 14"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M6.99 1.17C6.8 4.3 4.3 6.8 1.17 6.99V7.01C4.3 7.2 6.8 9.7 6.99 12.83H7.01C7.2 9.7 9.7 7.2 12.83 7.01V6.99C9.7 6.8 7.2 4.3 7.01 1.17H6.99Z"
      fill="url(#paint0_linear_1_6365)"
    />
    <defs>
      <linearGradient
        id="paint0_linear_1_6365"
        x1="10.84"
        y1="3.46"
        x2="2.64"
        y2="10.42"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#217BFE" />
        <stop offset="0.14" stopColor="#1485FC" />
        <stop offset="0.27" stopColor="#078EFB" />
        <stop offset="0.52" stopColor="#548FFD" />
        <stop offset="0.78" stopColor="#A190FF" />
        <stop offset="0.89" stopColor="#AF94FE" />
        <stop offset="1" stopColor="#BD99FE" />
      </linearGradient>
    </defs>
  </svg>
);
