// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/brand/shape/brand/grok.svg

import type { IconProps } from "../../types";

export const IconGrok = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 14 14"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M4.11 4.03C5.37 2.77 7.24 2.45 8.8 3.09C9.14 3.22 9.44 3.4 9.67 3.57L8.37 4.17C7.16 3.66 5.78 4.01 4.93 4.85C3.82 5.96 3.57 7.85 4.78 9.13L4.9 9.26L1.23 12.52C1.47 12.2 1.76 11.9 2.04 11.6C2.85 10.75 3.66 9.91 3.17 8.71C2.51 7.12 2.89 5.25 4.11 4.03ZM12.68 1.6C11.47 3.25 10.89 4.07 11.36 6.09L11.36 6.09C11.68 7.47 11.33 9 10.21 10.13C8.79 11.55 6.52 11.86 4.65 10.59L5.96 9.98C7.15 10.45 8.45 10.24 9.39 9.31C10.33 8.37 10.54 7.01 10.07 5.87C9.98 5.66 9.71 5.6 9.52 5.74L5.69 8.57L11.18 3.06V3.06L12.77 1.48C12.74 1.52 12.71 1.56 12.68 1.6Z"
      fill="currentColor"
    />
  </svg>
);
