// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/sync/usecase/sync-chat/loading.svg

import type { IconProps } from "../../types";

export const IconLoading = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 16 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <circle cx="11.5" cy="8" r="1" fill="#BEBEBE" />
    <circle cx="4.5" cy="8" r="1" fill="#BEBEBE" />
    <circle cx="8" cy="8" r="1" fill="#404040" />
  </svg>
);
