// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/message-system/meaning-1.svg

import type { IconProps } from "../../types";

export const IconLockGraphic = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 16 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M8.33 2.58C9.12 2.58 9.88 2.9 10.44 3.46C11 4.02 11.31 4.78 11.31 5.57V6.56H11.81C12.63 6.56 13.3 7.23 13.3 8.05V12.02C13.3 12.85 12.63 13.52 11.81 13.52H4.85C4.03 13.52 3.36 12.85 3.36 12.02V8.05C3.36 7.23 4.03 6.56 4.85 6.56H5.35V5.57C5.35 4.78 5.66 4.02 6.22 3.46C6.78 2.9 7.54 2.58 8.33 2.58ZM4.85 7.56C4.58 7.56 4.36 7.78 4.36 8.05V12.02C4.36 12.3 4.58 12.52 4.85 12.52H11.81C12.08 12.52 12.3 12.3 12.3 12.02V8.05C12.3 7.78 12.08 7.56 11.81 7.56H4.85ZM8.43 9.04C8.93 9.1 9.33 9.52 9.33 10.04C9.33 10.59 8.88 11.03 8.33 11.03C7.81 11.03 7.39 10.64 7.34 10.14L7.33 10.04L7.34 9.93C7.39 9.43 7.81 9.04 8.33 9.04L8.43 9.04ZM8.33 10.03H8.33V10.04L8.33 10.04L8.33 10.04V10.04L8.33 10.04H8.33L8.33 10.04V10.04L8.33 10.03H8.33L8.33 10.03L8.33 10.03ZM8.33 3.58C7.8 3.58 7.3 3.79 6.93 4.16C6.56 4.54 6.35 5.04 6.35 5.57V6.56H10.31V5.57C10.31 5.04 10.1 4.54 9.73 4.16C9.36 3.79 8.86 3.58 8.33 3.58Z"
      fill="currentColor"
    />
  </svg>
);
