// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=48-20.svg

import type { IconProps } from "../../types";

export const IconSize4820 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 70 48"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2815" fill="white">
      <path d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z" />
    </mask>
    <path
      d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z"
      fill="#1F72CD"
    />
    <path
      d="M8 0V1H62V0V-1H8V0ZM70 8H69V40H70H71V8H70ZM62 48V47H8V48V49H62V48ZM0 40H1V8H0H-1V40H0ZM8 48V47C4.13 47 1 43.87 1 40H0H-1C-1 44.97 3.03 49 8 49V48ZM70 40H69C69 43.87 65.87 47 62 47V48V49C66.97 49 71 44.97 71 40H70ZM62 0V1C65.87 1 69 4.13 69 8H70H71C71 3.03 66.97 -1 62 -1V0ZM8 0V-1C3.03 -1 -1 3.03 -1 8H0H1C1 4.13 4.13 1 8 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2815)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.55 17L6 31.49H13.84L14.81 29.18H17.03L18.01 31.49H26.64V29.73L27.41 31.49H31.87L32.64 29.69V31.49H50.59L52.77 29.24L54.81 31.49L64.03 31.51L57.46 24.29L64.03 17H54.96L52.83 19.21L50.85 17H31.33L29.65 20.74L27.93 17H20.11V18.7L19.24 17H12.55ZM39.35 19.06H49.66L52.81 22.46L56.06 19.06H59.22L54.43 24.29L59.22 29.45H55.92L52.77 26.01L49.5 29.45H39.35V19.06ZM41.9 23.11V21.21V21.21H48.33L51.13 24.25L48.2 27.3H41.9V25.23H47.52V23.11H41.9ZM14.07 19.06H17.89L22.23 28.89V19.06H26.42L29.77 26.1L32.87 19.06H37.03V29.46H34.5L34.48 21.31L30.78 29.46H28.51L24.8 21.31V29.46H19.58L18.59 27.13H13.25L12.27 29.46H9.47L14.07 19.06ZM14.17 24.97L15.93 20.82L17.68 24.97H14.17Z"
      fill="#FAFAFA"
    />
  </svg>
);
