// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=24-20.svg

import type { IconProps } from "../../types";

export const IconSize2420 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 35 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2870" fill="white">
      <path d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z" />
    </mask>
    <path
      d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z"
      fill="#FAFAFA"
    />
    <path
      d="M6 0V1H29V0V-1H6V0ZM35 6H34V18H35H36V6H35ZM29 24V23H6V24V25H29V24ZM0 18H1V6H0H-1V18H0ZM6 24V23C3.24 23 1 20.76 1 18H0H-1C-1 21.87 2.13 25 6 25V24ZM35 18H34C34 20.76 31.76 23 29 23V24V25C32.87 25 36 21.87 36 18H35ZM29 0V1C31.76 1 34 3.24 34 6H35H36C36 2.13 32.87 -1 29 -1V0ZM6 0V-1C2.13 -1 -1 2.13 -1 6H0H1C1 3.24 3.24 1 6 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2870)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10.63 16.26H8.5L6.91 10.19C6.84 9.91 6.68 9.67 6.44 9.55C5.86 9.26 5.21 9.03 4.5 8.91V8.67H7.92C8.39 8.67 8.74 9.03 8.8 9.43L9.62 13.81L11.74 8.67H13.81L10.63 16.26ZM14.98 16.26H12.98L14.63 8.67H16.63L14.98 16.26ZM19.22 10.78C19.28 10.37 19.64 10.13 20.05 10.13C20.7 10.08 21.4 10.19 21.99 10.48L22.35 8.85C21.76 8.62 21.11 8.5 20.52 8.5C18.58 8.5 17.16 9.55 17.16 11.01C17.16 12.12 18.16 12.7 18.87 13.05C19.64 13.4 19.93 13.63 19.87 13.98C19.87 14.51 19.28 14.74 18.69 14.74C17.99 14.74 17.28 14.57 16.63 14.27L16.28 15.91C16.99 16.2 17.75 16.32 18.46 16.32C20.64 16.37 21.99 15.33 21.99 13.75C21.99 11.77 19.22 11.65 19.22 10.78ZM29 16.26L27.41 8.67H25.7C25.35 8.67 25 8.91 24.88 9.26L21.93 16.26H23.99L24.41 15.15H26.94L27.17 16.26H29ZM26 10.72L26.59 13.58H24.94L26 10.72Z"
      fill="#172B85"
    />
  </svg>
);
