// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=24-9.svg

import type { IconProps } from "../../types";

export const IconSize249 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 35 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2359" fill="white">
      <path d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z" />
    </mask>
    <path
      d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z"
      fill="#FAFAFA"
    />
    <path
      d="M6 0V1H29V0V-1H6V0ZM35 6H34V18H35H36V6H35ZM29 24V23H6V24V25H29V24ZM0 18H1V6H0H-1V18H0ZM6 24V23C3.24 23 1 20.76 1 18H0H-1C-1 21.87 2.13 25 6 25V24ZM35 18H34C34 20.76 31.76 23 29 23V24V25C32.87 25 36 21.87 36 18H35ZM29 0V1C31.76 1 34 3.24 34 6H35H36C36 2.13 32.87 -1 29 -1V0ZM6 0V-1C2.13 -1 -1 2.13 -1 6H0H1C1 3.24 3.24 1 6 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2359)"
    />
    <circle cx="17.43" cy="11.94" r="7.93" fill="#6481E7" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17.53 6.35V14.36L21.09 12.26L17.53 6.35Z"
      fill="#C1CCF5"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M13.97 12.26L17.53 14.36V6.35L13.97 12.26Z"
      fill="#FAFAFA"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17.53 10.64L13.97 12.26L17.53 14.36L21.09 12.26L17.53 10.64Z"
      fill="#8299EC"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17.53 10.64L13.97 12.26L17.53 14.36L17.53 10.64Z"
      fill="#C1CCF5"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M17.53 15.04V17.95L21.09 12.93L17.53 15.04Z"
      fill="#C1CCF5"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M13.97 12.93L17.53 17.95V15.04L13.97 12.93Z"
      fill="#FAFAFA"
    />
  </svg>
);
