// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=48-15.svg

import type { IconProps } from "../../types";

export const IconSize4815 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 70 48"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2862" fill="white">
      <path d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z" />
    </mask>
    <path
      d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z"
      fill="#FAFAFA"
    />
    <path
      d="M8 0V1H62V0V-1H8V0ZM70 8H69V40H70H71V8H70ZM62 48V47H8V48V49H62V48ZM0 40H1V8H0H-1V40H0ZM8 48V47C4.13 47 1 43.87 1 40H0H-1C-1 44.97 3.03 49 8 49V48ZM70 40H69C69 43.87 65.87 47 62 47V48V49C66.97 49 71 44.97 71 40H70ZM62 0V1C65.87 1 69 4.13 69 8H70H71C71 3.03 66.97 -1 62 -1V0ZM8 0V-1C3.03 -1 -1 3.03 -1 8H0H1C1 4.13 4.13 1 8 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2862)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M21.25 32.52H17.01L13.83 20.38C13.68 19.83 13.36 19.33 12.89 19.1C11.71 18.52 10.41 18.05 9 17.82V17.35H15.83C16.77 17.35 17.48 18.05 17.6 18.87L19.25 27.62L23.49 17.35H27.61L21.25 32.52ZM29.97 32.52H25.96L29.26 17.35H33.27L29.97 32.52ZM38.45 21.55C38.56 20.73 39.27 20.27 40.1 20.27C41.39 20.15 42.81 20.38 43.98 20.97L44.69 17.7C43.51 17.23 42.22 17 41.04 17C37.15 17 34.32 19.1 34.32 22.02C34.32 24.23 36.33 25.4 37.74 26.1C39.27 26.8 39.86 27.27 39.74 27.97C39.74 29.02 38.56 29.48 37.39 29.48C35.97 29.48 34.56 29.13 33.27 28.55L32.56 31.82C33.97 32.4 35.5 32.63 36.92 32.63C41.28 32.75 43.98 30.65 43.98 27.5C43.98 23.53 38.45 23.3 38.45 21.55ZM58 32.52L54.82 17.35H51.4C50.7 17.35 49.99 17.82 49.75 18.52L43.87 32.52H47.99L48.81 30.3H53.88L54.35 32.52H58ZM51.99 21.43L53.17 27.15H49.87L51.99 21.43Z"
      fill="#172B85"
    />
  </svg>
);
