// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-39.svg

import type { IconProps } from "../../types";

export const IconSize1639 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 23 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2369" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#FAFAFA"
    />
    <path
      d="M4 0V1H19V0V-1H4V0ZM23 4H22V12H23H24V4H23ZM19 16V15H4V16V17H19V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23 12H22C22 13.66 20.66 15 19 15V16V17C21.76 17 24 14.76 24 12H23ZM19 0V1C20.66 1 22 2.34 22 4H23H24C24 1.24 21.76 -1 19 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2369)"
    />
    <ellipse cx="11.46" cy="7.88" rx="5.21" ry="5.21" fill="#6481E7" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.52 4.21V9.48L13.86 8.09L11.52 4.21Z"
      fill="#C1CCF5"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.18 8.09L11.52 9.48V4.21L9.18 8.09Z"
      fill="#FAFAFA"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.52 7.03L9.18 8.09L11.52 9.48L13.86 8.09L11.52 7.03Z"
      fill="#8299EC"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.52 7.03L9.18 8.09L11.52 9.48L11.52 7.03Z"
      fill="#C1CCF5"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.52 9.92V11.83L13.86 8.54L11.52 9.92Z"
      fill="#C1CCF5"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.18 8.54L11.52 11.83V9.92L9.18 8.54Z"
      fill="#FAFAFA"
    />
  </svg>
);
