// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/message-system/size=default.svg

import type { IconProps } from "../../types";

export const IconSizeDefault = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 32 32"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16 2C23.73 2 30 8.27 30 16C30 23.73 23.73 30 16 30C8.27 30 2 23.73 2 16C2 8.27 8.27 2 16 2ZM8.6 25.44C10.64 27.04 13.2 28 16 28C22.63 28 28 22.63 28 16C28 13.21 27.04 10.63 25.44 8.59L8.6 25.44ZM16 4C9.37 4 4 9.37 4 16C4 19.19 5.25 22.09 7.28 24.25L24.24 7.28C22.09 5.25 19.19 4 16 4Z"
      fill="#6C6C6C"
    />
  </svg>
);
