// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-14.svg

import type { IconProps } from "../../types";

export const IconSize1614 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 23 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2878" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#FAFAFA"
    />
    <path
      d="M4 0V1H19V0V-1H4V0ZM23 4H22V12H23H24V4H23ZM19 16V15H4V16V17H19V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23 12H22C22 13.66 20.66 15 19 15V16V17C21.76 17 24 14.76 24 12H23ZM19 0V1C20.66 1 22 2.34 22 4H23H24C24 1.24 21.76 -1 19 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2878)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M7.03 10.84H5.63L4.59 6.79C4.54 6.61 4.43 6.44 4.28 6.37C3.89 6.17 3.46 6.02 3 5.94V5.78H5.24C5.55 5.78 5.79 6.02 5.83 6.29L6.37 9.21L7.76 5.78H9.11L7.03 10.84ZM9.89 10.84H8.57L9.66 5.78H10.97L9.89 10.84ZM12.68 7.18C12.71 6.91 12.95 6.76 13.22 6.76C13.64 6.72 14.11 6.79 14.49 6.99L14.73 5.9C14.34 5.74 13.91 5.67 13.53 5.67C12.25 5.67 11.32 6.37 11.32 7.34C11.32 8.08 11.98 8.47 12.44 8.7C12.95 8.93 13.14 9.09 13.1 9.32C13.1 9.67 12.71 9.83 12.33 9.83C11.86 9.83 11.4 9.71 10.97 9.52L10.74 10.61C11.21 10.8 11.71 10.88 12.17 10.88C13.6 10.92 14.49 10.22 14.49 9.17C14.49 7.84 12.68 7.77 12.68 7.18ZM19.1 10.84L18.06 5.78H16.93C16.7 5.78 16.47 5.94 16.39 6.17L14.46 10.84H15.81L16.08 10.1H17.75L17.9 10.84H19.1ZM17.13 7.14L17.51 9.05H16.43L17.13 7.14Z"
      fill="#172B85"
    />
  </svg>
);
