// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=24-25.svg

import type { IconProps } from "../../types";

export const IconSize2425 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 35 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_1301" fill="white">
      <path d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z" />
    </mask>
    <path
      d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z"
      fill="#3D95CE"
    />
    <path
      d="M6 0V1H29V0V-1H6V0ZM35 6H34V18H35H36V6H35ZM29 24V23H6V24V25H29V24ZM0 18H1V6H0H-1V18H0ZM6 24V23C3.24 23 1 20.76 1 18H0H-1C-1 21.87 2.13 25 6 25V24ZM35 18H34C34 20.76 31.76 23 29 23V24V25C32.87 25 36 21.87 36 18H35ZM29 0V1C31.76 1 34 3.24 34 6H35H36C36 2.13 32.87 -1 29 -1V0ZM6 0V-1C2.13 -1 -1 2.13 -1 6H0H1C1 3.24 3.24 1 6 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_1301)"
    />
    <path
      d="M23.27 8.46C23.27 11.52 20.72 15.51 18.64 18.3H13.9L12 6.67L16.15 6.27L17.16 14.54C18.1 12.98 19.25 10.52 19.25 8.84C19.25 7.92 19.1 7.3 18.86 6.78L22.64 6C23.08 6.74 23.27 7.5 23.27 8.46Z"
      fill="#FAFAFA"
    />
  </svg>
);
