// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=48-3.svg

import type { IconProps } from "../../types";

export const IconSize483 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 70 48"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2694" fill="white">
      <path d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z" />
    </mask>
    <path
      d="M0 8C0 3.58 3.58 0 8 0H62C66.42 0 70 3.58 70 8V40C70 44.42 66.42 48 62 48H8C3.58 48 0 44.42 0 40V8Z"
      fill="#FAFAFA"
    />
    <path
      d="M8 0V1H62V0V-1H8V0ZM70 8H69V40H70H71V8H70ZM62 48V47H8V48V49H62V48ZM0 40H1V8H0H-1V40H0ZM8 48V47C4.13 47 1 43.87 1 40H0H-1C-1 44.97 3.03 49 8 49V48ZM70 40H69C69 43.87 65.87 47 62 47V48V49C66.97 49 71 44.97 71 40H70ZM62 0V1C65.87 1 69 4.13 69 8H70H71C71 3.03 66.97 -1 62 -1V0ZM8 0V-1C3.03 -1 -1 3.03 -1 8H0H1C1 4.13 4.13 1 8 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2694)"
    />
    <path
      d="M26.54 10.45C34.08 10.45 40.19 16.63 40.19 24.25C40.19 31.88 34.08 38.06 26.54 38.06C19 38.06 12.89 31.88 12.89 24.25C12.89 16.63 19 10.45 26.54 10.45Z"
      fill="#ED0006"
    />
    <path
      d="M44.25 10.45C51.78 10.45 57.89 16.63 57.89 24.25C57.89 31.88 51.78 38.06 44.25 38.06C36.71 38.06 30.6 31.88 30.6 24.25C30.6 16.63 36.71 10.45 44.25 10.45Z"
      fill="#0099DF"
    />
    <path
      d="M35.39 13.75C38.33 16.28 40.19 20.05 40.19 24.25C40.19 28.46 38.33 32.23 35.39 34.76C32.46 32.23 30.6 28.46 30.6 24.25C30.6 20.05 32.46 16.28 35.39 13.75Z"
      fill="#6C6BBD"
    />
  </svg>
);
