// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-26.svg

import type { IconProps } from "../../types";

export const IconSize1626 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_1304" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19.33C21.54 0 23.33 1.79 23.33 4V12C23.33 14.21 21.54 16 19.33 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19.33C21.54 0 23.33 1.79 23.33 4V12C23.33 14.21 21.54 16 19.33 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#3D95CE"
    />
    <path
      d="M4 0V1H19.33V0V-1H4V0ZM23.33 4H22.33V12H23.33H24.33V4H23.33ZM19.33 16V15H4V16V17H19.33V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23.33 12H22.33C22.33 13.66 20.99 15 19.33 15V16V17C22.09 17 24.33 14.76 24.33 12H23.33ZM19.33 0V1C20.99 1 22.33 2.34 22.33 4H23.33H24.33C24.33 1.24 22.09 -1 19.33 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_1304)"
    />
    <path
      d="M15.52 5.64C15.52 7.68 13.81 10.34 12.43 12.2H9.27L8 4.45L10.77 4.18L11.44 9.7C12.06 8.65 12.84 7.01 12.84 5.89C12.84 5.28 12.73 4.87 12.57 4.52L15.09 4C15.39 4.49 15.52 5 15.52 5.64Z"
      fill="#FAFAFA"
    />
  </svg>
);
