// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-10.svg

import type { IconProps } from "../../types";

export const IconSize1610 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 23 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2343" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#FAFAFA"
    />
    <path
      d="M4 0V1H19V0V-1H4V0ZM23 4H22V12H23H24V4H23ZM19 16V15H4V16V17H19V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23 12H22C22 13.66 20.66 15 19 15V16V17C21.76 17 24 14.76 24 12H23ZM19 0V1C20.66 1 22 2.34 22 4H23H24C24 1.24 21.76 -1 19 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2343)"
    />
    <path
      d="M11.46 2.67C14.34 2.67 16.67 5.04 16.67 7.96C16.67 10.88 14.34 13.25 11.46 13.25C8.58 13.25 6.24 10.88 6.24 7.96C6.24 5.03 8.58 2.67 11.46 2.67ZM10.19 7.96L9.55 8.21L9.36 8.92L9.99 8.67L9.55 10.41H13.94L14.19 9.38H11.46L11.84 7.96L12.6 7.7L12.79 6.99L12.03 7.31L12.6 5.05H10.95L10.19 7.96Z"
      fill="#A5A8A9"
    />
  </svg>
);
