// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=24-2.svg

import type { IconProps } from "../../types";

export const IconSize242 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 35 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2704" fill="white">
      <path d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z" />
    </mask>
    <path
      d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z"
      fill="#FAFAFA"
    />
    <path
      d="M6 0V1H29V0V-1H6V0ZM35 6H34V18H35H36V6H35ZM29 24V23H6V24V25H29V24ZM0 18H1V6H0H-1V18H0ZM6 24V23C3.24 23 1 20.76 1 18H0H-1C-1 21.87 2.13 25 6 25V24ZM35 18H34C34 20.76 31.76 23 29 23V24V25C32.87 25 36 21.87 36 18H35ZM29 0V1C31.76 1 34 3.24 34 6H35H36C36 2.13 32.87 -1 29 -1V0ZM6 0V-1C2.13 -1 -1 2.13 -1 6H0H1C1 3.24 3.24 1 6 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2704)"
    />
    <path
      d="M13.27 5.22C17.04 5.22 20.09 8.32 20.09 12.13C20.09 15.94 17.04 19.03 13.27 19.03C9.5 19.03 6.45 15.94 6.45 12.13C6.45 8.32 9.5 5.22 13.27 5.22Z"
      fill="#ED0006"
    />
    <path
      d="M22.12 5.22C25.89 5.22 28.95 8.32 28.95 12.13C28.95 15.94 25.89 19.03 22.12 19.03C18.36 19.03 15.3 15.94 15.3 12.13C15.3 8.32 18.36 5.22 22.12 5.22Z"
      fill="#0099DF"
    />
    <path
      d="M17.7 6.88C19.16 8.14 20.09 10.02 20.09 12.13C20.09 14.23 19.16 16.11 17.7 17.38C16.23 16.11 15.3 14.23 15.3 12.13C15.3 10.02 16.23 8.14 17.7 6.88Z"
      fill="#6C6BBD"
    />
  </svg>
);
