// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-3.svg

import type { IconProps } from "../../types";

export const IconSize163 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 23 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2714" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#FAFAFA"
    />
    <path
      d="M4 0V1H19V0V-1H4V0ZM23 4H22V12H23H24V4H23ZM19 16V15H4V16V17H19V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23 12H22C22 13.66 20.66 15 19 15V16V17C21.76 17 24 14.76 24 12H23ZM19 0V1C20.66 1 22 2.34 22 4H23H24C24 1.24 21.76 -1 19 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2714)"
    />
    <path
      d="M8.39 3C11.09 3 13.28 5.21 13.28 7.95C13.28 10.68 11.09 12.89 8.39 12.89C5.69 12.89 3.5 10.68 3.5 7.95C3.5 5.21 5.69 3 8.39 3Z"
      fill="#ED0006"
    />
    <path
      d="M14.73 3C17.43 3 19.62 5.21 19.62 7.95C19.62 10.68 17.43 12.89 14.73 12.89C12.03 12.89 9.84 10.68 9.84 7.95C9.84 5.21 12.03 3 14.73 3Z"
      fill="#0099DF"
    />
    <path
      d="M11.56 4.18C12.61 5.09 13.28 6.44 13.28 7.94C13.28 9.45 12.61 10.8 11.56 11.71C10.51 10.8 9.84 9.45 9.84 7.94C9.84 6.44 10.51 5.09 11.56 4.18Z"
      fill="#6C6BBD"
    />
  </svg>
);
