// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-27.svg

import type { IconProps } from "../../types";

export const IconSize1627 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_1287" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19.33C21.54 0 23.33 1.79 23.33 4V12C23.33 14.21 21.54 16 19.33 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19.33C21.54 0 23.33 1.79 23.33 4V12C23.33 14.21 21.54 16 19.33 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#FAFAFA"
    />
    <path
      d="M4 0V1H19.33V0V-1H4V0ZM23.33 4H22.33V12H23.33H24.33V4H23.33ZM19.33 16V15H4V16V17H19.33V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23.33 12H22.33C22.33 13.66 20.99 15 19.33 15V16V17C22.09 17 24.33 14.76 24.33 12H23.33ZM19.33 0V1C20.99 1 22.33 2.34 22.33 4H23.33H24.33C24.33 1.24 22.09 -1 19.33 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_1287)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.22 5H6.24V5.48H6.22C4.99 5.48 3.95 6.29 3.61 7.41L3.14 7.26C3.55 5.95 4.77 5 6.22 5Z"
      fill="url(#paint0_linear_268_1287)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.24 5.48V5H6.22C7.67 5 8.89 5.96 9.3 7.27L8.84 7.42C8.5 6.31 7.46 5.49 6.24 5.48Z"
      fill="url(#paint1_linear_268_1287)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M7.83 10.43L8.11 10.82C7.56 11.22 6.9 11.44 6.22 11.44C5.55 11.44 4.9 11.23 4.35 10.84L4.64 10.45C5.08 10.77 5.63 10.95 6.22 10.95C6.82 10.95 7.37 10.76 7.83 10.43Z"
      fill="url(#paint2_linear_268_1287)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M3.14 7.26L3.61 7.41C3.52 7.67 3.48 7.94 3.48 8.22C3.48 9.14 3.94 9.95 4.64 10.45L4.35 10.84C3.56 10.28 3.04 9.37 3 8.33V8.11C3.01 7.81 3.06 7.53 3.14 7.26Z"
      fill="url(#paint3_linear_268_1287)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.44 8.22C9.44 9.29 8.92 10.24 8.11 10.82L7.83 10.43C8.17 10.18 8.46 9.85 8.65 9.47C8.85 9.08 8.95 8.65 8.95 8.22C8.95 7.94 8.91 7.67 8.84 7.42L9.3 7.27C9.39 7.57 9.44 7.89 9.44 8.22V8.22Z"
      fill="url(#paint4_linear_268_1287)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M7.73 8.7C7.73 8.53 7.61 8.45 7.35 8.45H6.71V8.94H7.35C7.61 8.94 7.73 8.87 7.73 8.7ZM7.26 7.68H6.71V8.17H7.26C7.51 8.17 7.62 8.09 7.62 7.92C7.62 7.76 7.51 7.68 7.26 7.68ZM8.06 8.73C8.06 9.05 7.8 9.23 7.35 9.23H6.41C6.39 9.23 6.38 9.22 6.38 9.21V7.41C6.38 7.4 6.39 7.39 6.41 7.39H7.27C7.71 7.39 7.95 7.56 7.95 7.86C7.95 8.05 7.87 8.19 7.63 8.26C7.93 8.32 8.05 8.5 8.06 8.73ZM5.99 7.41V7.66C5.99 7.68 5.98 7.69 5.96 7.69H4.87V8.16H5.78C5.79 8.16 5.81 8.17 5.81 8.18V8.44C5.81 8.45 5.79 8.46 5.78 8.46H4.88V9.21C4.88 9.22 4.86 9.23 4.85 9.23H4.57C4.56 9.23 4.55 9.22 4.55 9.21V7.41C4.55 7.4 4.56 7.39 4.57 7.39H5.96C5.98 7.39 5.99 7.4 5.99 7.41H5.99Z"
      fill="#64717D"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M18.33 7.14C18.6 7.96 18.9 8.77 19.25 9.56L20.09 7.14H20.77L19.56 10.27C19.4 10.67 19.22 10.98 19.01 11.2C18.8 11.41 18.51 11.52 18.15 11.52C18.07 11.52 17.98 11.52 17.9 11.5V10.95C17.97 10.97 18.03 10.97 18.08 10.97C18.29 10.97 18.47 10.91 18.61 10.79C18.74 10.67 18.86 10.49 18.96 10.26C18.71 9.75 18.47 9.24 18.25 8.72C18.03 8.2 17.82 7.67 17.61 7.14H18.33ZM15.83 7.06C16.21 7.06 16.51 7.17 16.74 7.38C16.97 7.6 17.09 7.92 17.09 8.35V10.17H16.49V9.68C16.37 9.86 16.22 9.99 16.03 10.09C15.83 10.19 15.61 10.24 15.39 10.23C15.07 10.23 14.81 10.15 14.63 9.99C14.45 9.82 14.36 9.6 14.36 9.34C14.36 9.07 14.46 8.84 14.67 8.66C14.87 8.48 15.19 8.39 15.64 8.39H16.48V8.38C16.48 7.87 16.24 7.62 15.76 7.62C15.56 7.62 15.4 7.65 15.26 7.72C15.12 7.8 15.01 7.89 14.93 8.02L14.5 7.69C14.63 7.48 14.81 7.33 15.02 7.22C15.25 7.11 15.5 7.06 15.76 7.06H15.83L15.83 7.06ZM12.31 5.92C12.86 5.92 13.26 6.05 13.53 6.3C13.8 6.56 13.93 6.9 13.93 7.34C13.93 7.77 13.8 8.11 13.53 8.37C13.26 8.62 12.86 8.75 12.31 8.75H11.15V10.17H10.5V5.92H12.31H12.31ZM16.48 8.87H15.66C15.42 8.87 15.25 8.91 15.14 8.99C15.09 9.02 15.05 9.07 15.03 9.12C15 9.17 14.99 9.23 14.99 9.29C14.99 9.56 15.17 9.69 15.53 9.69C15.77 9.69 15.97 9.64 16.13 9.53C16.28 9.43 16.4 9.28 16.48 9.1V8.87ZM12.25 6.52H11.15V8.16H12.25C12.6 8.16 12.86 8.09 13.02 7.95C13.18 7.82 13.26 7.61 13.26 7.34C13.26 7.06 13.18 6.86 13.02 6.72C12.86 6.58 12.6 6.52 12.25 6.52H12.25Z"
      fill="#1B2529"
    />
    <defs>
      <linearGradient
        id="paint0_linear_268_1287"
        x1="6.24"
        y1="5.63"
        x2="3.76"
        y2="7.42"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#24D365" />
        <stop offset="1" stopColor="#139DBD" />
      </linearGradient>
      <linearGradient
        id="paint1_linear_268_1287"
        x1="6.22"
        y1="5.61"
        x2="8.7"
        y2="7.42"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#23D068" />
        <stop offset="0.52" stopColor="#EACD36" />
        <stop offset="1" stopColor="#FF6C5C" />
      </linearGradient>
      <linearGradient
        id="paint2_linear_268_1287"
        x1="4.49"
        y1="10.65"
        x2="7.96"
        y2="10.65"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#266FF3" />
        <stop offset="1" stopColor="#C439D6" />
      </linearGradient>
      <linearGradient
        id="paint3_linear_268_1287"
        x1="3.96"
        y1="10.66"
        x2="2.92"
        y2="7.62"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#266FF3" />
        <stop offset="1" stopColor="#149FBA" />
      </linearGradient>
      <linearGradient
        id="paint4_linear_268_1287"
        x1="8.73"
        y1="7.35"
        x2="7.68"
        y2="10.37"
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#FF6C5C" />
        <stop offset="1" stopColor="#C439D6" />
      </linearGradient>
    </defs>
  </svg>
);
