// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=24-6.svg

import type { IconProps } from "../../types";

export const IconSize246 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 35 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2823" fill="white">
      <path d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z" />
    </mask>
    <path
      d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z"
      fill="#1F72CD"
    />
    <path
      d="M6 0V1H29V0V-1H6V0ZM35 6H34V18H35H36V6H35ZM29 24V23H6V24V25H29V24ZM0 18H1V6H0H-1V18H0ZM6 24V23C3.24 23 1 20.76 1 18H0H-1C-1 21.87 2.13 25 6 25V24ZM35 18H34C34 20.76 31.76 23 29 23V24V25C32.87 25 36 21.87 36 18H35ZM29 0V1C31.76 1 34 3.24 34 6H35H36C36 2.13 32.87 -1 29 -1V0ZM6 0V-1C2.13 -1 -1 2.13 -1 6H0H1C1 3.24 3.24 1 6 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2823)"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.68 8.5L3.5 15.75H7.31L7.78 14.59H8.86L9.33 15.75H13.52V14.86L13.9 15.75H16.07L16.44 14.85V15.75H25.16L26.22 14.62L27.21 15.75L31.69 15.76L28.5 12.14L31.69 8.5H27.28L26.25 9.6L25.29 8.5H15.8L14.99 10.37L14.15 8.5H10.35V9.35L9.93 8.5H6.68ZM19.7 9.53H24.71L26.24 11.23L27.82 9.53H29.35L27.02 12.14L29.35 14.73H27.75L26.22 13L24.63 14.73H19.7V9.53ZM20.94 11.55V10.61V10.6H24.06L25.42 12.12L24 13.65H20.94V12.61H23.67V11.55H20.94ZM7.42 9.53H9.27L11.38 14.44V9.53H13.42L15.05 13.05L16.55 9.53H18.57V14.73H17.34L17.33 10.65L15.54 14.73H14.44L12.63 10.65V14.73H10.1L9.62 13.56H7.02L6.54 14.73H5.19L7.42 9.53ZM7.47 12.49L8.32 10.41L9.17 12.49H7.47Z"
      fill="#FAFAFA"
    />
  </svg>
);
