// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-31.svg

import type { IconProps } from "../../types";

export const IconSize1631 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 23 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2092" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#FAFAFA"
    />
    <path
      d="M4 0V1H19V0V-1H4V0ZM23 4H22V12H23H24V4H23ZM19 16V15H4V16V17H19V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23 12H22C22 13.66 20.66 15 19 15V16V17C21.76 17 24 14.76 24 12H23ZM19 0V1C20.66 1 22 2.34 22 4H23H24C24 1.24 21.76 -1 19 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2092)"
    />
    <path
      d="M11.72 3.3C15.44 3.3 16.87 5.37 16.87 7.97C16.87 11.09 14.87 12.66 11.72 12.66H6.25V3.3H11.72ZM6.77 12.13H11.72C14.71 12.13 16.34 10.71 16.34 7.99C16.34 5.18 14.58 3.86 11.72 3.86H6.77V12.13ZM9.03 11.44H7.44V8.57H9.03V11.44ZM8.23 6.12C8.78 6.12 9.22 6.57 9.22 7.13C9.22 7.69 8.78 8.14 8.23 8.14C7.69 8.14 7.24 7.69 7.24 7.13C7.24 6.58 7.69 6.12 8.23 6.12Z"
      fill="currentColor"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M14.53 6.21H14.99V7.59H15.65C15.48 5.07 13.51 4.51 11.72 4.51H9.82V6.21H10.1C10.62 6.21 10.93 6.55 10.93 7.13C10.93 7.71 10.62 8.05 10.12 8.05H9.82V11.44H11.72C14.63 11.44 15.62 10.07 15.67 8.05H14.53V6.21ZM12.34 7.59V8.05H11.2V6.21H12.31V6.67H11.66V6.88H12.28V7.35H11.68V7.59H12.34ZM12.54 8.05L13.09 6.21H13.74L14.29 8.05H13.82L13.72 7.71H13.12L13.02 8.05H12.54ZM13.26 7.23H13.25V7.25L13.26 7.23ZM13.26 7.23H13.58L13.43 6.72H13.41L13.26 7.23ZM9.82 7.59V6.67H10.1C10.28 6.67 10.47 6.72 10.47 7.13C10.47 7.54 10.3 7.59 10.1 7.59H9.82Z"
      fill="#D50072"
    />
  </svg>
);
