// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=16-33.svg

import type { IconProps } from "../../types";

export const IconSize1633 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 23 16"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2749" fill="white">
      <path d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z" />
    </mask>
    <path
      d="M0 4C0 1.79 1.79 0 4 0H19C21.21 0 23 1.79 23 4V12C23 14.21 21.21 16 19 16H4C1.79 16 0 14.21 0 12V4Z"
      fill="#FAFAFA"
    />
    <path
      d="M4 0V1H19V0V-1H4V0ZM23 4H22V12H23H24V4H23ZM19 16V15H4V16V17H19V16ZM0 12H1V4H0H-1V12H0ZM4 16V15C2.34 15 1 13.66 1 12H0H-1C-1 14.76 1.24 17 4 17V16ZM23 12H22C22 13.66 20.66 15 19 15V16V17C21.76 17 24 14.76 24 12H23ZM19 0V1C20.66 1 22 2.34 22 4H23H24C24 1.24 21.76 -1 19 -1V0ZM4 0V-1C1.24 -1 -1 1.24 -1 4H0H1C1 2.34 2.34 1 4 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2749)"
    />
    <path
      d="M14.97 2.99C17.75 2.99 20 5.21 20 7.94C20 10.67 17.75 12.88 14.97 12.88C13.73 12.88 12.59 12.43 11.71 11.7C10.84 12.43 9.7 12.88 8.45 12.88C5.68 12.88 3.43 10.66 3.43 7.94C3.43 5.21 5.68 2.99 8.45 2.99C9.7 2.99 10.84 3.44 11.71 4.17C12.59 3.44 13.73 2.99 14.97 2.99Z"
      fill="#ED0006"
    />
    <path
      d="M14.97 2.99C17.75 2.99 20 5.21 20 7.94C20 10.67 17.75 12.88 14.97 12.88C13.73 12.88 12.59 12.43 11.71 11.69C12.79 10.79 13.48 9.44 13.48 7.94C13.48 6.43 12.79 5.08 11.71 4.18C12.59 3.44 13.73 2.99 14.97 2.99Z"
      fill="#F9A000"
    />
    <path
      d="M11.71 4.17C12.79 5.08 13.48 6.43 13.48 7.94C13.48 9.44 12.79 10.79 11.71 11.7C10.63 10.79 9.95 9.44 9.95 7.94C9.95 6.43 10.63 5.08 11.71 4.17Z"
      fill="#FF5E00"
    />
  </svg>
);
