// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=24-18.svg

import type { IconProps } from "../../types";

export const IconSize2418 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 35 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2076" fill="white">
      <path d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z" />
    </mask>
    <path
      d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z"
      fill="#FAFAFA"
    />
    <path
      d="M6 0V1H29V0V-1H6V0ZM35 6H34V18H35H36V6H35ZM29 24V23H6V24V25H29V24ZM0 18H1V6H0H-1V18H0ZM6 24V23C3.24 23 1 20.76 1 18H0H-1C-1 21.87 2.13 25 6 25V24ZM35 18H34C34 20.76 31.76 23 29 23V24V25C32.87 25 36 21.87 36 18H35ZM29 0V1C31.76 1 34 3.24 34 6H35H36C36 2.13 32.87 -1 29 -1V0ZM6 0V-1C2.13 -1 -1 2.13 -1 6H0H1C1 3.24 3.24 1 6 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2076)"
    />
    <path
      d="M17.84 4.96C23.5 4.96 25.68 8.05 25.68 11.96C25.68 16.63 22.64 18.98 17.84 18.99H9.51V4.96H17.84ZM10.3 18.19H17.84C22.39 18.19 24.86 16.07 24.86 11.98C24.86 7.78 22.19 5.8 17.84 5.8H10.3V18.19ZM13.74 17.16H11.32V12.85H13.74V17.16ZM12.53 9.19C13.36 9.19 14.04 9.86 14.04 10.7C14.04 11.53 13.36 12.21 12.53 12.21C11.7 12.21 11.02 11.53 11.02 10.7C11.02 9.86 11.7 9.19 12.53 9.19Z"
      fill="currentColor"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M22.12 9.31H22.81V11.39H23.82C23.55 7.6 20.56 6.76 17.84 6.76H14.95V9.31H15.37C16.16 9.31 16.63 9.83 16.63 10.7C16.63 11.56 16.16 12.08 15.4 12.08H14.95V17.15H17.84C22.27 17.15 23.77 15.1 23.85 12.08H22.12V9.31ZM18.78 11.39V12.08H17.05V9.31H18.73V10H17.74V10.33H18.68V11.02H17.77V11.39H18.78ZM19.08 12.08L19.92 9.31H20.91L21.75 12.08H21.03L20.88 11.56H19.97L19.82 12.08H19.08ZM20.17 10.84H20.16V10.87L20.17 10.84ZM20.17 10.84H20.66L20.44 10.08H20.41L20.17 10.84ZM14.95 11.39V10H15.37C15.64 10 15.94 10.08 15.94 10.7C15.94 11.31 15.67 11.39 15.37 11.39H14.95Z"
      fill="#D50072"
    />
  </svg>
);
