// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/payment_method/Size=24-1.svg

import type { IconProps } from "../../types";

export const IconSize241 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 35 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <mask id="path-1-inside-1_268_2737" fill="white">
      <path d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z" />
    </mask>
    <path
      d="M0 6C0 2.69 2.69 0 6 0H29C32.31 0 35 2.69 35 6V18C35 21.31 32.31 24 29 24H6C2.69 24 0 21.31 0 18V6Z"
      fill="#FAFAFA"
    />
    <path
      d="M6 0V1H29V0V-1H6V0ZM35 6H34V18H35H36V6H35ZM29 24V23H6V24V25H29V24ZM0 18H1V6H0H-1V18H0ZM6 24V23C3.24 23 1 20.76 1 18H0H-1C-1 21.87 2.13 25 6 25V24ZM35 18H34C34 20.76 31.76 23 29 23V24V25C32.87 25 36 21.87 36 18H35ZM29 0V1C31.76 1 34 3.24 34 6H35H36C36 2.13 32.87 -1 29 -1V0ZM6 0V-1C2.13 -1 -1 2.13 -1 6H0H1C1 3.24 3.24 1 6 1V0Z"
      fill="#DCDCDC"
      mask="url(#path-1-inside-1_268_2737)"
    />
    <path
      d="M22.18 5C25.94 5 29 8.09 29 11.9C29 15.72 25.94 18.81 22.18 18.81C20.49 18.81 18.94 18.18 17.75 17.15C16.56 18.18 15.01 18.81 13.32 18.81C9.56 18.81 6.5 15.72 6.5 11.9C6.5 8.09 9.56 5 13.32 5C15.01 5 16.56 5.62 17.75 6.65C18.94 5.62 20.49 5 22.18 5Z"
      fill="#ED0006"
    />
    <path
      d="M22.18 5C25.94 5 29 8.09 29 11.9C29 15.72 25.94 18.81 22.18 18.81C20.49 18.81 18.94 18.18 17.75 17.15C19.22 15.89 20.15 14.01 20.15 11.9C20.15 9.8 19.22 7.92 17.75 6.65C18.94 5.62 20.49 5 22.18 5Z"
      fill="#F9A000"
    />
    <path
      d="M17.75 6.65C19.22 7.92 20.15 9.8 20.15 11.9C20.15 14.01 19.22 15.89 17.75 17.15C16.28 15.89 15.35 14.01 15.35 11.9C15.35 9.8 16.28 7.92 17.75 6.65Z"
      fill="#FF5E00"
    />
  </svg>
);
