// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/update_plan/meaning-12.svg

import type { IconProps } from "../../types";

export const IconToastSuccess = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 68 68"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M34.59 11.34C46.83 11.65 56.67 21.68 56.67 34L56.66 34.59C56.35 46.83 46.32 56.67 34 56.67L33.41 56.66C21.36 56.35 11.65 46.64 11.34 34.59L11.33 34C11.33 21.48 21.48 11.33 34 11.33L34.59 11.34ZM34 13.83C22.86 13.83 13.83 22.86 13.83 34C13.83 45.14 22.86 54.17 34 54.17C45.14 54.17 54.17 45.14 54.17 34C54.17 22.86 45.14 13.83 34 13.83ZM41.63 27.44C42.13 26.96 42.92 26.97 43.4 27.46C43.88 27.96 43.87 28.75 43.37 29.23L31.68 40.56C31.2 41.03 30.43 41.03 29.94 40.56L24.63 35.41C24.13 34.93 24.12 34.14 24.6 33.65C25.08 33.15 25.87 33.14 26.37 33.62L30.81 37.93L41.63 27.44Z"
      fill="#F71C1C"
    />
  </svg>
);
