// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/graphics/Vector-1.svg

import type { IconProps } from "../../types";

export const IconVector1 = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 3 2"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M1.75 0.75L0.75 0.75"
      stroke="#BEBEBE"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);
