import {
  EAIART_STYLE,
  EAIART_TYPE,
} from "@/core/models/chat-features/image-creation";
import type { TSelectedAIArt } from "@/core/models/conversation";
import type { TAIArtOptions } from "@/core/ports/chat-features/image-creation";
import { generateRandomUUIDV4 } from "@/utils/commons/helpers";
import { AI_ART_STYLES_IMAGE } from "@/utils/constants/cdn";

// const AI_ART_SAMPLE_PROMPT = [
//   {
//     id: generateRandomUUIDV4(),
//     artId: EAIART_STYLE.PAINTING,
//     title: "Create an image of a cute fluffy dog playing in a garden ",
//   },
//   {
//     id: generateRandomUUIDV4(),
//     artId: EAIART_STYLE.WATERCOLOR,
//     title:
//       "Create an image of a tropical bird with colorful feathers in style watercolor",
//   },
//   {
//     id: generateRandomUUIDV4(),
//     artId: EAIART_STYLE.REALISTIC,
//     title: "Create an image of a stormy ocean in style realistic",
//   },
// ];

// Shared across every style catalog's "None" entry and the store's default
// selection, so the "None" card highlights correctly before any catalog sync
// effect runs (each catalog's own random id would never match otherwise).
export const NONE_AI_ART_STYLE_ID = "ai-art-style-none";

export const defaultAIArtStyle: TSelectedAIArt = {
  description: "",
  id: NONE_AI_ART_STYLE_ID,
  image: AI_ART_STYLES_IMAGE.NONE,
  maxImages: 4,
  title: "None",
  type: EAIART_TYPE.IMAGE_TO_IMAGE,
  value: EAIART_STYLE.NONE,
};

// Image to Image Options
export const NANO_BANANA_STYLE_VERSION_1_OPTIONS: TAIArtOptions[] = [
  {
    description: "",
    id: NONE_AI_ART_STYLE_ID,
    image: AI_ART_STYLES_IMAGE.NONE,
    isEnabled: true,
    isNew: false,
    maxImages: 4,
    title: "None",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.NONE,
  },
  {
    description:
      "Transform yourself into a lifelike collectible figure with detailed realism.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.REALISTIC_FIGURE,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Realistic Figurine",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.REALISTIC_FIGURE,
  },
  {
    description:
      "Place your portrait inside a modern gallery setting, like an art exhibition.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ART_GALLEY,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Art Gallery",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.ART_GALLEY,
  },
  {
    description:
      "Blend your photo with creative overlays for a surreal double-exposure effect.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.DOUBLE_POTRAIT,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Double Portrait",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.DOUBLE_POTRAIT,
  },
  {
    description:
      "Dramatic spotlight portraits with cinematic mood and soft shadows.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.STUDIO_PORTRAIT,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Studio Portrait",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.STUDIO_PORTRAIT,
  },
  {
    description:
      "Celebrate with a festive birthday scene featuring cake, candles, and joy.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.BIRTHDAY,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Birthday",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.BIRTHDAY,
  },
  {
    description: "Bold fashion-poster look with a graphic circle backdrop.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.POSTER_DESIGN,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Poster Design",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.POSTER_DESIGN,
  },
  {
    description:
      "Immersive music vibe, placing you inside a digital playlist scene.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.SPOTIFY,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Music",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.SPOTIFY,
  },
  {
    description: "Relax in a cozy, stylish scene surrounded by adorable cats.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.MEOWCHIC,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Meowchic",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.MEOWCHIC,
  },
  {
    description:
      "Be immersed in a warm autumn atmosphere with falling leaves and golden tones.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.AUTUMN,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Autumn",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.AUTUMN,
  },
  {
    description: "Snowy wonderland with aurora skies and icy landscapes.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.WINTER,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Winter",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.WINTER,
  },
  {
    description:
      "Transport yourself to Santorini’s iconic white houses and blue domes.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.SANTORINI,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Santorini",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.SANTORINI,
  },
  {
    description: "Cherry blossoms & Mount Fuji in Japan.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.MOUNT_FUJI,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Japan",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.MOUNT_FUJI,
  },
  {
    description:
      "Stand before the Taj Mahal for a majestic and timeless backdrop.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.TAJ_MAHAL,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Taj Mahal",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.TAJ_MAHAL,
  },
  {
    description:
      "Stand before Rome’s iconic Colosseum in a timeless cityscape.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ROME,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Rome",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.ROME,
  },
  {
    description:
      "Feature yourself with the romantic charm of Paris and the Eiffel Tower.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.PARIS,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Paris",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.PARIS,
  },
  {
    description: "Immerse yourself in Venice’s canals and gondola charm.",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.VENICE,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Venice",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.VENICE,
  },
];

// const NANO_BANANA_STYLE_VERSION_2_OPTIONS: TAIArtOptions[] = [
//   {
//     id: generateRandomUUIDV4(),
//     title: "None",
//     description: "",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.NONE,
//     value: EAIART_STYLE.NONE,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 4,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Mirror",
//     description:
//       "A haunting mirror reflection revealing eerie masked figures behind you.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.MIRROR,
//     value: EAIART_STYLE.MIRROR,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Shadow Monarch",
//     description:
//       "Sitting on a dark throne with a glowing halo, guarded by horror icons.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.SHADOWN_MONARCH,
//     value: EAIART_STYLE.SHADOWN_MONARCH,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Halloween Portrait",
//     description:
//       "Elegant black-and-white portrait with eerie shadows revealing a darker side.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.HALLOWEEN_PORTRAIT,
//     value: EAIART_STYLE.HALLOWEEN_PORTRAIT,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Pennywise",
//     description:
//       "Enter the chilling world of the clown with red balloons and eerie mist.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.PENNYWISE,
//     value: EAIART_STYLE.PENNYWISE,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Happy Death Day",
//     description:
//       "A dark birthday scene with a candlelit cake and a masked figure watching.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.HAPPY_DEATH_DATE,
//     value: EAIART_STYLE.HAPPY_DEATH_DATE,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Realistic Figurine",
//     description:
//       "Transform yourself into a lifelike collectible figure with detailed realism.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.REALISTIC_FIGURE,
//     value: EAIART_STYLE.REALISTIC_FIGURE,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Studio Portrait",
//     description:
//       "Dramatic spotlight portraits with cinematic mood and soft shadows.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.STUDIO_PORTRAIT,
//     value: EAIART_STYLE.STUDIO_PORTRAIT,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Art Gallery",
//     description:
//       "Place your portrait inside a modern gallery setting, like an art exhibition.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.ART_GALLEY,
//     value: EAIART_STYLE.ART_GALLEY,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Birthday",
//     description:
//       "Celebrate with a festive birthday scene featuring cake, candles, and joy.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.BIRTHDAY,
//     value: EAIART_STYLE.BIRTHDAY,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Horror Kitchen",
//     description:
//       "A haunted kitchen scene with carved pumpkins and lurking terror.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.HORROR_KITCHEN,
//     value: EAIART_STYLE.HORROR_KITCHEN,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Scary House",
//     description:
//       "A haunted home setting with glowing pumpkins and lurking shadows.",
//     isNew: true,
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.SCARY_HOUSE,
//     value: EAIART_STYLE.SCARY_HOUSE,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Pennywise Custom",
//     description:
//       "Dressed in a creepy clown costume with red balloons, standing against a dark, eerie backdrop.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.PENNYWISE_CUSTOM,
//     value: EAIART_STYLE.PENNYWISE_CUSTOM,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "DarkUno",
//     description:
//       "Playing Uno in a living room setting, with a creepy presence adding a horror twist.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.DARK_UNO,
//     value: EAIART_STYLE.DARK_UNO,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Halloween Party",
//     description:
//       "A lively costume party scene with friends, laughter, and festive vibes.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.HALLOWEEN_PARTY,
//     value: EAIART_STYLE.HALLOWEEN_PARTY,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Freaky Cinema",
//     description:
//       "A horror cinema scene with iconic villains as fellow moviegoers.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.FREAKY_CINEMA,
//     value: EAIART_STYLE.FREAKY_CINEMA,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Summon",
//     description:
//       "Dark ritual scene with glowing symbols, candlelight, and an eerie presence.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.SUMMON,
//     value: EAIART_STYLE.SUMMON,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Reading",
//     description:
//       "Reading newspapers with a creepy figure seated right beside you.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.READING,
//     value: EAIART_STYLE.READING,
//     isEnabled: true,
//     isNew: true,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Paris",
//     description:
//       "Feature yourself with the romantic charm of Paris and the Eiffel Tower.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.PARIS,
//     value: EAIART_STYLE.PARIS,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Autumn",
//     description:
//       "Be immersed in a warm autumn atmosphere with falling leaves and golden tones.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.AUTUMN,
//     value: EAIART_STYLE.AUTUMN,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Poster Design",
//     description: "Bold fashion-poster look with a graphic circle backdrop.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.POSTER_DESIGN,
//     value: EAIART_STYLE.POSTER_DESIGN,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Santorini",
//     description:
//       "Transport yourself to Santorini’s iconic white houses and blue domes.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.SANTORINI,
//     value: EAIART_STYLE.SANTORINI,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Rome",
//     description:
//       "Stand before Rome’s iconic Colosseum in a timeless cityscape.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.ROME,
//     value: EAIART_STYLE.ROME,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Meowchic",
//     description: "Relax in a cozy, stylish scene surrounded by adorable cats.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.MEOWCHIC,
//     value: EAIART_STYLE.MEOWCHIC,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Winter",
//     description: "Snowy wonderland with aurora skies and icy landscapes.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.WINTER,
//     value: EAIART_STYLE.WINTER,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Venice",
//     description: "Immerse yourself in Venice’s canals and gondola charm.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.VENICE,
//     value: EAIART_STYLE.VENICE,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Japan",
//     description: "Cherry blossoms & Mount Fuji in Japan.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.MOUNT_FUJI,
//     value: EAIART_STYLE.MOUNT_FUJI,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Double Portrait",
//     description:
//       "Blend your photo with creative overlays for a surreal double-exposure effect.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.DOUBLE_POTRAIT,
//     value: EAIART_STYLE.DOUBLE_POTRAIT,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Taj Mahal",
//     description:
//       "Stand before the Taj Mahal for a majestic and timeless backdrop.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.TAJ_MAHAL,
//     value: EAIART_STYLE.TAJ_MAHAL,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
//   {
//     id: generateRandomUUIDV4(),
//     title: "Music",
//     description:
//       "Immersive music vibe, placing you inside a digital playlist scene.",
//     type: EAIART_TYPE.IMAGE_TO_IMAGE,
//     image: AI_ART_STYLES_IMAGE.SPOTIFY,
//     value: EAIART_STYLE.SPOTIFY,
//     isEnabled: true,
//     isNew: false,
//     maxImages: 1,
//   },
// ];

export const NANO_BANANA_PRO_STYLE_OPTIONS: TAIArtOptions[] = [
  {
    description: "",
    id: NONE_AI_ART_STYLE_ID,
    image: AI_ART_STYLES_IMAGE.NONE,
    isEnabled: true,
    isNew: false,
    maxImages: 4,
    title: "None",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.NONE,
  },
  {
    description:
      "A full-body miniature of the person displayed inside a clear gashapon capsule, keeping their identity true while completing the full outfit. A fun, collectible-style portrait with a clean, polished look.",
    gifImage: AI_ART_STYLES_IMAGE.GASHAPON_CAPSULE_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.GASHAPON_CAPSULE,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Gashapon Capsule",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.GASHAPON_CAPSULE,
  },
  {
    description:
      "A symmetrical cutaway illustration of your subject with labeled anatomy and concise info, styled like an encyclopedia page on parchment.",
    gifImage: AI_ART_STYLES_IMAGE.ANATOMICAL_INFOTAGRAPH_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ANATOMICAL_INFOTAGRAPH,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Anatomical Infographic",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.ANATOMICAL_INFOTAGRAPH,
  },
  {
    description:
      "An ultra-detailed exploded-view image of your product, showing every internal component floating in precise alignment over a soft gray studio background.",
    gifImage: AI_ART_STYLES_IMAGE.PRODUCT_TECHNICAL_VIEW_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.PRODUCT_TECHNICAL_VIEW,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Product Technical View",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.PRODUCT_TECHNICAL_VIEW,
  },
  {
    description:
      "A polished advertising poster featuring your product in realistic detail, enhanced with a matching slogan and clean, professional layout.",
    gifImage: AI_ART_STYLES_IMAGE.POSTER_CREATION_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.POSTER_CREATION,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Poster Creation",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.POSTER_CREATION,
  },
  {
    description:
      "A clean wooden-background layout showing your dish fully deconstructed into labeled, realistic ingredients with clear names and quantities.",
    gifImage: AI_ART_STYLES_IMAGE.INGREDIENTS_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.INGREDIENTS,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Ingredients",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.INGREDIENTS,
  },
  {
    description:
      "Turn a black-and-white sketch into a fully colored illustration while keeping the original style, details, likeness, and clean professional rendering.",
    gifImage: AI_ART_STYLES_IMAGE.STUDIO_STYLE_PHOTO_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.STUDIO_STYLE_PHOTO,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Photo Coloring",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.STUDIO_STYLE_PHOTO,
  },
  {
    description:
      "Creates a precise architectural floor plan or blueprint by analyzing the building’s exterior and inferring its interior layout using real-world architectural logic.",
    gifImage: AI_ART_STYLES_IMAGE.OBJECT_INFRASTRUCTURE_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.OBJECT_INFRASTRUCTURE,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Object Infrastructure",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.OBJECT_INFRASTRUCTURE,
  },
  {
    description:
      "Replaces the outfit with clothing from the other images while keeping their pose, identity, and the original background.",
    gifImage: AI_ART_STYLES_IMAGE.OUTFIT_SWAP_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.OUTFIT_SWAP,
    isEnabled: true,
    isNew: true,
    maxImages: 4,
    title: "Outfit Swap",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.OUTFIT_SWAP,
  },
  {
    description:
      "Merge the person and pet from the uploaded images into one natural scene, keeping true identity, lighting, and perspective so they look photographed together.",
    gifImage: AI_ART_STYLES_IMAGE.ME_WITH_MY_PET_PRO_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ME_WITH_MY_PET_PRO,
    isEnabled: true,
    isNew: true,
    maxImages: 4,
    title: "Me With My Pet",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.ME_WITH_MY_PET_PRO,
  },
  {
    description:
      "Combines all uploaded elements into one natural, cohesive scene with unified lighting, scale, and color. Produces a seamless, photorealistic composite.",
    gifImage: AI_ART_STYLES_IMAGE.COMBINATION_PHOTO_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.COMBINATION_PHOTO,
    isEnabled: true,
    isNew: true,
    maxImages: 4,
    title: "Combination Photo",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.COMBINATION_PHOTO,
  },
  {
    description:
      "A 3×3 grid of studio portraits showing the same person in nine varied poses with consistent outfit, identity, and clean studio lighting.",
    gifImage: AI_ART_STYLES_IMAGE.LINE_ART_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.LINE_ART,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Line Art",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.LINE_ART,
  },
  {
    description:
      "A 3×3 grid of half-length portraits captured in diverse natural outdoor settings. Identity remains consistent while outfits adjust to match each scene and season.",
    gifImage: AI_ART_STYLES_IMAGE.NINE_HALF_LENGTH_PORTRAITS_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.NINE_HALF_LENGTH_PORTRAITS,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Nine Portraits",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.NINE_HALF_LENGTH_PORTRAITS,
  },
  {
    description:
      "A realistic fashion collage that removes the model and displays each outfit piece separately with true colors, textures, and 3D fabric shape on a corkboard background.",
    gifImage: AI_ART_STYLES_IMAGE.CLOTHING_EXTRACTION_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.CLOTHING_EXTRACTION,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Clothing Extraction",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CLOTHING_EXTRACTION,
  },
  {
    description:
      "Turns the dish into a hyper-realistic knitted wool version while preserving its composition and colors. A detailed yarn sculpture photographed like real food.",
    gifImage: AI_ART_STYLES_IMAGE.KNITTED_WOOL_FOOD_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.KNITTED_WOOL_FOOD,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Knitted Wool Food",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.KNITTED_WOOL_FOOD,
  },
  {
    description:
      "Combine the person with multiple copies of the same pet species in one cohesive outdoor scene, keeping identity and realism intact. photorealistic detail.",
    gifImage: AI_ART_STYLES_IMAGE.PET_SURROUNDING_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.PET_SURROUNDING,
    isEnabled: true,
    isNew: true,
    maxImages: 4,
    title: "Pet Surrounding",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.PET_SURROUNDING,
  },
  {
    description:
      "Complete the unfinished sketch in the same art style with clean, professional linework and proper details.",
    gifImage: AI_ART_STYLES_IMAGE.DRAWING_ASSISTANT_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.DRAWING_ASSISTANT,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Drawing Assistant",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.DRAWING_ASSISTANT,
  },
  {
    description:
      "Creates a 6-frame cinematic storyboard expanding the scene, keeping characters and art style consistent.",
    gifImage: AI_ART_STYLES_IMAGE.STORYBOARD_EXTEND_BORDER_LINE_GIF,
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.STORYBOARD_EXTEND_BORDER_LINE,
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Storyboard",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.STORYBOARD_EXTEND_BORDER_LINE,
  },
];

export const GPT_STYLE_OPTIONS: TAIArtOptions[] = [
  {
    description: "",
    id: NONE_AI_ART_STYLE_ID,
    image: AI_ART_STYLES_IMAGE.NONE,
    isEnabled: true,
    isNew: false,
    maxImages: 4,
    title: "None",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.NONE,
  },
  {
    description: "",
    id: "c2c1f1d7-3e4b-4d89-8e3a-4e1b2a0d9c01",
    image: "https://stg-static.vulcanlabs.co/chatsmith/ai_art/caricature_1.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Caricature 1",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CARICATURE_1,
  },
  {
    description: "",
    id: "a7b6e9d4-1c3a-4f2b-9e8d-5c0a6b1e2f02",
    image: "https://stg-static.vulcanlabs.co/chatsmith/ai_art/caricature_2.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Caricature 2",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CARICATURE_2,
  },
  {
    description: "",
    id: "f3d2c8a9-7b6e-4a1c-9d5f-8e0b2c4a3f03",
    image:
      "https://stg-static.vulcanlabs.co/chatsmith/ai_art/phineas_and_ferb_transform.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Phineas and Ferb transform",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.PHINEAS_AND_FERB_TRANSFORM,
  },
  {
    description: "",
    id: "9a0e4c1f-5d8b-4f7a-8e6c-2b3d1a9f0404",
    image: "https://stg-static.vulcanlabs.co/chatsmith/ai_art/caricature_3.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Caricature 3",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CARICATURE_3,
  },
  {
    description: "",
    id: "1b5c9e0a-8f6d-4e2a-9c7b-3d4f1a2e0505",
    image: "https://stg-static.vulcanlabs.co/chatsmith/ai_art/caricature_4.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Caricature 4",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CARICATURE_4,
  },
  {
    description: "",
    id: "e4f1b0c3-2a6d-4c9e-8f7b-5a1d0e6c0606",
    image:
      "https://stg-static.vulcanlabs.co/chatsmith/ai_art/caricature_couple.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Caricature couple",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CARICATURE_COUPLE,
  },
  {
    description: "",
    id: "7c2d5f9a-4e8b-4a1c-9e6f-0b3d2a1c0707",
    image: "https://stg-static.vulcanlabs.co/chatsmith/ai_art/caricature_5.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Caricature 5",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CARICATURE_5,
  },
  {
    description: "",
    id: "0a9b3d6f-5c2e-4b1a-8f7d-4e1c9a2b0808",
    image: "https://stg-static.vulcanlabs.co/chatsmith/ai_art/caricature_6.jpg",
    isEnabled: true,
    isNew: true,
    maxImages: 1,
    title: "Caricature 6",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.CARICATURE_6,
  },
  {
    description: "Niche appeal, more art-house than mainstream in the U.S",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.GHIBLI,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Studio Ghibli",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.GHIBLI,
  },
  {
    description:
      "A cultural juggernaut with unmatched mainstream appeal and longevity",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.THE_SIMPSONS,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "The Simpsons",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.THE_SIMPSONS,
  },
  {
    description:
      "Strong, consistent fanbase with significant cultural relevance",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.SOUTH_PARK,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "South Park",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.SOUTH_PARK,
  },
  {
    description:
      "The most iconic anime in the U.S., with deep cultural penetration",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.DRAGON_BALL,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Dragon Ball",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.DRAGON_BALL,
  },
  {
    description:
      "Massive search popularity and viewership, slightly behind Dragon Ball",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.NARUTO,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Naruto",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.NARUTO,
  },
  {
    description: "Modern appeal and strong fanbase among younger adults",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.RICK_AND_MORTY,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Rick & Morty",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.RICK_AND_MORTY,
  },
  {
    description:
      "Popular but lags behind Naruto and Dragon Ball due to accessibility issues",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ONE_PIECE,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "One Piece",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.ONE_PIECE,
  },
  {
    description:
      "Nostalgic appeal and niche fanbase, strong in specific regions",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.SAILOR_MOON,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Sailor Moon",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.SAILOR_MOON,
  },
  {
    description:
      "Critically acclaimed with a dedicated fanbase, but smaller than the Big Three",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ATTACK_ON_TITAN,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Attack on Titan",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.ATTACK_ON_TITAN,
  },
  {
    description:
      "Rising star, popular among younger fans, but less established in the U.S",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.DEMON_SLAYER,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Demon Slayer",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.DEMON_SLAYER,
  },
  {
    description:
      "Revived interest with recent arcs, but lower overall impact in the U.S",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.BLEACH,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Bleach",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.BLEACH,
  },
  {
    description: "Limited U.S. popularity, mostly niche or nostalgic",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.DORAEMON,
    isEnabled: true,
    isNew: false,
    maxImages: 1,
    title: "Doraemon",
    type: EAIART_TYPE.IMAGE_TO_IMAGE,
    value: EAIART_STYLE.DORAEMON,
  },
];

// Text to Image Options
export const CHAT_SMITH_STYLE_OPTIONS: TAIArtOptions[] = [
  {
    description: "",
    id: NONE_AI_ART_STYLE_ID,
    image: AI_ART_STYLES_IMAGE.NONE,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "None",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.NONE,
  },
  {
    description: "Hand-painted images with textured brush strokes",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.PAINTING,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Painting",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.PAINTING,
  },
  {
    description: "3D images with depth and perspective",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE._3D,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "3D",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE._3D,
  },
  {
    description: "Lifelike images that look like real photos",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.REALISTIC,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Realistic",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.REALISTIC,
  },
  {
    description: "Fun, simplified images with bold outlines",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.CARTOON,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Cartoon",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.CARTOON,
  },
  {
    description: "Futuristic images with neon lights and dark tech",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.CYBERPUNK,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Cyberpunk",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.CYBERPUNK,
  },
  {
    description: "Modern emulates the look, feel of traditional paintings",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.DIGITAL_ART,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Digital Art",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.DIGITAL_ART,
  },
  {
    description: "Magical images of mythical enchanted worlds",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.FANTASY,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Fantasy",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.FANTASY,
  },
  {
    description: "Colorful images like Japanese cartoons",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ANIME,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Anime",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.ANIME,
  },
  {
    description: "Cute, miniature characters with oversized heads",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.CHIBI,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Chibi",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.CHIBI,
  },
  {
    description: "Soft images like watercolor paintings",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.WATERCOLOR,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Watercolor",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.WATERCOLOR,
  },
  {
    description: "Bold, vibrant retro comic book images",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.POP_ART,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Pop Art",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.POP_ART,
  },
  {
    description: "Rough images like hand-drawn sketches",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.SKETCH,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Sketch",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.SKETCH,
  },
  {
    description: "Dramatic black-and-white images with shadows",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.NOIR,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Noir",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.NOIR,
  },
  {
    description: "Shapes and colors, not realistic images",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.ABSTRACT,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Abstract",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.ABSTRACT,
  },
  {
    description: "Images made of simple geometric shapes",
    id: generateRandomUUIDV4(),
    image: AI_ART_STYLES_IMAGE.LOW_POLY,
    isEnabled: true,
    isNew: false,
    maxImages: 0,
    title: "Low Poly",
    type: EAIART_TYPE.TEXT_TO_IMAGE,
    value: EAIART_STYLE.LOW_POLY,
  },
];
