// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/3 days view.svg

import type { IconProps } from "./types";

export const Icon3DaysView = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M18.51 4.88C19.96 4.88 21.13 6.05 21.13 7.5V16.5C21.13 17.95 19.96 19.13 18.51 19.13H5.51C4.06 19.13 2.88 17.95 2.88 16.5V7.5C2.88 6.05 4.06 4.88 5.51 4.88H18.51ZM5.51 6.13C4.75 6.13 4.13 6.74 4.13 7.5V16.5C4.13 17.26 4.75 17.88 5.51 17.88H8.51V6.13H5.51ZM15.76 17.88H18.51C19.27 17.88 19.88 17.26 19.88 16.5V7.5C19.88 6.74 19.27 6.13 18.51 6.13H15.76V17.88ZM9.76 17.88H14.51V6.13H9.76V17.88Z"
      fill="currentColor"
    />
  </svg>
);
