// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/arrow_up.svg

import type { IconProps } from "./types";

export const IconArrowUp = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.01 5.54C12.05 5.54 12.08 5.55 12.11 5.55C12.12 5.55 12.13 5.55 12.13 5.56C12.16 5.56 12.19 5.57 12.22 5.58C12.23 5.59 12.24 5.59 12.25 5.59C12.28 5.61 12.31 5.62 12.33 5.64C12.34 5.64 12.34 5.65 12.35 5.65C12.38 5.67 12.41 5.7 12.44 5.72L18.27 11.56C18.52 11.8 18.52 12.2 18.27 12.44C18.03 12.69 17.63 12.69 17.39 12.44L12.62 7.68V17.83C12.62 18.18 12.34 18.46 12 18.46C11.65 18.46 11.37 18.18 11.37 17.83V7.68L6.61 12.44C6.36 12.69 5.97 12.69 5.72 12.44C5.48 12.2 5.48 11.8 5.72 11.56L11.56 5.72L11.66 5.64C11.72 5.6 11.79 5.57 11.86 5.56C11.87 5.55 11.88 5.55 11.89 5.55C11.93 5.55 11.96 5.54 11.99 5.54C11.99 5.54 12 5.54 12 5.54C12 5.54 12.01 5.54 12.01 5.54Z"
      fill="currentColor"
    />
  </svg>
);
