// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/arrow-left-to-line.svg

import type { IconProps } from "./types";

export const IconArrowLeftToLine = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M3.58 4.83C3.93 4.83 4.21 5.11 4.21 5.45V18.55C4.21 18.89 3.93 19.17 3.58 19.17C3.24 19.17 2.96 18.89 2.96 18.55V5.45C2.96 5.11 3.24 4.83 3.58 4.83ZM12.49 5.95C12.74 5.7 13.13 5.7 13.38 5.95C13.62 6.19 13.62 6.59 13.38 6.83L8.83 11.37H20.42C20.76 11.37 21.04 11.65 21.04 12C21.04 12.34 20.76 12.62 20.42 12.62H8.83L13.38 17.17C13.62 17.41 13.62 17.81 13.38 18.05C13.13 18.3 12.74 18.3 12.49 18.05L6.89 12.45C6.86 12.42 6.83 12.38 6.8 12.35C6.79 12.33 6.79 12.32 6.78 12.3C6.77 12.28 6.76 12.26 6.75 12.24C6.68 12.08 6.68 11.91 6.75 11.76C6.76 11.74 6.77 11.72 6.78 11.69C6.79 11.68 6.79 11.67 6.8 11.66L6.81 11.65C6.83 11.62 6.85 11.59 6.88 11.56L12.49 5.95Z"
      fill="currentColor"
    />
  </svg>
);
