// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/calendar-blank.svg

import type { IconProps } from "./types";

export const IconCalendarBlank = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.02 1.39C16.36 1.39 16.64 1.67 16.64 2.02V3.39H19.02C20.47 3.39 21.64 4.57 21.64 6.02V20.02C21.64 21.47 20.47 22.64 19.02 22.64H5.02C3.57 22.64 2.39 21.47 2.39 20.02V6.02C2.39 4.57 3.57 3.39 5.02 3.39H7.39V2.02C7.39 1.67 7.67 1.39 8.02 1.39C8.36 1.39 8.64 1.67 8.64 2.02V3.39H15.39V2.02C15.39 1.67 15.67 1.39 16.02 1.39ZM3.64 10.64V20.02C3.64 20.77 4.26 21.39 5.02 21.39H19.02C19.77 21.39 20.39 20.77 20.39 20.02V10.64H3.64ZM5.02 4.64C4.26 4.64 3.64 5.26 3.64 6.02V9.39H20.39V6.02C20.39 5.26 19.77 4.64 19.02 4.64H16.64V6.02C16.64 6.36 16.36 6.64 16.02 6.64C15.67 6.64 15.39 6.36 15.39 6.02V4.64H8.64V6.02C8.64 6.36 8.36 6.64 8.02 6.64C7.67 6.64 7.39 6.36 7.39 6.02V4.64H5.02Z"
      fill="currentColor"
    />
  </svg>
);
