// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/chat.svg

import type { IconProps } from "./types";

export const IconChat = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.37 4.71C14.32 4.79 16.18 5.49 17.61 6.71C19.03 7.92 19.93 9.57 20.1 11.35C20.27 13.13 19.71 14.9 18.54 16.33C17.37 17.75 15.66 18.73 13.76 19.11C11.93 19.47 10.01 19.26 8.34 18.5L4.62 19.29C4.41 19.33 4.18 19.26 4.03 19.09C3.88 18.92 3.83 18.69 3.9 18.48L4.89 15.51C3.99 14.05 3.68 12.35 4.01 10.69C4.37 8.93 5.43 7.36 6.97 6.27C8.5 5.18 10.43 4.63 12.37 4.71ZM12.32 5.96C10.64 5.89 8.99 6.37 7.69 7.29C6.39 8.21 5.53 9.51 5.24 10.93C4.95 12.35 5.25 13.82 6.1 15.08C6.2 15.24 6.23 15.44 6.17 15.62L5.43 17.84L8.28 17.23L8.38 17.22C8.49 17.21 8.59 17.23 8.68 17.28C10.15 17.99 11.87 18.21 13.52 17.89C15.16 17.56 16.6 16.72 17.57 15.53C18.55 14.35 19 12.91 18.86 11.47C18.72 10.04 17.99 8.68 16.79 7.66C15.59 6.63 14.01 6.02 12.32 5.96Z"
      fill="currentColor"
    />
  </svg>
);
