// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/check.svg

import type { IconProps } from "./types";

export const IconCheck = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M18.52 7.18C18.76 6.94 19.16 6.94 19.4 7.18C19.64 7.43 19.64 7.82 19.4 8.07L10.23 17.23C10.12 17.35 9.96 17.42 9.79 17.42C9.63 17.42 9.47 17.35 9.35 17.23L5.18 13.07C4.94 12.82 4.94 12.43 5.18 12.18C5.43 11.94 5.82 11.94 6.07 12.18L9.79 15.91L18.52 7.18Z"
      fill="currentColor"
    />
  </svg>
);
