// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/chervon_down_up.svg

import type { IconProps } from "./types";

export const IconChervonDownUp = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M11.62 13.44C11.86 13.28 12.19 13.3 12.4 13.52L15.73 16.85C15.98 17.09 15.98 17.49 15.73 17.73C15.49 17.98 15.09 17.98 14.85 17.73L11.96 14.84L9.07 17.73C8.82 17.98 8.43 17.98 8.18 17.73C7.94 17.49 7.94 17.09 8.18 16.85L11.52 13.52L11.62 13.44ZM14.85 6.18C15.09 5.94 15.49 5.94 15.73 6.18C15.98 6.43 15.98 6.82 15.73 7.07L12.4 10.4C12.16 10.64 11.76 10.64 11.52 10.4L8.18 7.07C7.94 6.82 7.94 6.43 8.18 6.18C8.43 5.94 8.82 5.94 9.07 6.18L11.96 9.07L14.85 6.18Z"
      fill="currentColor"
    />
  </svg>
);
