// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/chevron_down.svg

import type { IconProps } from "./types";

export const IconChevronDown = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16.56 9.56C16.8 9.31 17.2 9.31 17.44 9.56C17.69 9.8 17.69 10.2 17.44 10.44L12.44 15.44C12.2 15.69 11.8 15.69 11.56 15.44L6.56 10.44C6.31 10.2 6.31 9.8 6.56 9.56C6.8 9.31 7.2 9.31 7.44 9.56L12 14.12L16.56 9.56Z"
      fill="currentColor"
    />
  </svg>
);
