// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/chevron_right.svg

import type { IconProps } from "./types";

export const IconChevronRight = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M9.94 17.44C9.7 17.69 9.3 17.69 9.06 17.44C8.81 17.2 8.81 16.8 9.06 16.56L13.61 12L9.06 7.44C8.81 7.2 8.81 6.8 9.06 6.56C9.3 6.31 9.7 6.31 9.94 6.56L14.94 11.56C15.19 11.8 15.19 12.2 14.94 12.44L9.94 17.44Z"
      fill="currentColor"
    />
  </svg>
);
