// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/circle-uncheck.svg

import type { IconProps } from "./types";

export const IconCircleUncheck = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 4C16.42 4 20 7.58 20 12C20 16.42 16.42 20 12 20C7.58 20 4 16.42 4 12C4 7.58 7.58 4 12 4ZM12 5.25C8.27 5.25 5.25 8.27 5.25 12C5.25 15.73 8.27 18.75 12 18.75C15.73 18.75 18.75 15.73 18.75 12C18.75 8.27 15.73 5.25 12 5.25Z"
      fill="currentColor"
    />
  </svg>
);
