// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/circle-ellipsis.svg

import type { IconProps } from "./types";

export const IconCircleEllipsis = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.15 4C16.66 4 20.31 7.65 20.31 12.15C20.31 16.66 16.66 20.31 12.15 20.31C7.65 20.31 4 16.66 4 12.15C4 7.65 7.65 4 12.15 4ZM12.15 5.25C8.34 5.25 5.25 8.34 5.25 12.15C5.25 15.97 8.34 19.06 12.15 19.06C15.97 19.06 19.06 15.97 19.06 12.15C19.06 8.34 15.97 5.25 12.15 5.25ZM8.4 11.53C8.74 11.53 9.02 11.81 9.02 12.15C9.02 12.5 8.74 12.78 8.4 12.78H8.39C8.04 12.78 7.76 12.5 7.76 12.15C7.76 11.81 8.04 11.53 8.39 11.53H8.4ZM12.16 11.53C12.51 11.53 12.79 11.81 12.79 12.15C12.79 12.5 12.51 12.78 12.16 12.78H12.15C11.81 12.78 11.53 12.5 11.53 12.15C11.53 11.81 11.81 11.53 12.15 11.53H12.16ZM15.93 11.53C16.27 11.53 16.55 11.81 16.55 12.15C16.55 12.5 16.27 12.78 15.93 12.78H15.92C15.57 12.78 15.29 12.5 15.29 12.15C15.29 11.81 15.57 11.53 15.92 11.53H15.93Z"
      fill="currentColor"
    />
  </svg>
);
