// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/circle x.svg

import type { IconProps } from "./types";

export const IconCircleX = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 4C16.42 4 20 7.58 20 12C20 16.42 16.42 20 12 20C7.58 20 4 16.42 4 12C4 7.58 7.58 4 12 4ZM12 5.25C8.27 5.25 5.25 8.27 5.25 12C5.25 15.73 8.27 18.75 12 18.75C15.73 18.75 18.75 15.73 18.75 12C18.75 8.27 15.73 5.25 12 5.25ZM13.62 9.18C13.87 8.94 14.26 8.94 14.51 9.18C14.75 9.43 14.75 9.82 14.51 10.07L12.73 11.84L14.51 13.62C14.75 13.87 14.75 14.26 14.51 14.51C14.26 14.75 13.87 14.75 13.62 14.51L11.84 12.73L10.07 14.51C9.82 14.75 9.43 14.75 9.18 14.51C8.94 14.26 8.94 13.87 9.18 13.62L10.96 11.84L9.18 10.07C8.94 9.82 8.94 9.43 9.18 9.18C9.43 8.94 9.82 8.94 10.07 9.18L11.84 10.96L13.62 9.18Z"
      fill="currentColor"
    />
  </svg>
);
