// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/circle_chevron_left.svg

import type { IconProps } from "./types";

export const IconCircleChevronLeft = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.13 3.38C16.96 3.38 20.88 7.29 20.88 12.13C20.88 16.96 16.96 20.88 12.13 20.88C7.29 20.88 3.38 16.96 3.38 12.13C3.38 7.29 7.29 3.38 12.13 3.38ZM12.13 4.63C7.98 4.63 4.63 7.98 4.63 12.13C4.63 16.27 7.98 19.63 12.13 19.63C16.27 19.63 19.63 16.27 19.63 12.13C19.63 7.98 16.27 4.63 12.13 4.63ZM12.56 8.56C12.8 8.31 13.2 8.31 13.44 8.56C13.69 8.8 13.69 9.2 13.44 9.44L10.88 12L13.44 14.56C13.69 14.8 13.69 15.2 13.44 15.44C13.2 15.69 12.8 15.69 12.56 15.44L9.56 12.44C9.31 12.2 9.31 11.8 9.56 11.56L12.56 8.56Z"
      fill="currentColor"
    />
  </svg>
);
