// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/corner-down-right.svg

import type { IconProps } from "./types";

export const IconCornerDownRight = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M4.63 4C4.97 4 5.25 4.28 5.25 4.63V11.12C5.25 11.94 5.57 12.72 6.15 13.3C6.73 13.88 7.52 14.2 8.33 14.2H17.96L14.38 10.63C14.14 10.39 14.14 9.99 14.38 9.75C14.63 9.5 15.03 9.5 15.27 9.75L19.91 14.38C19.99 14.47 20.04 14.57 20.07 14.67C20.07 14.68 20.07 14.69 20.08 14.71C20.09 14.75 20.09 14.79 20.09 14.83V14.83C20.09 14.89 20.08 14.95 20.06 15.01C20.05 15.03 20.05 15.05 20.04 15.07C20.03 15.09 20.02 15.1 20.01 15.12C20 15.14 19.99 15.16 19.98 15.17C19.96 15.21 19.93 15.24 19.9 15.27L15.27 19.91C15.03 20.15 14.63 20.15 14.38 19.91C14.14 19.66 14.14 19.27 14.38 19.02L17.95 15.45H8.33C7.19 15.45 6.08 15 5.27 14.18C4.46 13.37 4 12.27 4 11.12V4.63C4 4.28 4.28 4 4.63 4Z"
      fill="currentColor"
    />
  </svg>
);
