// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/corner-up-left.svg

import type { IconProps } from "./types";

export const IconCornerUpLeft = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M19.46 20.09C19.12 20.09 18.84 19.81 18.84 19.46L18.84 12.97C18.84 12.15 18.51 11.37 17.94 10.79C17.36 10.21 16.57 9.89 15.75 9.89L6.13 9.89L9.71 13.46C9.95 13.7 9.95 14.1 9.71 14.34C9.46 14.59 9.06 14.59 8.82 14.34L4.18 9.7C4.1 9.62 4.05 9.52 4.02 9.42C4.02 9.41 4.02 9.4 4.01 9.38C4 9.34 4 9.3 4 9.26L4 9.26C4 9.2 4.01 9.14 4.03 9.08C4.04 9.06 4.04 9.04 4.05 9.02C4.06 9 4.07 8.99 4.08 8.97C4.09 8.95 4.1 8.93 4.11 8.92C4.13 8.88 4.16 8.85 4.19 8.82L8.82 4.18C9.06 3.94 9.46 3.94 9.71 4.18C9.95 4.43 9.95 4.82 9.71 5.07L6.14 8.64L15.75 8.64C16.9 8.64 18.01 9.09 18.82 9.91C19.63 10.72 20.09 11.82 20.09 12.97L20.09 19.46C20.09 19.81 19.81 20.09 19.46 20.09Z"
      fill="currentColor"
    />
  </svg>
);
