// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/crosshair.svg

import type { IconProps } from "./types";

export const IconCrosshair = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.42 3.86C16.73 4.07 20.16 7.64 20.16 12C20.16 16.5 16.5 20.16 12 20.16C7.5 20.16 3.84 16.5 3.84 12C3.84 7.5 7.5 3.84 12 3.84L12.42 3.86ZM12.63 7.48C12.63 7.83 12.35 8.11 12 8.11C11.65 8.11 11.38 7.83 11.38 7.48V5.12C8.06 5.42 5.42 8.06 5.12 11.38H7.48C7.83 11.38 8.11 11.65 8.11 12C8.11 12.35 7.83 12.63 7.48 12.63H5.12C5.42 15.94 8.06 18.58 11.38 18.88V16.52C11.38 16.17 11.65 15.89 12 15.89C12.35 15.89 12.63 16.17 12.63 16.52V18.88C15.94 18.58 18.58 15.94 18.88 12.63H16.52C16.17 12.63 15.89 12.35 15.89 12C15.89 11.65 16.17 11.38 16.52 11.38H18.88C18.58 8.06 15.94 5.42 12.63 5.12V7.48Z"
      fill="currentColor"
    />
  </svg>
);
