// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/folder.svg

import type { IconProps } from "./types";

export const IconFolder = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M9.04 5.38C9.84 5.38 10.59 5.74 11.09 6.36L11.89 7.36C12.15 7.69 12.54 7.87 12.96 7.88H16.75C18.2 7.88 19.38 9.05 19.38 10.5V16C19.38 17.45 18.2 18.63 16.75 18.63H7.25C5.8 18.63 4.63 17.45 4.63 16V8C4.63 6.55 5.8 5.38 7.25 5.38H9.04ZM7.25 6.63C6.49 6.63 5.88 7.24 5.88 8V16C5.88 16.76 6.49 17.38 7.25 17.38H16.75C17.51 17.38 18.13 16.76 18.13 16V10.5C18.13 9.74 17.51 9.13 16.75 9.13H12.96C12.16 9.12 11.41 8.76 10.91 8.14L10.11 7.14C9.85 6.81 9.46 6.63 9.04 6.63H7.25Z"
      fill="currentColor"
    />
  </svg>
);
