// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/home.svg

import type { IconProps } from "./types";

export const IconHome = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M10.47 5.15C11.37 4.45 12.63 4.45 13.53 5.15L18.41 8.95C19.02 9.42 19.37 10.15 19.38 10.92V16.88C19.38 18.26 18.26 19.38 16.88 19.38H7.12C5.74 19.38 4.63 18.26 4.63 16.88V10.92C4.63 10.15 4.98 9.42 5.59 8.95L10.47 5.15ZM12.76 6.14C12.32 5.79 11.68 5.79 11.24 6.14L6.36 9.93C6.05 10.17 5.88 10.53 5.88 10.92V16.88C5.88 17.57 6.43 18.13 7.12 18.13H16.88C17.57 18.13 18.13 17.57 18.13 16.88V10.92C18.12 10.53 17.95 10.17 17.64 9.93L12.76 6.14ZM14.25 15.13C14.6 15.13 14.87 15.41 14.88 15.75C14.88 16.1 14.6 16.38 14.25 16.38H9.75C9.4 16.38 9.13 16.1 9.13 15.75C9.13 15.41 9.4 15.13 9.75 15.13H14.25Z"
      fill="currentColor"
    />
  </svg>
);
