// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/image.svg

import type { IconProps } from "./types";

export const IconImage = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.75 4.63C18.2 4.63 19.38 5.8 19.38 7.25V16.75C19.38 18.2 18.2 19.38 16.75 19.38H7.25C5.8 19.38 4.63 18.2 4.63 16.75V7.25C4.63 5.8 5.8 4.63 7.25 4.63H16.75ZM15.27 12.4C15.12 12.25 14.88 12.25 14.73 12.4L12.23 14.9C11.93 15.2 11.52 15.38 11.09 15.38H5.88V16.75C5.88 17.51 6.49 18.13 7.25 18.13H16.75C17.51 18.13 18.13 17.51 18.13 16.75V15.26L15.27 12.4ZM7.25 5.88C6.49 5.88 5.88 6.49 5.88 7.25V14.13H11.09C11.19 14.13 11.28 14.09 11.35 14.02L13.85 11.52C14.49 10.88 15.51 10.88 16.15 11.52L18.13 13.49V7.25C18.13 6.49 17.51 5.88 16.75 5.88H7.25ZM9.5 8.5C10.05 8.5 10.5 8.95 10.5 9.5C10.5 10.05 10.05 10.5 9.5 10.5C8.95 10.5 8.5 10.05 8.5 9.5C8.5 8.95 8.95 8.5 9.5 8.5Z"
      fill="currentColor"
    />
  </svg>
);
