// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/mail.svg

import type { IconProps } from "./types";

export const IconMail = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M18.52 4.9C19.79 4.9 20.81 5.92 20.81 7.19V17.19C20.81 18.45 19.79 19.48 18.52 19.48H5.19C3.92 19.48 2.9 18.45 2.9 17.19V7.19C2.9 5.92 3.92 4.9 5.19 4.9H18.52ZM13.03 13.32C13.02 13.32 13.02 13.33 13.01 13.33C12.66 13.54 12.26 13.64 11.86 13.64C11.45 13.64 11.06 13.54 10.71 13.33C10.7 13.33 10.69 13.32 10.68 13.32L4.15 9.16V17.19C4.15 17.76 4.61 18.23 5.19 18.23H18.52C19.1 18.23 19.56 17.76 19.56 17.19V9.16L13.03 13.32ZM5.19 6.15C4.61 6.15 4.15 6.61 4.15 7.19V7.68L11.34 12.26C11.5 12.35 11.68 12.39 11.86 12.39C12.04 12.39 12.22 12.35 12.37 12.26L19.56 7.68V7.19C19.56 6.61 19.1 6.15 18.52 6.15H5.19Z"
      fill="currentColor"
    />
  </svg>
);
