// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/minus.svg

import type { IconProps } from "./types";

export const IconMinus = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 4C16.42 4 20 7.58 20 12C20 16.42 16.42 20 12 20C7.58 20 4 16.42 4 12C4 7.58 7.58 4 12 4ZM7 11V13H17V11H7Z"
      fill="currentColor"
    />
  </svg>
);
