// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/pen.svg

import type { IconProps } from "./types";

export const IconPen = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M18 18.29C18.35 18.29 18.63 18.57 18.63 18.92C18.63 19.26 18.35 19.54 18 19.54H6C5.65 19.54 5.38 19.26 5.38 18.92C5.38 18.57 5.65 18.29 6 18.29H18ZM13.45 4.66C13.85 4.38 14.38 4.39 14.77 4.68L14.85 4.75L17.03 6.73C17.51 7.17 17.52 7.91 17.06 8.37L9.91 15.36C9.79 15.48 9.64 15.54 9.47 15.54H6C5.65 15.54 5.38 15.26 5.38 14.92V11.76C5.38 11.58 5.46 11.4 5.6 11.28L13.37 4.72L13.45 4.66ZM6.63 12.05V14.29H9.22L16.09 7.56L14.09 5.75L6.63 12.05Z"
      fill="currentColor"
    />
  </svg>
);
