// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/phone.svg

import type { IconProps } from "./types";

export const IconPhone = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M15.83 3.71C17.02 3.71 17.99 4.68 17.99 5.87V18.13C17.99 19.32 17.02 20.29 15.83 20.29H8.17C6.98 20.29 6.01 19.32 6.01 18.13V5.87C6.01 4.68 6.98 3.71 8.17 3.71H15.83ZM8.17 4.96C7.67 4.96 7.26 5.37 7.26 5.87V18.13C7.26 18.63 7.67 19.04 8.17 19.04H15.83C16.33 19.04 16.74 18.63 16.74 18.13V5.87C16.74 5.37 16.33 4.96 15.83 4.96H8.17ZM12.01 15.97C12.35 15.97 12.63 16.25 12.63 16.6C12.63 16.94 12.35 17.22 12.01 17.22H12C11.66 17.22 11.38 16.94 11.38 16.6C11.38 16.25 11.66 15.97 12 15.97H12.01Z"
      fill="currentColor"
    />
  </svg>
);
