// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/plus.svg

import type { IconProps } from "./types";

export const IconPlus = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 5.54C12.34 5.54 12.62 5.82 12.62 6.17V11.37H17.83C18.18 11.37 18.46 11.65 18.46 12C18.46 12.34 18.18 12.62 17.83 12.62H12.62V17.83C12.62 18.18 12.34 18.46 12 18.46C11.65 18.46 11.37 18.18 11.37 17.83V12.62H6.17C5.82 12.62 5.54 12.34 5.54 12C5.54 11.65 5.82 11.37 6.17 11.37H11.37V6.17C11.37 5.82 11.65 5.54 12 5.54Z"
      fill="currentColor"
    />
  </svg>
);
