// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/presentation.svg

import type { IconProps } from "./types";

export const IconPresentation = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M22.39 2C22.73 2 23.01 2.28 23.01 2.63C23.01 2.97 22.73 3.25 22.39 3.25H21.97V14.04C21.97 14.76 21.69 15.45 21.18 15.95C20.68 16.46 19.99 16.75 19.27 16.75H13.52L17.64 20.87C17.88 21.11 17.88 21.51 17.64 21.75C17.39 22 17 22 16.75 21.75L12.01 17L7.26 21.75C7.01 22 6.62 22 6.37 21.75C6.13 21.51 6.13 21.11 6.37 20.87L10.5 16.75H4.74C4.02 16.75 3.34 16.46 2.83 15.95C2.32 15.45 2.04 14.76 2.04 14.04V3.25H1.63C1.28 3.25 1 2.97 1 2.63C1 2.28 1.28 2 1.63 2H22.39ZM3.29 14.04C3.29 14.43 3.44 14.8 3.71 15.07C3.99 15.34 4.35 15.5 4.74 15.5H19.27C19.66 15.5 20.03 15.34 20.3 15.07C20.57 14.8 20.72 14.43 20.72 14.04V3.25H3.29V14.04Z"
      fill="currentColor"
    />
  </svg>
);
