// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/setting.svg

import type { IconProps } from "./types";

export const IconSetting = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.17 13.04C17.89 13.04 19.29 14.44 19.29 16.17C19.29 17.89 17.89 19.29 16.17 19.29C14.66 19.29 13.39 18.22 13.1 16.79H6.17C5.82 16.79 5.54 16.51 5.54 16.17C5.54 15.82 5.82 15.54 6.17 15.54H13.1C13.39 14.12 14.66 13.04 16.17 13.04ZM16.17 14.29C15.13 14.29 14.29 15.13 14.29 16.17C14.29 17.2 15.13 18.04 16.17 18.04C17.2 18.04 18.04 17.2 18.04 16.17C18.04 15.13 17.2 14.29 16.17 14.29ZM7.83 4.71C9.34 4.71 10.61 5.78 10.9 7.21H17.83C18.18 7.21 18.46 7.49 18.46 7.83C18.46 8.18 18.18 8.46 17.83 8.46H10.9C10.61 9.88 9.34 10.96 7.83 10.96C6.11 10.96 4.71 9.56 4.71 7.83C4.71 6.11 6.11 4.71 7.83 4.71ZM7.83 5.96C6.8 5.96 5.96 6.8 5.96 7.83C5.96 8.87 6.8 9.71 7.83 9.71C8.87 9.71 9.71 8.87 9.71 7.83C9.71 6.8 8.87 5.96 7.83 5.96Z"
      fill="currentColor"
    />
  </svg>
);
