// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/square-activity.svg

import type { IconProps } from "./types";

export const IconSquareActivity = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M18.63 2C20.07 2 21.25 3.18 21.25 4.63V18.63C21.25 20.07 20.07 21.25 18.63 21.25H4.63C3.18 21.25 2 20.07 2 18.63V4.63C2 3.18 3.18 2 4.63 2H18.63ZM4.63 3.25C3.87 3.25 3.25 3.87 3.25 4.63V18.63C3.25 19.38 3.87 20 4.63 20H18.63C19.38 20 20 19.38 20 18.63V4.63C20 3.87 19.38 3.25 18.63 3.25H4.63ZM10.68 6C10.96 6.03 11.18 6.23 11.24 6.5L12.83 14.44L14.04 11.39L14.09 11.31C14.2 11.12 14.4 11 14.63 11H16.63C16.97 11 17.25 11.28 17.25 11.63C17.25 11.97 16.97 12.25 16.63 12.25H15.05L13.21 16.86C13.1 17.11 12.84 17.27 12.57 17.25C12.29 17.22 12.07 17.02 12.01 16.75L10.42 8.81L9.21 11.86C9.11 12.09 8.88 12.25 8.63 12.25H6.63C6.28 12.25 6 11.97 6 11.63C6 11.28 6.28 11 6.63 11H8.2L10.04 6.39L10.09 6.3C10.21 6.1 10.44 5.98 10.68 6Z"
      fill="currentColor"
    />
  </svg>
);
