// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/square.svg

import type { IconProps } from "./types";

export const IconSquare = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.67 5.38C17.75 5.38 18.63 6.25 18.63 7.33V16.67C18.63 17.75 17.75 18.62 16.67 18.63H7.33C6.25 18.62 5.38 17.75 5.38 16.67V7.33C5.38 6.25 6.25 5.38 7.33 5.38H16.67Z"
      fill="currentColor"
    />
  </svg>
);
