// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/upload.svg

import type { IconProps } from "./types";

export const IconUpload = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M18.29 19C18.64 19 18.92 19.28 18.92 19.62C18.92 19.97 18.64 20.25 18.29 20.25H6.63C6.28 20.25 6 19.97 6 19.62C6 19.28 6.28 19 6.63 19H18.29ZM12.22 4.05C12.37 3.98 12.54 3.98 12.7 4.05C12.71 4.05 12.73 4.06 12.75 4.07C12.8 4.1 12.85 4.14 12.9 4.18L17.9 9.18C18.14 9.43 18.14 9.82 17.9 10.07C17.66 10.31 17.26 10.31 17.02 10.07L13.08 6.13V16.29C13.08 16.64 12.8 16.92 12.46 16.92C12.11 16.92 11.83 16.64 11.83 16.29V6.13L7.9 10.07C7.66 10.31 7.26 10.31 7.02 10.07C6.77 9.82 6.77 9.43 7.02 9.18L12.02 4.18C12.06 4.14 12.11 4.1 12.17 4.07C12.18 4.06 12.2 4.05 12.22 4.05Z"
      fill="currentColor"
    />
  </svg>
);
