// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/user.svg

import type { IconProps } from "./types";

export const IconUser = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 3.88C14.65 3.88 16.79 6.02 16.79 8.67C16.79 10.35 15.92 11.84 14.6 12.69C15.55 13.05 16.42 13.61 17.16 14.34C18.52 15.71 19.29 17.57 19.29 19.5C19.29 19.84 19.01 20.13 18.67 20.13C18.32 20.12 18.04 19.84 18.04 19.5C18.04 17.9 17.41 16.36 16.27 15.23C15.14 14.09 13.6 13.46 12 13.46C10.4 13.46 8.86 14.09 7.73 15.23C6.6 16.36 5.96 17.9 5.96 19.5C5.96 19.84 5.68 20.13 5.33 20.13C4.99 20.12 4.71 19.84 4.71 19.5C4.71 17.57 5.48 15.71 6.84 14.34C7.58 13.61 8.45 13.05 9.4 12.69C8.08 11.84 7.21 10.35 7.21 8.67C7.21 6.02 9.35 3.88 12 3.88ZM12 5.13C10.05 5.13 8.46 6.71 8.46 8.67C8.46 10.62 10.05 12.21 12 12.21C13.96 12.21 15.54 10.62 15.54 8.67C15.54 6.71 13.96 5.13 12 5.13Z"
      fill="currentColor"
    />
  </svg>
);
