// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: svgs/user-fill.svg

import type { IconProps } from "./types";

export const IconUserFill = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 3.88C14.65 3.88 16.79 6.02 16.79 8.67C16.79 10.35 15.92 11.84 14.6 12.69C15.55 13.05 16.42 13.61 17.16 14.34C18.52 15.71 19.29 17.57 19.29 19.5C19.29 19.67 19.23 19.82 19.11 19.94C18.99 20.06 18.83 20.13 18.67 20.13H5.33C5.17 20.13 5.01 20.06 4.89 19.94C4.77 19.82 4.71 19.67 4.71 19.5C4.71 17.57 5.48 15.71 6.84 14.34C7.58 13.61 8.45 13.05 9.4 12.69C8.08 11.84 7.21 10.35 7.21 8.67C7.21 6.02 9.35 3.88 12 3.88Z"
      fill="currentColor"
    />
  </svg>
);
