// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/survey/meaning-63.svg

import type { IconProps } from "../../types";

export const IconActivity = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M19 2.38C20.45 2.38 21.63 3.55 21.63 5V19C21.63 20.45 20.45 21.63 19 21.63H5C3.55 21.63 2.38 20.45 2.38 19V5C2.38 3.55 3.55 2.38 5 2.38H19ZM5 3.63C4.24 3.63 3.63 4.24 3.63 5V19C3.63 19.76 4.24 20.38 5 20.38H19C19.76 20.38 20.38 19.76 20.38 19V5C20.38 4.24 19.76 3.63 19 3.63H5ZM11.06 6.38C11.33 6.4 11.56 6.61 11.61 6.88L13.2 14.81L14.42 11.77L14.46 11.68C14.57 11.49 14.78 11.38 15 11.38H17C17.35 11.38 17.63 11.65 17.63 12C17.63 12.35 17.35 12.63 17 12.63H15.42L13.58 17.23C13.48 17.49 13.22 17.65 12.94 17.62C12.67 17.6 12.44 17.39 12.39 17.12L10.8 9.18L9.58 12.23C9.49 12.47 9.26 12.63 9 12.63H7C6.65 12.63 6.38 12.35 6.38 12C6.38 11.65 6.65 11.38 7 11.38H8.58L10.42 6.77L10.46 6.68C10.59 6.47 10.82 6.36 11.06 6.38Z"
      fill="currentColor"
    />
  </svg>
);
