// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/brand/meaning-18.svg

import type { IconProps } from "../../types";

export const IconAiMark = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M11.98 2C11.66 7.36 7.36 11.66 2 11.98V12.02C7.36 12.34 11.66 16.64 11.98 22H12.02C12.34 16.64 16.64 12.34 22 12.02V11.98C16.64 11.66 12.34 7.36 12.02 2H11.98Z"
      fill="currentColor"
    />
  </svg>
);
