// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/social-media/meaning-119.svg

import type { IconProps } from "../../types";

export const IconApple = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16.11 5.15C17.62 5.15 19.22 5.97 20.35 7.38C16.62 9.42 17.23 14.72 21 16.14C20.48 17.28 20.23 17.8 19.56 18.81C18.63 20.22 17.32 21.98 15.69 22C14.24 22.01 13.87 21.06 11.9 21.07C9.94 21.08 9.53 22.01 8.08 22C6.45 21.98 5.2 20.4 4.27 18.98C1.66 15.03 1.39 10.39 3 7.93C4.14 6.18 5.95 5.15 7.64 5.15C9.37 5.15 10.45 6.09 11.88 6.09C13.27 6.09 14.11 5.15 16.11 5.15ZM15.67 0C15.87 1.34 15.32 2.65 14.59 3.57C13.82 4.56 12.48 5.33 11.18 5.29C10.95 4.01 11.55 2.7 12.29 1.81C13.1 0.83 14.48 0.08 15.67 0Z"
      fill="currentColor"
    />
  </svg>
);
