// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-110.svg

import type { IconProps } from "../../types";

export const IconArrowRightToLine = ({
  size = 24,
  className,
  ...props
}: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    className={className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M20.42 19.34C20.07 19.34 19.79 19.06 19.79 18.72L19.79 5.63C19.79 5.28 20.07 5 20.42 5C20.76 5 21.04 5.28 21.04 5.63L21.04 18.72C21.04 19.06 20.76 19.34 20.42 19.34ZM11.51 18.23C11.26 18.47 10.87 18.47 10.62 18.23C10.38 17.98 10.38 17.58 10.62 17.34L15.17 12.8L3.58 12.8C3.24 12.8 2.96 12.52 2.96 12.17C2.96 11.83 3.24 11.55 3.58 11.55L15.17 11.55L10.62 7C10.38 6.76 10.38 6.36 10.62 6.12C10.87 5.88 11.26 5.88 11.51 6.12L17.11 11.73C17.14 11.76 17.17 11.79 17.2 11.83C17.21 11.84 17.21 11.85 17.22 11.87C17.23 11.89 17.24 11.91 17.25 11.93C17.32 12.09 17.32 12.26 17.25 12.41C17.24 12.43 17.23 12.45 17.22 12.48C17.21 12.49 17.21 12.5 17.2 12.52L17.19 12.52C17.17 12.55 17.15 12.59 17.12 12.61L11.51 18.23Z"
      fill="currentColor"
    />
  </svg>
);
