// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/create-event/meaning-26.svg

import type { IconProps } from "../../types";

export const IconArrowRightAlt = ({
  size = 24,
  className,
  ...props
}: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    className={className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11.18 4.18C11.43 3.94 11.82 3.94 12.07 4.18L19.07 11.18C19.31 11.43 19.31 11.82 19.07 12.07L12.07 19.07C11.82 19.31 11.43 19.31 11.18 19.07C10.94 18.82 10.94 18.43 11.18 18.18L17.12 12.25H4.63C4.28 12.25 4 11.97 4 11.63C4 11.28 4.28 11 4.63 11H17.12L11.18 5.07C10.94 4.82 10.94 4.43 11.18 4.18Z"
      fill="currentColor"
    />
  </svg>
);
