// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/shape/general/blend.svg

import type { IconProps } from "../../types";

export const IconBlend = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M9.35 2.9C12.47 2.9 15.07 5.1 15.68 8.03C18.61 8.64 20.81 11.24 20.81 14.35C20.81 17.92 17.92 20.81 14.35 20.81C11.24 20.81 8.64 18.61 8.03 15.68C5.1 15.07 2.9 12.47 2.9 9.35C2.9 5.79 5.79 2.9 9.35 2.9ZM15.81 9.35C15.81 12.92 12.92 15.81 9.35 15.81C9.98 17.98 11.98 19.56 14.35 19.56C17.23 19.56 19.56 17.23 19.56 14.35C19.56 11.98 17.98 9.98 15.81 9.35ZM14.35 9.15C11.48 9.15 9.15 11.48 9.15 14.35C9.15 14.42 9.15 14.49 9.15 14.56C9.22 14.56 9.29 14.56 9.35 14.56C12.23 14.56 14.56 12.23 14.56 9.35C14.56 9.29 14.56 9.22 14.56 9.15C14.49 9.15 14.42 9.15 14.35 9.15ZM9.35 4.15C6.48 4.15 4.15 6.48 4.15 9.35C4.15 11.72 5.73 13.72 7.9 14.35L7.9 14.02C8.08 10.61 10.9 7.9 14.35 7.9C13.72 5.73 11.72 4.15 9.35 4.15Z"
      fill="currentColor"
    />
  </svg>
);
