// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/input_form/meaning_control-1.svg

import type { IconProps } from "../../types";

export const IconCheck = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M18.43 7.09C18.72 6.8 19.2 6.8 19.49 7.09C19.78 7.39 19.78 7.86 19.49 8.16L10.32 17.32C10.18 17.46 9.99 17.54 9.79 17.54C9.59 17.54 9.4 17.46 9.26 17.32L5.09 13.16C4.8 12.86 4.8 12.39 5.09 12.1C5.39 11.8 5.86 11.8 6.16 12.1L9.79 15.73L18.43 7.09Z"
      fill="currentColor"
    />
  </svg>
);
