// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/input_form/meaning_control-2.svg

import type { IconProps } from "../../types";

export const IconChevronUp = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M7.44 14.44C7.2 14.69 6.8 14.69 6.56 14.44C6.31 14.2 6.31 13.8 6.56 13.56L11.56 8.56C11.8 8.31 12.2 8.31 12.44 8.56L17.44 13.56C17.69 13.8 17.69 14.2 17.44 14.44C17.2 14.69 16.8 14.69 16.56 14.44L12 9.89L7.44 14.44Z"
      fill="currentColor"
    />
  </svg>
);
