// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/input_form/meaning_control-3.svg

import type { IconProps } from "../../types";

export const IconChevronDown = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.47 9.47C16.76 9.18 17.24 9.18 17.53 9.47C17.82 9.76 17.82 10.24 17.53 10.53L12.53 15.53C12.24 15.82 11.76 15.82 11.47 15.53L6.47 10.53C6.18 10.24 6.18 9.76 6.47 9.47C6.76 9.18 7.24 9.18 7.53 9.47L12 13.94L16.47 9.47Z"
      fill="currentColor"
    />
  </svg>
);
