// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-57.svg

import type { IconProps } from "../../types";

export const IconChevronRightToLine = ({
  size = 24,
  className,
  ...props
}: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    className={className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M7.18 6.18C7.43 5.94 7.82 5.94 8.07 6.18L13.07 11.18C13.31 11.43 13.31 11.82 13.07 12.07L8.07 17.07C7.82 17.31 7.43 17.31 7.18 17.07C6.94 16.82 6.94 16.43 7.18 16.18L11.74 11.63L7.18 7.07C6.94 6.82 6.94 6.43 7.18 6.18ZM15.96 6C16.31 6 16.59 6.28 16.59 6.63V16.63C16.59 16.97 16.31 17.25 15.96 17.25C15.62 17.25 15.34 16.97 15.34 16.63V6.63C15.34 6.28 15.62 6 15.96 6Z"
      fill="currentColor"
    />
  </svg>
);
