// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-153.svg

import type { IconProps } from "../../types";

export const IconChevronLeft = ({
  size = 24,
  className,
  ...props
}: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    className={className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13.06 6.56C13.3 6.31 13.7 6.31 13.94 6.56C14.19 6.8 14.19 7.2 13.94 7.44L9.39 12L13.94 16.56C14.19 16.8 14.19 17.2 13.94 17.44C13.7 17.69 13.3 17.69 13.06 17.44L8.06 12.44C7.81 12.2 7.81 11.8 8.06 11.56L13.06 6.56Z"
      fill="currentColor"
    />
  </svg>
);
