// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-194.svg

import type { IconProps } from "../../types";

export const IconChevronsLeft = ({
  size = 24,
  className,
  ...props
}: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    className={className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M15.52 6.18C15.76 5.94 16.16 5.94 16.4 6.18C16.65 6.43 16.65 6.82 16.4 7.07L11.84 11.63L16.4 16.19C16.65 16.43 16.65 16.83 16.4 17.07C16.16 17.31 15.76 17.31 15.52 17.07L10.52 12.07C10.27 11.82 10.27 11.43 10.52 11.18L15.52 6.18ZM7.63 6C7.97 6 8.25 6.28 8.25 6.63V16.63C8.25 16.97 7.97 17.25 7.63 17.25C7.28 17.25 7 16.97 7 16.63V6.63C7 6.28 7.28 6 7.63 6Z"
      fill="currentColor"
    />
  </svg>
);
