// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/ds/meaning-120.svg

import type { IconProps } from "../../types";

export const IconCircleX = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 32 32"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.55 5.35C22.18 5.63 26.67 10.29 26.67 16L26.65 16.55C26.37 22.18 21.71 26.67 16 26.67L15.45 26.65C10 26.38 5.62 22 5.35 16.55L5.33 16C5.33 10.11 10.11 5.33 16 5.33L16.55 5.35ZM16 6.83C10.94 6.83 6.83 10.94 6.83 16C6.83 21.06 10.94 25.17 16 25.17C21.06 25.17 25.17 21.06 25.17 16C25.17 10.94 21.06 6.83 16 6.83ZM18.22 12.3C18.52 12.01 18.99 12.01 19.28 12.3C19.58 12.6 19.58 13.07 19.28 13.36L16.85 15.79L19.28 18.22C19.58 18.52 19.58 18.99 19.28 19.28C18.99 19.58 18.52 19.58 18.22 19.28L15.79 16.85L13.36 19.28C13.07 19.58 12.6 19.58 12.3 19.28C12.01 18.99 12.01 18.52 12.3 18.22L14.73 15.79L12.3 13.36C12.01 13.07 12.01 12.6 12.3 12.3C12.6 12.01 13.07 12.01 13.36 12.3L15.79 14.73L18.22 12.3Z"
      fill="currentColor"
    />
  </svg>
);
