// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-89.svg

import type { IconProps } from "../../types";

export const IconCircleChevronRight = ({
  size = 24,
  className,
  ...props
}: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    className={className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.13 3.38C16.96 3.38 20.88 7.29 20.88 12.13C20.88 16.96 16.96 20.88 12.13 20.88C7.29 20.88 3.38 16.96 3.38 12.13C3.38 7.29 7.29 3.38 12.13 3.38ZM12.13 4.63C7.98 4.63 4.63 7.98 4.63 12.13C4.63 16.27 7.98 19.63 12.13 19.63C16.27 19.63 19.63 16.27 19.63 12.13C19.63 7.98 16.27 4.63 12.13 4.63ZM10.56 8.56C10.8 8.31 11.2 8.31 11.44 8.56L14.44 11.56C14.69 11.8 14.69 12.2 14.44 12.44L11.44 15.44C11.2 15.69 10.8 15.69 10.56 15.44C10.31 15.2 10.31 14.8 10.56 14.56L13.12 12L10.56 9.44C10.31 9.2 10.31 8.8 10.56 8.56Z"
      fill="currentColor"
    />
  </svg>
);
