// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/ds/meaning-123.svg

import type { IconProps } from "../../types";

export const IconCircleCheck = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 32 32"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.55 5.35C22.18 5.63 26.67 10.29 26.67 16L26.65 16.55C26.37 22.19 21.71 26.67 16 26.67L15.45 26.65C10 26.38 5.62 22 5.35 16.55L5.33 16C5.33 10.11 10.11 5.33 16 5.33L16.55 5.35ZM16 6.83C10.94 6.83 6.83 10.94 6.83 16C6.83 21.06 10.94 25.17 16 25.17C21.06 25.17 25.17 21.06 25.17 16C25.17 10.94 21.06 6.83 16 6.83ZM19.48 12.8C19.77 12.51 20.25 12.51 20.54 12.81C20.83 13.11 20.82 13.58 20.52 13.87L15.02 19.21C14.73 19.49 14.27 19.49 13.98 19.21L11.48 16.78C11.18 16.49 11.17 16.02 11.46 15.72C11.75 15.42 12.23 15.42 12.52 15.71L14.5 17.62L19.48 12.8Z"
      fill="currentColor"
    />
  </svg>
);
