// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/status/meaning-74.svg

import type { IconProps } from "../../types";

export const IconCirleAlert = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.02 3C16.99 3 21.03 7.04 21.03 12.02C21.03 16.99 16.99 21.03 12.02 21.03C7.04 21.03 3 16.99 3 12.02C3 7.04 7.04 3 12.02 3ZM12.02 4.25C7.73 4.25 4.25 7.73 4.25 12.02C4.25 16.3 7.73 19.78 12.02 19.78C16.3 19.78 19.78 16.3 19.78 12.02C19.78 7.73 16.3 4.25 12.02 4.25ZM12.02 14.75C12.37 14.75 12.65 15.03 12.65 15.37C12.65 15.72 12.37 16 12.02 16H12.02C11.67 16 11.39 15.72 11.39 15.37C11.39 15.03 11.67 14.75 12.02 14.75H12.02ZM12.02 8.03C12.36 8.03 12.64 8.31 12.64 8.66V12.02C12.64 12.36 12.36 12.64 12.02 12.64C11.67 12.64 11.39 12.36 11.39 12.02V8.66C11.39 8.31 11.67 8.03 12.02 8.03Z"
      fill="currentColor"
    />
  </svg>
);
