// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/industry/meaning-186.svg

import type { IconProps } from "../../types";

export const IconClockOff = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.29 3C16.32 3 19.58 6.27 19.58 10.29C19.58 14.11 16.65 17.24 12.92 17.55V19.67H16.46C16.8 19.67 17.08 19.95 17.08 20.29C17.08 20.64 16.8 20.92 16.46 20.92H8.13C7.78 20.92 7.5 20.64 7.5 20.29C7.5 19.95 7.78 19.67 8.13 19.67H11.67V17.55C7.93 17.24 5 14.11 5 10.29C5 6.27 8.27 3 12.29 3ZM12.29 4.25C8.96 4.25 6.25 6.96 6.25 10.29C6.25 13.63 8.96 16.33 12.29 16.33C15.63 16.33 18.33 13.63 18.33 10.29C18.33 6.96 15.63 4.25 12.29 4.25ZM14.35 7.77C14.59 7.52 14.99 7.52 15.23 7.77C15.48 8.01 15.48 8.41 15.23 8.65L10.65 13.23C10.41 13.48 10.01 13.48 9.77 13.23C9.52 12.99 9.52 12.59 9.77 12.35L14.35 7.77ZM10.18 7.02C10.43 6.77 10.82 6.77 11.07 7.02C11.31 7.26 11.31 7.66 11.07 7.9L9.9 9.07C9.66 9.31 9.26 9.31 9.02 9.07C8.77 8.82 8.77 8.43 9.02 8.18L10.18 7.02Z"
      fill="currentColor"
    />
  </svg>
);
