// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/display/meaning-203.svg

import type { IconProps } from "../../types";

export const IconClock = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M11.63 1C17.49 1 22.25 5.76 22.25 11.63C22.25 17.49 17.49 22.25 11.63 22.25C5.76 22.25 1 17.49 1 11.63C1 5.76 5.76 1 11.63 1ZM11.63 2.25C6.45 2.25 2.25 6.45 2.25 11.63C2.25 16.8 6.45 21 11.63 21C16.8 21 21 16.8 21 11.63C21 6.45 16.8 2.25 11.63 2.25ZM11.63 5C11.97 5 12.25 5.28 12.25 5.63V11.24L15.9 13.07C16.21 13.22 16.34 13.6 16.18 13.9C16.03 14.21 15.65 14.34 15.35 14.18L11.35 12.18C11.13 12.08 11 11.86 11 11.63V5.63C11 5.28 11.28 5 11.63 5Z"
      fill="currentColor"
    />
  </svg>
);
