// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/create-event/meaning-56.svg

import type { IconProps } from "../../types";

export const IconClose = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16.56 6.56C16.8 6.31 17.2 6.31 17.44 6.56C17.69 6.8 17.69 7.2 17.44 7.44L12.88 12L17.44 16.56C17.69 16.8 17.69 17.2 17.44 17.44C17.2 17.69 16.8 17.69 16.56 17.44L12 12.88L7.44 17.44C7.2 17.69 6.8 17.69 6.56 17.44C6.31 17.2 6.31 16.8 6.56 16.56L11.12 12L6.56 7.44C6.31 7.2 6.31 6.8 6.56 6.56C6.8 6.31 7.2 6.31 7.44 6.56L12 11.12L16.56 6.56Z"
      fill="currentColor"
    />
  </svg>
);
