// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/calendar-view/meaning-116.svg

import type { IconProps } from "../../types";

export const IconColumns = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M18.5 4.88C19.95 4.88 21.13 6.05 21.13 7.5V16.5C21.13 17.95 19.95 19.13 18.5 19.13H5.5C4.05 19.13 2.88 17.95 2.88 16.5V7.5C2.88 6.05 4.05 4.88 5.5 4.88H18.5ZM5.5 6.13C4.74 6.13 4.13 6.74 4.13 7.5V16.5C4.13 17.26 4.74 17.88 5.5 17.88H7.5V6.13H5.5ZM8.75 17.88H11.5V6.13H8.75V17.88ZM12.75 17.88H15.5V6.13H12.75V17.88ZM16.75 17.88H18.5C19.26 17.88 19.88 17.26 19.88 16.5V7.5C19.88 6.74 19.26 6.13 18.5 6.13H16.75V17.88Z"
      fill="currentColor"
    />
  </svg>
);
