// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/shape/general/conversation.svg

import type { IconProps } from "../../types";

export const IconConversation = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.75 4.37C18.34 4.37 19.62 5.66 19.63 7.25V13.98C19.62 15.43 17.96 16.26 16.81 15.37L15.74 14.54V15.09C15.74 16.68 14.45 17.97 12.86 17.97H9.42C9.06 17.97 8.71 18.09 8.43 18.3L7.19 19.26C6.04 20.15 4.38 19.32 4.38 17.87V11.14C4.38 9.55 5.66 8.26 7.25 8.26H8.26V7.25C8.26 5.66 9.55 4.37 11.14 4.37H16.75ZM7.25 9.51C6.35 9.51 5.63 10.24 5.63 11.14V17.87C5.63 18.29 6.1 18.52 6.43 18.27L7.66 17.31C8.17 16.93 8.78 16.72 9.42 16.72H12.86C13.76 16.72 14.49 15.99 14.49 15.09V11.14C14.49 10.24 13.76 9.51 12.86 9.51H7.25ZM11.14 5.62C10.24 5.62 9.51 6.35 9.51 7.25V8.26H12.86C14.45 8.26 15.74 9.55 15.74 11.14V13.07C15.95 13.16 16.15 13.28 16.34 13.42L17.57 14.38C17.9 14.63 18.37 14.4 18.38 13.98V7.25C18.37 6.35 17.65 5.62 16.75 5.62H11.14Z"
      fill="currentColor"
    />
  </svg>
);
