// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/request_response/meaning-157.svg

import type { IconProps } from "../../types";

export const IconCopy = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M17 7.21C18.27 7.21 19.29 8.23 19.29 9.5V17.83C19.29 19.1 18.27 20.12 17 20.13H11.17C9.9 20.12 8.88 19.1 8.88 17.83V9.5C8.88 8.23 9.9 7.21 11.17 7.21H17ZM11.17 8.46C10.59 8.46 10.13 8.92 10.13 9.5V17.83C10.13 18.41 10.59 18.87 11.17 18.88H17C17.58 18.87 18.04 18.41 18.04 17.83V9.5C18.04 8.92 17.58 8.46 17 8.46H11.17ZM12.83 3.88C13.68 3.88 14.42 4.34 14.82 5.02C14.99 5.32 14.89 5.7 14.59 5.87C14.29 6.05 13.91 5.95 13.74 5.65C13.55 5.33 13.22 5.13 12.83 5.13H7C6.43 5.13 5.96 5.59 5.96 6.17V14.5C5.96 15.08 6.43 15.54 7 15.54C7.35 15.54 7.63 15.82 7.63 16.17C7.63 16.51 7.35 16.79 7 16.79C5.73 16.79 4.71 15.77 4.71 14.5V6.17C4.71 4.9 5.73 3.88 7 3.88H12.83Z"
      fill="currentColor"
    />
  </svg>
);
