// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/list/shape/general/corner-down-right.svg

import type { IconProps } from "../../types";

export const IconCornerDownRight = ({
  size = 24,
  className,
  ...props
}: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    className={className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"}
    fill="none"
    height={size}
    viewBox="0 0 20 20"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M3.85 3.23C4.2 3.23 4.48 3.51 4.48 3.85V9.26C4.48 9.92 4.74 10.55 5.2 11.01C5.66 11.47 6.29 11.73 6.95 11.73H14.71L11.91 8.93C11.67 8.69 11.67 8.29 11.91 8.05C12.16 7.8 12.55 7.81 12.8 8.05L16.66 11.91C16.78 12.03 16.85 12.18 16.85 12.36C16.85 12.42 16.83 12.48 16.82 12.53C16.81 12.55 16.81 12.57 16.8 12.59C16.76 12.67 16.72 12.74 16.66 12.8L12.8 16.66C12.55 16.91 12.16 16.91 11.91 16.66C11.67 16.42 11.67 16.02 11.91 15.78L14.71 12.98H6.95C5.96 12.98 5.01 12.59 4.32 11.89C3.62 11.2 3.23 10.25 3.23 9.26V3.85C3.23 3.51 3.51 3.23 3.85 3.23Z"
      fill="currentColor"
    />
  </svg>
);
