// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/suiteC_tool/meaning-182.svg

import type { IconProps } from "../../types";

export const IconCursor = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M6.29 5.29C6.44 5.29 6.59 5.31 6.73 5.37L6.73 5.37L20.06 10.79L20.21 10.86C20.34 10.94 20.46 11.06 20.55 11.2C20.67 11.38 20.72 11.6 20.71 11.82C20.69 12.04 20.61 12.25 20.47 12.42C20.33 12.58 20.14 12.71 19.93 12.76H19.93L14.82 14.08H14.82C14.64 14.12 14.48 14.22 14.35 14.35C14.22 14.48 14.12 14.64 14.08 14.82L12.76 19.93V19.93C12.7 20.14 12.58 20.33 12.42 20.47C12.25 20.61 12.04 20.69 11.82 20.71C11.6 20.72 11.38 20.67 11.2 20.55C11.06 20.46 10.94 20.35 10.86 20.21L10.79 20.06L5.37 6.73L5.37 6.73C5.29 6.54 5.27 6.33 5.31 6.13L5.35 5.98C5.4 5.84 5.48 5.7 5.59 5.59L5.71 5.49C5.84 5.4 5.98 5.34 6.13 5.31L6.29 5.29ZM11.71 19.01L12.86 14.51V14.51C12.97 14.11 13.17 13.75 13.46 13.46C13.75 13.18 14.12 12.97 14.51 12.87L19.01 11.71L6.71 6.71L11.71 19.01Z"
      fill="currentColor"
    />
  </svg>
);
