// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/shape/general/type=filled-1.svg

import type { IconProps } from "../../types";

export const IconDislike = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.44 19.2C12.09 19.73 11.22 20.1 10.48 19.83C9.68 19.56 9.16 18.66 9.33 17.86L9.75 15.2C9.78 14.96 9.72 14.74 9.58 14.57C9.44 14.41 9.24 14.31 9.02 14.31L5.68 14.31C5.04 14.31 4.48 14.05 4.16 13.6C3.85 13.16 3.79 12.59 3.99 12.01L5.99 5.91C6.25 4.9 7.34 4.08 8.43 4.08L11.6 4.08C12.15 4.08 12.91 4.27 13.26 4.62L14.3 5.42C14.7 5.72 14.93 6.2 14.93 6.71L14.93 14.98C14.93 15.31 14.84 15.63 14.66 15.89L12.44 19.2ZM17.52 16.57C16.26 16.57 15.75 16.08 15.75 14.88L15.75 6.69C15.75 5.48 16.26 4.99 17.52 4.99L18.35 4.99C19.61 4.99 20.13 5.48 20.13 6.69L20.13 14.88C20.13 16.08 19.61 16.57 18.35 16.57L17.52 16.57Z"
      fill="currentColor"
    />
  </svg>
);
