// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/suiteC_chip/meaning-126.svg

import type { IconProps } from "../../types";

export const IconDocumentText = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M17.47 3C18.76 3 19.58 4.25 19.58 5.48V18.44C19.58 19.67 18.76 20.92 17.47 20.92H7.11C5.82 20.92 5 19.67 5 18.44V5.48C5 4.25 5.82 3 7.11 3H17.47ZM7.11 4.25C6.76 4.25 6.25 4.66 6.25 5.48V18.44C6.25 19.26 6.76 19.67 7.11 19.67H17.47C17.82 19.67 18.33 19.26 18.33 18.44V5.48C18.33 4.66 17.82 4.25 17.47 4.25H7.11ZM15.96 14.12C16.3 14.12 16.58 14.4 16.58 14.74C16.58 15.09 16.3 15.37 15.96 15.37H8.96C8.61 15.37 8.33 15.09 8.33 14.74C8.33 14.4 8.61 14.12 8.96 14.12H15.96ZM15.96 11.12C16.3 11.12 16.58 11.4 16.58 11.74C16.58 12.09 16.3 12.37 15.96 12.37H8.96C8.61 12.37 8.33 12.09 8.33 11.74C8.33 11.4 8.61 11.12 8.96 11.12H15.96ZM15.96 8.12C16.3 8.12 16.58 8.4 16.58 8.74C16.58 9.09 16.3 9.37 15.96 9.37H8.96C8.61 9.37 8.33 9.09 8.33 8.74C8.33 8.4 8.61 8.12 8.96 8.12H15.96Z"
      fill="currentColor"
    />
  </svg>
);
