// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/suiteW_action/meaning-81.svg

import type { IconProps } from "../../types";

export const IconExpandCollapse = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M14.85 13.52C15.09 13.27 15.49 13.27 15.73 13.52C15.98 13.76 15.98 14.16 15.73 14.4L12.4 17.73C12.16 17.98 11.76 17.98 11.52 17.73L8.18 14.4C7.94 14.16 7.94 13.76 8.18 13.52C8.43 13.27 8.82 13.27 9.07 13.52L11.96 16.41L14.85 13.52ZM11.62 6.1C11.86 5.94 12.19 5.97 12.4 6.18L15.73 9.52C15.98 9.76 15.98 10.16 15.73 10.4C15.49 10.64 15.09 10.64 14.85 10.4L11.96 7.51L9.07 10.4C8.82 10.64 8.43 10.64 8.18 10.4C7.94 10.16 7.94 9.76 8.18 9.52L11.52 6.18L11.62 6.1Z"
      fill="currentColor"
    />
  </svg>
);
