// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/social-media/meaning-8.svg

import type { IconProps } from "../../types";

export const IconFacebook = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M22 12.06C22 6.5 17.52 2 12 2C6.48 2 2 6.5 2 12.06C2 17.08 5.66 21.25 10.44 22V14.97H7.9V12.06H10.44V9.84C10.44 7.32 11.93 5.93 14.21 5.93C15.31 5.93 16.45 6.13 16.45 6.13V8.6H15.19C13.95 8.6 13.56 9.38 13.56 10.17V12.06H16.34L15.89 14.97H13.56V22C18.34 21.25 22 17.08 22 12.06Z"
      fill="currentColor"
    />
  </svg>
);
