// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/social-media/meaning-19.svg

import type { IconProps } from "../../types";

export const IconGoogle = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.2 2.99C14.84 2.99 17.05 3.96 18.75 5.54L15.94 8.35C14.92 7.38 13.63 6.88 12.2 6.88C9.65 6.88 7.49 8.6 6.71 10.92V10.92C6.52 11.51 6.41 12.14 6.41 12.78C6.41 13.43 6.52 14.05 6.71 14.64C7.48 16.96 9.64 18.68 12.2 18.68C13.51 18.68 14.63 18.33 15.51 17.74L15.51 17.75C16.55 17.05 17.24 16.01 17.47 14.79H12.2V11H21.42C21.54 11.64 21.6 12.31 21.6 13C21.6 15.99 20.53 18.5 18.68 20.2H18.68C17.06 21.7 14.84 22.58 12.2 22.58C8.37 22.58 5.05 20.38 3.44 17.18V17.18C2.78 15.86 2.4 14.36 2.4 12.78C2.4 11.2 2.78 9.7 3.44 8.38L3.6 8.08C5.26 5.05 8.49 2.99 12.2 2.99Z"
      fill="currentColor"
    />
  </svg>
);
