// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/meaning-11.svg

import type { IconProps } from "../../types";

export const IconGridDots = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M8.5 12C10.43 12 12 13.57 12 15.5C12 17.43 10.43 19 8.5 19C6.57 19 5 17.43 5 15.5C5 13.57 6.57 12 8.5 12ZM15.5 12C17.43 12 19 13.57 19 15.5C19 17.43 17.43 19 15.5 19C13.57 19 12 17.43 12 15.5C12 13.57 13.57 12 15.5 12ZM8.5 5C10.43 5 12 6.57 12 8.5C12 10.43 10.43 12 8.5 12C6.57 12 5 10.43 5 8.5C5 6.57 6.57 5 8.5 5ZM15.5 5C17.43 5 19 6.57 19 8.5C19 10.43 17.43 12 15.5 12C13.57 12 12 10.43 12 8.5C12 6.57 13.57 5 15.5 5Z"
      fill="currentColor"
    />
  </svg>
);
