// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/create-event/meaning-6.svg

import type { IconProps } from "../../types";

export const IconHamburgerMenu = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.63 18C16.97 18 17.25 18.28 17.25 18.63C17.25 18.97 16.97 19.25 16.63 19.25H2.63C2.28 19.25 2 18.97 2 18.63C2 18.28 2.28 18 2.63 18H16.63ZM14.63 11C14.97 11 15.25 11.28 15.25 11.63C15.25 11.97 14.97 12.25 14.63 12.25H2.63C2.28 12.25 2 11.97 2 11.63C2 11.28 2.28 11 2.63 11H14.63ZM20.63 4C20.97 4 21.25 4.28 21.25 4.63C21.25 4.97 20.97 5.25 20.63 5.25H2.63C2.28 5.25 2 4.97 2 4.63C2 4.28 2.28 4 2.63 4H20.63Z"
      fill="currentColor"
    />
  </svg>
);
