// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/top_toolbar/meaning-147.svg

import type { IconProps } from "../../types";

export const IconHamburger = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M18.67 17.21C19.01 17.21 19.29 17.49 19.29 17.83C19.29 18.18 19.01 18.46 18.67 18.46H5.33C4.99 18.46 4.71 18.18 4.71 17.83C4.71 17.49 4.99 17.21 5.33 17.21H18.67ZM18.67 11.38C19.01 11.38 19.29 11.65 19.29 12C19.29 12.35 19.01 12.63 18.67 12.63H5.33C4.99 12.62 4.71 12.35 4.71 12C4.71 11.65 4.99 11.38 5.33 11.38H18.67ZM18.67 5.54C19.01 5.54 19.29 5.82 19.29 6.17C19.29 6.51 19.01 6.79 18.67 6.79H5.33C4.99 6.79 4.71 6.51 4.71 6.17C4.71 5.82 4.99 5.54 5.33 5.54H18.67Z"
      fill="currentColor"
    />
  </svg>
);
