// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/manage_account/meaning-134.svg

import type { IconProps } from "../../types";

export const IconInfo = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12.1 3.18C17.02 3.18 21.01 7.17 21.01 12.1C21.01 17.02 17.02 21.01 12.1 21.01C7.17 21.01 3.18 17.02 3.18 12.1C3.18 7.17 7.17 3.18 12.1 3.18ZM12.1 4.43C7.86 4.43 4.43 7.86 4.43 12.1C4.43 16.33 7.86 19.76 12.1 19.76C16.33 19.76 19.76 16.33 19.76 12.1C19.76 7.86 16.33 4.43 12.1 4.43ZM12.1 11.47C12.44 11.47 12.72 11.75 12.72 12.1V15.41C12.72 15.76 12.44 16.04 12.1 16.04C11.75 16.04 11.47 15.76 11.47 15.41V12.1C11.47 11.75 11.75 11.47 12.1 11.47ZM12.1 8.15C12.45 8.15 12.73 8.43 12.73 8.78C12.73 9.12 12.45 9.4 12.1 9.4H12.1C11.75 9.4 11.47 9.12 11.47 8.78C11.47 8.43 11.75 8.15 12.1 8.15H12.1Z"
      fill="currentColor"
    />
  </svg>
);
