// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/shape/general/type=filled.svg

import type { IconProps } from "../../types";

export const IconLike = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M11.56 4.8C11.91 4.27 12.78 3.9 13.52 4.17C14.31 4.44 14.84 5.34 14.67 6.14L14.25 8.8C14.21 9.04 14.28 9.26 14.42 9.43C14.56 9.59 14.76 9.69 14.98 9.69H18.32C18.96 9.69 19.51 9.95 19.84 10.4C20.15 10.84 20.2 11.41 20 11.99L18 18.09C17.75 19.1 16.65 19.92 15.56 19.92H12.39C11.85 19.92 11.09 19.73 10.74 19.38L9.7 18.58C9.3 18.28 9.06 17.8 9.06 17.29V9.02C9.06 8.69 9.16 8.37 9.34 8.11L11.56 4.8ZM6.48 7.43C7.74 7.43 8.25 7.92 8.25 9.12V17.31C8.25 18.52 7.74 19.01 6.48 19.01H5.64C4.38 19.01 3.87 18.52 3.87 17.31V9.12C3.87 7.92 4.38 7.43 5.64 7.43H6.48Z"
      fill="currentColor"
    />
  </svg>
);
