// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/calendar-view/meaning-88.svg

import type { IconProps } from "../../types";

export const IconListView = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M19.88 18.38C20.22 18.38 20.5 18.65 20.5 19C20.5 19.35 20.22 19.63 19.88 19.63H4.13C3.78 19.63 3.5 19.35 3.5 19C3.5 18.65 3.78 18.38 4.13 18.38H19.88ZM18.5 8C19.95 8 21.13 9.18 21.13 10.63V13.63C21.13 15.07 19.95 16.25 18.5 16.25H5.5C4.05 16.25 2.88 15.07 2.88 13.63V10.63C2.88 9.18 4.05 8 5.5 8H18.5ZM5.5 9.25C4.74 9.25 4.13 9.87 4.13 10.63V13.63C4.13 14.38 4.74 15 5.5 15H18.5C19.26 15 19.88 14.38 19.88 13.63V10.63C19.88 9.87 19.26 9.25 18.5 9.25H5.5ZM19.88 4.38C20.22 4.38 20.5 4.65 20.5 5C20.5 5.35 20.22 5.63 19.88 5.63H4.13C3.78 5.63 3.5 5.35 3.5 5C3.5 4.65 3.78 4.38 4.13 4.38H19.88Z"
      fill="currentColor"
    />
  </svg>
);
