// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-54.svg

import type { IconProps } from "../../types";

export const IconLogOut = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M9.54 4C9.89 4 10.17 4.28 10.17 4.63C10.17 4.97 9.89 5.25 9.54 5.25H6.26C5.99 5.25 5.74 5.36 5.55 5.55C5.36 5.74 5.25 5.99 5.25 6.26V17.74C5.25 18.01 5.36 18.26 5.55 18.45C5.74 18.64 5.99 18.75 6.26 18.75H9.54C9.89 18.75 10.17 19.03 10.17 19.38C10.17 19.72 9.89 20 9.54 20H6.26C5.66 20 5.09 19.76 4.66 19.34C4.24 18.91 4 18.34 4 17.74V6.26C4 5.66 4.24 5.09 4.66 4.66C5.09 4.24 5.66 4 6.26 4H9.54ZM14.84 7.18C15.08 6.94 15.48 6.94 15.72 7.18L19.57 11.03C19.82 11.12 20 11.35 20 11.63C20 11.64 20 11.66 20 11.67C20 11.69 20 11.71 20 11.72C20 11.89 19.93 12.05 19.82 12.16L15.72 16.26C15.48 16.51 15.08 16.51 14.84 16.26C14.59 16.02 14.59 15.62 14.84 15.38L17.96 12.25H9.54C9.2 12.25 8.92 11.97 8.92 11.63C8.92 11.28 9.2 11 9.54 11H17.77L14.84 8.07C14.59 7.82 14.59 7.43 14.84 7.18Z"
      fill="currentColor"
    />
  </svg>
);
