// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-163.svg

import type { IconProps } from "../../types";

export const IconMail = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M19.55 4C20.94 4 22.06 5.12 22.06 6.51V17.79C22.06 19.17 20.94 20.3 19.55 20.3H4.51C3.12 20.3 2 19.18 2 17.79V6.51C2 5.12 3.12 4 4.51 4H19.55ZM13.32 13.36C13.31 13.36 13.3 13.37 13.29 13.37C12.91 13.6 12.48 13.71 12.04 13.71C11.59 13.71 11.16 13.6 10.78 13.37C10.77 13.37 10.76 13.36 10.75 13.36L3.25 8.59V17.79C3.25 18.48 3.81 19.05 4.51 19.05H19.55C20.25 19.05 20.81 18.48 20.81 17.79V8.59L13.32 13.36ZM4.51 5.25C3.81 5.25 3.25 5.81 3.25 6.51V7.1L11.41 12.3C11.6 12.4 11.82 12.46 12.04 12.46C12.25 12.46 12.47 12.4 12.65 12.3L20.81 7.1V6.51C20.81 5.81 20.25 5.25 19.55 5.25H4.51Z"
      fill="currentColor"
    />
  </svg>
);
