// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/suiteC_tool/meaning-72.svg

import type { IconProps } from "../../types";

export const IconMinus = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M19 11.38C19.35 11.38 19.63 11.65 19.63 12C19.63 12.35 19.35 12.63 19 12.63H5C4.65 12.63 4.38 12.35 4.38 12C4.38 11.65 4.65 11.38 5 11.38H19Z"
      fill="currentColor"
    />
  </svg>
);
