// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/meaning-12.svg

import type { IconProps } from "../../types";

export const IconMosaic = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M9.67 19H5V14.33H9.67V19ZM19 19H14.33V14.33H19V19ZM14.33 14.33H9.67V9.67H14.33V14.33ZM9.67 9.67H5V5H9.67V9.67ZM19 9.67H14.33V5H19V9.67Z"
      fill="currentColor"
    />
  </svg>
);
