// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/brand/meaning-17.svg

import type { IconProps } from "../../types";

export const IconOffline = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M7.05 6.91C9.21 4.75 12.41 4.2 15.08 5.3C15.67 5.52 16.18 5.83 16.58 6.12L14.36 7.15C12.28 6.28 9.9 6.87 8.45 8.32C6.55 10.21 6.12 13.46 8.19 15.66L8.39 15.87L2.12 21.47C2.51 20.92 3.01 20.4 3.5 19.89C4.89 18.43 6.27 16.98 5.43 14.94C4.3 12.2 4.96 9 7.05 6.91ZM21.74 2.73C19.67 5.58 18.66 6.97 19.47 10.45L19.47 10.44C20.03 12.81 19.43 15.44 17.5 17.36C15.07 19.79 11.18 20.33 7.98 18.15L10.21 17.11C12.25 17.91 14.49 17.56 16.1 15.96C17.71 14.35 18.07 12.01 17.26 10.06C17.11 9.69 16.64 9.6 16.32 9.84L9.75 14.69L19.16 5.24V5.25L21.88 2.53C21.84 2.6 21.79 2.67 21.74 2.73Z"
      fill="currentColor"
    />
  </svg>
);
