// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-37.svg

import type { IconProps } from "../../types";

export const IconPanel = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.31 3.01C19.48 3.17 22 5.79 22 9V15C22 18.21 19.48 20.83 16.31 20.99L16 21H8C4.79 21 2.17 18.48 2.01 15.31L2 15V9C2 5.69 4.69 3 8 3H16L16.31 3.01ZM8 4.25C5.38 4.25 3.25 6.38 3.25 9V15C3.25 17.62 5.38 19.75 8 19.75H16C18.62 19.75 20.75 17.62 20.75 15V9C20.75 6.38 18.62 4.25 16 4.25H8ZM7 7.38C7.35 7.38 7.63 7.65 7.63 8V16C7.63 16.35 7.35 16.63 7 16.63C6.65 16.63 6.38 16.35 6.38 16V8C6.38 7.65 6.65 7.38 7 7.38Z"
      fill="currentColor"
    />
  </svg>
);
