// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-91.svg

import type { IconProps } from "../../types";

export const IconPlay = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M8.38 3C8.8 3 9.21 3.12 9.58 3.33L20.07 9.55C20.43 9.76 20.73 10.06 20.93 10.43C21.14 10.79 21.25 11.2 21.25 11.62C21.25 12.04 21.14 12.45 20.94 12.82C20.73 13.18 20.43 13.49 20.07 13.7L20.07 13.7L9.58 19.92C9.21 20.13 8.8 20.25 8.38 20.25C7.96 20.25 7.55 20.14 7.19 19.93C6.83 19.72 6.53 19.41 6.32 19.05C6.14 18.73 6.03 18.37 6 18L6 17.85V5.4C6 4.98 6.11 4.57 6.32 4.2C6.53 3.84 6.83 3.53 7.19 3.32C7.55 3.11 7.96 3 8.38 3ZM8.38 4.25C8.18 4.25 7.99 4.3 7.82 4.4C7.65 4.5 7.5 4.65 7.4 4.82C7.3 5 7.25 5.2 7.25 5.4V17.85C7.25 18.05 7.3 18.25 7.4 18.43C7.5 18.6 7.65 18.75 7.82 18.85C7.99 18.95 8.18 19 8.38 19C8.57 19 8.77 18.95 8.94 18.84L19.44 12.62L19.56 12.54C19.68 12.45 19.77 12.33 19.85 12.2C19.95 12.03 20 11.83 20 11.62C20 11.42 19.95 11.22 19.85 11.05C19.75 10.87 19.61 10.73 19.44 10.63L19.43 10.63L8.94 4.41C8.77 4.3 8.57 4.25 8.38 4.25Z"
      fill="currentColor"
    />
  </svg>
);
