// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/meaning-13.svg

import type { IconProps } from "../../types";

export const IconQuote = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M5 5C6.86 5 8.64 5.74 9.95 7.05C11.26 8.36 12 10.14 12 12C12 13.86 11.26 15.64 9.95 16.95C8.64 18.26 6.86 19 5 19V5ZM12 5C13.86 5 15.64 5.74 16.95 7.05C18.26 8.36 19 10.14 19 12C19 13.86 18.26 15.64 16.95 16.95C15.64 18.26 13.86 19 12 19V5Z"
      fill="currentColor"
    />
  </svg>
);
