// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/input_form/meaning-148.svg

import type { IconProps } from "../../types";

export const IconSearch = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M11.17 3.87C15.19 3.87 18.46 7.14 18.46 11.17C18.46 12.95 17.81 14.59 16.74 15.86L19.94 19.06C20.19 19.3 20.19 19.7 19.94 19.94C19.7 20.19 19.3 20.19 19.06 19.94L15.86 16.74C14.59 17.81 12.95 18.46 11.17 18.46C7.14 18.46 3.87 15.19 3.87 11.17C3.87 7.14 7.14 3.87 11.17 3.87ZM11.17 5.12C7.83 5.12 5.12 7.83 5.12 11.17C5.12 14.5 7.83 17.21 11.17 17.21C14.5 17.21 17.21 14.5 17.21 11.17C17.21 7.83 14.5 5.12 11.17 5.12Z"
      fill="currentColor"
    />
  </svg>
);
