// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-46.svg

import type { IconProps } from "../../types";

export const IconSeparator = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M12 4.58C12.35 4.58 12.62 4.86 12.63 5.21V18.79C12.63 19.14 12.35 19.42 12 19.42C11.65 19.42 11.38 19.14 11.38 18.79V5.21C11.38 4.86 11.65 4.58 12 4.58ZM7.92 6.53C8.27 6.53 8.55 6.81 8.55 7.15V16.85C8.55 17.2 8.27 17.47 7.92 17.48C7.58 17.48 7.3 17.2 7.3 16.85V7.15C7.3 6.81 7.58 6.53 7.92 6.53ZM16.08 6.53C16.42 6.53 16.7 6.81 16.7 7.15V16.85C16.7 17.2 16.42 17.48 16.08 17.48C15.73 17.47 15.45 17.2 15.45 16.85V7.15C15.45 6.81 15.73 6.53 16.08 6.53ZM3.85 8.47C4.19 8.47 4.47 8.75 4.47 9.09V14.92C4.47 15.27 4.19 15.55 3.85 15.55C3.5 15.55 3.22 15.27 3.22 14.92V9.09C3.22 8.75 3.5 8.47 3.85 8.47ZM20.15 8.47C20.5 8.47 20.78 8.75 20.78 9.09V14.92C20.78 15.27 20.5 15.55 20.15 15.55C19.81 15.55 19.53 15.27 19.53 14.92V9.09C19.53 8.75 19.81 8.47 20.15 8.47Z"
      fill="currentColor"
    />
  </svg>
);
