// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-21.svg

import type { IconProps } from "../../types";

export const IconShare = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M9.52 3.9C10.79 3.9 11.81 4.92 11.81 6.19V9.52C11.81 10.79 10.79 11.81 9.52 11.81H8.48V14.52C8.48 14.8 8.59 15.06 8.78 15.26C8.98 15.45 9.24 15.56 9.52 15.56H12.23V14.52C12.23 13.26 13.26 12.23 14.52 12.23H17.85C19.12 12.23 20.15 13.26 20.15 14.52V17.85C20.15 19.12 19.12 20.15 17.85 20.15H14.52C13.26 20.15 12.23 19.12 12.23 17.85V16.81H9.52C8.91 16.81 8.33 16.57 7.9 16.14C7.47 15.71 7.23 15.13 7.23 14.52V11.81H6.19C4.92 11.81 3.9 10.79 3.9 9.52V6.19C3.9 4.92 4.92 3.9 6.19 3.9H9.52ZM14.52 13.48C13.95 13.48 13.48 13.95 13.48 14.52V17.85C13.48 18.43 13.95 18.9 14.52 18.9H17.85C18.43 18.9 18.9 18.43 18.9 17.85V14.52C18.9 13.95 18.43 13.48 17.85 13.48H14.52ZM6.19 5.15C5.61 5.15 5.15 5.61 5.15 6.19V9.52C5.15 10.1 5.61 10.56 6.19 10.56H9.52C10.1 10.56 10.56 10.1 10.56 9.52V6.19C10.56 5.61 10.1 5.15 9.52 5.15H6.19Z"
      fill="currentColor"
    />
  </svg>
);
