// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/meaning-14.svg

import type { IconProps } from "../../types";

export const IconSpark = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M11.21 5.54C11.49 4.82 12.51 4.82 12.79 5.54L13.31 6.87C14 8.62 15.38 10 17.13 10.69L18.46 11.21C19.18 11.49 19.18 12.51 18.46 12.79L17.13 13.31C15.38 14 14 15.38 13.31 17.13L12.79 18.46C12.51 19.18 11.49 19.18 11.21 18.46L10.69 17.13C10 15.38 8.62 14 6.87 13.31L5.54 12.79C4.82 12.51 4.82 11.49 5.54 11.21L6.87 10.69C8.62 10 10 8.62 10.69 6.87L11.21 5.54Z"
      fill="currentColor"
    />
  </svg>
);
