// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/suiteWchip/meaning-32.svg

import type { IconProps } from "../../types";

export const IconSpellCheck = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M18.52 15.85C18.76 15.61 19.16 15.61 19.4 15.85C19.64 16.09 19.64 16.49 19.4 16.73L16.07 20.07C15.82 20.31 15.43 20.31 15.18 20.07L13.52 18.4C13.27 18.16 13.27 17.76 13.52 17.52C13.76 17.27 14.16 17.27 14.4 17.52L15.62 18.74L18.52 15.85ZM10.62 4C10.86 4 11.08 4.13 11.18 4.35L16.18 14.35C16.34 14.65 16.21 15.03 15.9 15.18C15.6 15.34 15.22 15.21 15.07 14.9L13.57 11.92H7.68L6.18 14.9C6.03 15.21 5.65 15.34 5.35 15.18C5.04 15.03 4.91 14.65 5.07 14.35L10.07 4.35L10.11 4.27C10.23 4.1 10.42 4 10.62 4ZM8.3 10.67H12.95L10.62 6.02L8.3 10.67Z"
      fill="currentColor"
    />
  </svg>
);
