// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/shape/general/text-align-start.svg

import type { IconProps } from "../../types";

export const IconTextAlignStart = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M15.74 16.76C16.09 16.76 16.37 17.04 16.37 17.38C16.37 17.73 16.09 18.01 15.74 18.01H4.22C3.88 18.01 3.6 17.73 3.6 17.38C3.6 17.04 3.88 16.76 4.22 16.76H15.74ZM14.09 11C14.44 11 14.72 11.28 14.72 11.63C14.72 11.97 14.44 12.25 14.09 12.25H4.22C3.88 12.25 3.6 11.97 3.6 11.63C3.6 11.28 3.88 11 4.22 11H14.09ZM19.03 5.24C19.38 5.24 19.66 5.52 19.66 5.87C19.66 6.21 19.38 6.49 19.03 6.49H4.22C3.88 6.49 3.6 6.21 3.6 5.87C3.6 5.52 3.88 5.24 4.22 5.24H19.03Z"
      fill="currentColor"
    />
  </svg>
);
