// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/create-event/meaning-139.svg

import type { IconProps } from "../../types";

export const IconWebcam = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M13.63 5C15.07 5 16.25 6.18 16.25 7.63V9.04L20.56 6.52L20.69 6.46C20.83 6.4 20.97 6.37 21.12 6.37L21.27 6.38C21.37 6.39 21.46 6.42 21.55 6.45L21.69 6.52L21.81 6.6C21.89 6.66 21.96 6.73 22.02 6.81L22.1 6.93L22.16 7.06C22.22 7.2 22.25 7.35 22.25 7.5V15.69L22.24 15.84C22.22 15.99 22.17 16.14 22.09 16.27C21.99 16.44 21.84 16.59 21.66 16.68C21.48 16.78 21.27 16.82 21.07 16.81C20.87 16.8 20.67 16.74 20.5 16.63L20.5 16.63L16.25 13.79V15.63C16.25 17.07 15.07 18.25 13.63 18.25H3.63C2.18 18.25 1 17.07 1 15.63V7.63C1 6.18 2.18 5 3.63 5H13.63ZM3.63 6.25C2.87 6.25 2.25 6.87 2.25 7.63V15.63C2.25 16.38 2.87 17 3.63 17H13.63C14.38 17 15 16.38 15 15.63V7.63C15 6.87 14.38 6.25 13.63 6.25H3.63ZM16.25 10.48V12.29L21 15.46V7.71L16.25 10.48Z"
      fill="currentColor"
    />
  </svg>
);
