// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/input_form/meaning_control.svg

import type { IconProps } from "../../types";

export const IconX = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M16.43 6.43C16.68 6.19 17.07 6.19 17.32 6.43C17.56 6.68 17.56 7.07 17.32 7.32L12.76 11.88L17.32 16.43C17.56 16.68 17.56 17.07 17.32 17.32C17.07 17.56 16.68 17.56 16.43 17.32L11.88 12.76L7.32 17.32C7.07 17.56 6.68 17.56 6.43 17.32C6.19 17.07 6.19 16.68 6.43 16.43L10.99 11.88L6.43 7.32C6.19 7.07 6.19 6.68 6.43 6.43C6.68 6.19 7.07 6.19 7.32 6.43L11.88 10.99L16.43 6.43Z"
      fill="currentColor"
    />
  </svg>
);
