// Generated by scripts/generate-icons.ts — do not edit by hand.
// Source: figma-icons/icons_v1/icons/usecase/action/meaning-160.svg

import type { IconProps } from "../../types";

export const IconZoomOut = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="0 0 24 24"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    <path
      d="M11.17 3.88C15.19 3.88 18.46 7.14 18.46 11.17C18.46 12.96 17.81 14.59 16.74 15.86L19.94 19.06C20.19 19.3 20.19 19.7 19.94 19.94C19.7 20.19 19.3 20.19 19.06 19.94L15.86 16.74C14.59 17.81 12.96 18.46 11.17 18.46C7.14 18.46 3.88 15.19 3.88 11.17C3.88 7.14 7.14 3.88 11.17 3.88ZM11.17 5.13C7.83 5.13 5.13 7.83 5.13 11.17C5.13 14.5 7.83 17.21 11.17 17.21C12.81 17.21 14.3 16.55 15.39 15.48C15.4 15.47 15.42 15.45 15.43 15.43C15.45 15.42 15.47 15.4 15.48 15.39C16.55 14.3 17.21 12.81 17.21 11.17C17.21 7.83 14.5 5.13 11.17 5.13ZM13.67 10.54C14.01 10.54 14.29 10.82 14.29 11.17C14.29 11.51 14.01 11.79 13.67 11.79H8.67C8.32 11.79 8.04 11.51 8.04 11.17C8.04 10.82 8.32 10.54 8.67 10.54H13.67Z"
      fill="currentColor"
    />
  </svg>
);
