#!/usr/bin/env bun
/**
 * Generates one React icon component per SVG in `svgs/` into `src/`.
 * Run with `bun run generate` from packages/icons.
 */
import path from "node:path";

import { toComponentName, toKebabCase } from "./lib/naming";
import { parseSvg } from "./lib/svg";

const PACKAGE_ROOT = path.join(import.meta.dir, "..");
const SVGS_DIR = path.join(PACKAGE_ROOT, "svgs");
const SRC_DIR = path.join(PACKAGE_ROOT, "src");

const GENERATED_BANNER =
  "// Generated by scripts/generate-icons.ts — do not edit by hand.\n// Source: svgs/{{file}}\n\n";

const buildComponentSource = (
  file: string,
  componentName: string,
  viewBox: string,
  children: string
): string =>
  `${GENERATED_BANNER.replace("{{file}}", file)}import type { IconProps } from "./types";

export const ${componentName} = ({ size = 24, ...props }: IconProps) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}
    fill="none"
    height={size}
    viewBox="${viewBox}"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    ${children}
  </svg>
);
`;

const listFiles = async (dir: string, pattern: string): Promise<string[]> => {
  const glob = new Bun.Glob(pattern);
  const files: string[] = [];
  for await (const file of glob.scan({ cwd: dir })) {
    files.push(file);
  }
  return files.toSorted();
};

const buildSlugMap = (files: string[]): Map<string, string> => {
  const slugs = new Map<string, string>();
  for (const file of files) {
    const base = file.slice(0, -path.extname(file).length);
    const slug = toKebabCase(base);
    const collidingFile = slugs.get(slug);
    if (collidingFile) {
      throw new Error(
        `Icon name collision: "${collidingFile}" and "${file}" both resolve to slug "${slug}"`
      );
    }
    slugs.set(slug, file);
  }
  return slugs;
};

const generateIcon = async (slug: string, file: string): Promise<void> => {
  const source = await Bun.file(path.join(SVGS_DIR, file)).text();
  const { viewBox, children } = parseSvg(source, file);
  const componentName = toComponentName(slug);
  const code = buildComponentSource(file, componentName, viewBox, children);
  await Bun.write(path.join(SRC_DIR, `${slug}.tsx`), code);
};

const removeStaleIconFiles = async (
  keptSlugs: Set<string>
): Promise<number> => {
  const existingFiles = await listFiles(SRC_DIR, "*.tsx");
  const staleFiles = existingFiles.filter(
    (file) => !keptSlugs.has(file.slice(0, -path.extname(file).length))
  );
  await Promise.all(
    staleFiles.map((file) => Bun.file(path.join(SRC_DIR, file)).delete())
  );
  return staleFiles.length;
};

const main = async () => {
  const svgFiles = await listFiles(SVGS_DIR, "*.svg");
  if (svgFiles.length === 0) {
    throw new Error(`No .svg files found in ${SVGS_DIR}`);
  }

  const slugs = buildSlugMap(svgFiles);

  await Promise.all([...slugs].map(([slug, file]) => generateIcon(slug, file)));
  const removed = await removeStaleIconFiles(new Set(slugs.keys()));

  const summary = [
    `Generated ${slugs.size} icon${slugs.size === 1 ? "" : "s"}`,
  ];
  if (removed > 0) {
    summary.push(`removed ${removed} stale file${removed === 1 ? "" : "s"}`);
  }
  console.log(`${summary.join(", ")}.`);
};

await main();
