#!/usr/bin/env bun
/**
 * Generates one React icon component per resolved shape in the active
 * `figma-icons/` version into `generated-icons/<version>/<category>/`. Run
 * with `bun run gen` from packages/icons.
 *
 * Output is versioned the same way `@cs/design-tokens` lays out
 * `generated-token/<version>/`: each figma-icons version gets its own
 * folder, so an older version's output survives switching `.current` to a
 * newer one and can still be imported via a pinned subpath. Category
 * (`icons/`, `graphics/`, ... — any top-level dump folder works, nothing
 * here hardcodes the set) nests one level inside that. The public import
 * path stays flat (`@cs/icons/<slug>`) via package.json's `./*` export
 * (an alias for `./latest/*`), kept in sync every time this runs — see
 * `lib/package-exports.ts`. Filling in `names.json` for whatever
 * `preview.html` flags as unresolved/duplicate and running `bun run gen`
 * again is the entire workflow.
 */
import path from "node:path";

import { readCurrentVersion, versionDir } from "./lib/figma-icons-version";
import { byKind, resolveDump } from "./lib/icon-importer";
import type { Resolution } from "./lib/icon-importer";
import { loadNamesOverride } from "./lib/names-override";
import { toComponentName } from "./lib/naming";
import { syncPackageExports } from "./lib/package-exports";
import {
  PREVIEW_GALLERY_FILENAME,
  writePreviewArtifacts,
} from "./lib/preview-gallery";
import { tryParseEntry } from "./lib/svg-entry";

const PACKAGE_ROOT = path.join(import.meta.dir, "..");
const GENERATED_ICONS_ROOT = path.join(PACKAGE_ROOT, "generated-icons");

const GENERATED_BANNER =
  "// Generated by scripts/generate-icons.ts — do not edit by hand.\n// Source: figma-icons/{{version}}/{{file}}\n\n";

/**
 * An icon whose slug names a horizontal direction (e.g. "chevron-left",
 * "corner-down-right") points the wrong way once the page flips to `dir="rtl"`.
 * Flip it automatically via Tailwind's `rtl:` variant, baked into the
 * component itself — no per-usage className is ever needed.
 */
const DIRECTIONAL_SLUG = /(?<start>^|-)(?<direction>left|right)(?<end>-|$)/u;
const isDirectionalSlug = (slug: string): boolean =>
  DIRECTIONAL_SLUG.test(slug);

// oxlint-disable no-template-curly-in-string -- emitted as literal source text for a generated component, not interpolated here
const DIRECTIONAL_CLASSNAME_EXPR =
  'className ? `rtl:rotate-180 ${className}` : "rtl:rotate-180"';

const buildComponentSource = (
  version: string,
  file: string,
  componentName: string,
  viewBox: string,
  children: string,
  directional: boolean
): string => {
  const banner = GENERATED_BANNER.replace("{{version}}", version).replace(
    "{{file}}",
    file
  );
  const props = directional
    ? "{ size = 24, className, ...props }: IconProps"
    : "{ size = 24, ...props }: IconProps";
  const className = directional
    ? `\n    className={${DIRECTIONAL_CLASSNAME_EXPR}}`
    : "";

  return `${banner}import type { IconProps } from "../../types";

export const ${componentName} = (${props}) => (
  <svg
    aria-hidden={props["aria-label"] || props.role ? undefined : true}${className}
    fill="none"
    height={size}
    viewBox="${viewBox}"
    width={size}
    xmlns="http://www.w3.org/2000/svg"
    {...props}
  >
    ${children}
  </svg>
);
`;
};

const listExistingIconFiles = async (
  versionDirPath: string
): Promise<string[]> => {
  const glob = new Bun.Glob("*/*.tsx");
  const files: string[] = [];
  for await (const file of glob.scan({ cwd: versionDirPath })) {
    files.push(file);
  }
  return files;
};

interface GenerateResult {
  category: string;
  slug: string;
  relPath: string;
  ok: boolean;
}

/** Generates one component, or reports (without throwing) that this shape's
 * markup is beyond what `lib/svg.ts` understands — some graphics use
 * gradients, groups, or embedded images that a simple icon never would. One
 * unparseable shape shouldn't abort the whole run. */
const generateIcon = async (
  dumpDir: string,
  version: string,
  versionDirPath: string,
  resolution: Resolution
): Promise<GenerateResult | null> => {
  const slug = resolution.slug as string;
  const [entry] = resolution.entries;
  if (!entry) {
    return null;
  }
  const parsed = await tryParseEntry(dumpDir, entry);
  if (!parsed.ok) {
    return {
      category: entry.category,
      ok: false,
      relPath: entry.relPath,
      slug,
    };
  }
  const componentName = toComponentName(slug);
  const code = buildComponentSource(
    version,
    entry.relPath,
    componentName,
    parsed.viewBox,
    parsed.children,
    isDirectionalSlug(slug)
  );
  await Bun.write(
    path.join(versionDirPath, entry.category, `${slug}.tsx`),
    code
  );
  return { category: entry.category, ok: true, relPath: entry.relPath, slug };
};

/** Only cleans up stale files within this version's own folder — an older
 * version's generated output is left untouched so a pinned subpath
 * (`@cs/icons/icons_v1/...`) keeps resolving after `.current` moves on. */
const removeStaleIconFiles = async (
  versionDirPath: string,
  keptFiles: Set<string>
): Promise<number> => {
  const existingFiles = await listExistingIconFiles(versionDirPath);
  const staleFiles = existingFiles.filter((file) => !keptFiles.has(file));
  await Promise.all(
    staleFiles.map((file) => Bun.file(path.join(versionDirPath, file)).delete())
  );
  return staleFiles.length;
};

const pluralize = (count: number, word: string): string =>
  `${count} ${word}${count === 1 ? "" : "s"}`;

const main = async () => {
  const version = await readCurrentVersion();
  const dumpDir = versionDir(version);
  const versionDirPath = path.join(GENERATED_ICONS_ROOT, version);

  const namesOverride = await loadNamesOverride(dumpDir);
  const { resolutions, unparsed } = await resolveDump(dumpDir, namesOverride);

  const resolved = byKind(resolutions, "resolved");
  const duplicates = byKind(resolutions, "duplicate");
  const unresolved = byKind(resolutions, "unresolved");

  if (resolved.length === 0) {
    throw new Error(`No resolved icons found in ${dumpDir}`);
  }

  const rawResults = await Promise.all(
    resolved.map((resolution) =>
      generateIcon(dumpDir, version, versionDirPath, resolution)
    )
  );
  const results = rawResults.filter((result): result is GenerateResult =>
    Boolean(result)
  );
  const generated = results.filter((result) => result.ok);
  const failedToParse = results.filter((result) => !result.ok);
  const removed = await removeStaleIconFiles(
    versionDirPath,
    new Set(generated.map((result) => `${result.category}/${result.slug}.tsx`))
  );

  const categories = [...new Set(generated.map((result) => result.category))];
  await syncPackageExports(version, categories);

  await writePreviewArtifacts(
    dumpDir,
    versionDirPath,
    resolutions,
    new Set(failedToParse.map((result) => result.relPath))
  );

  console.log(
    `Generated ${pluralize(generated.length, "icon")}${removed > 0 ? `, removed ${pluralize(removed, "stale file")}` : ""}.`
  );
  if (failedToParse.length > 0) {
    console.log(
      `Couldn't parse ${pluralize(failedToParse.length, "shape")} — markup beyond what lib/svg.ts understands. See "Named, but couldn't parse" in ${path.join(dumpDir, PREVIEW_GALLERY_FILENAME)}.`
    );
  }
  if (duplicates.length > 0 || unresolved.length > 0) {
    const duplicateCount = duplicates.reduce(
      (sum, resolution) => sum + resolution.entries.length,
      0
    );
    console.log(
      `Skipped ${pluralize(duplicateCount, "duplicate")}, ${pluralize(unresolved.length, "unresolved shape")} — open ${path.join(dumpDir, PREVIEW_GALLERY_FILENAME)}, fill in names.json, re-run "bun run gen".`
    );
  }
  if (unparsed.length > 0) {
    console.log(`Couldn't parse ${unparsed.length} dump file(s).`);
  }
};

await main();
