export const TRACKING_ELEMENT_ID = {
  LANDING_PAGE: {
    ACCESS_SECTION_MOBILE_APP: "access-section-mobile-app",
    ACCESS_SECTION_TRY_NOW: "access-section-try-now",
    ALL_IN_ONE_CTA_BUTTON: "all-in-one-cta",
    ALL_IN_ONE_CTA_CATEGORY: "all-in-one-categories",
    BLOG_ACCESS_CTA: "blog-access-cta",
    BUILT_FOR_YOU_CTA_CATEGORY: "built-for-you-categories",
    CHAT_INPUT_CTA: "chat-input-cta",
    COMMUNITY: "join_community-cta",
    DISCOVER_MORE: "discover-more-cta",
    FEATURE_SECTION_CTA: "feature-section-cta",
    HERO_BANNER_CTA: "hero-banner-cta",
    HERO_SECTION_APP_STORE: "app-store",
    HERO_SECTION_CTA_BUTTON: "hero-section-cta",
    HERO_SECTION_GOOGLE_PLAY: "google-play",
    MADE_FOR_CHAT_CTA: "made-for-chat-cta",
    MADE_FOR_CTA: "made-for-cta",
    PLAN_DISCOVER_CTA: "plan-discover-cta",
    SOCIAL_DISCORD: "social-discord",
    SOCIAL_FACEBOOK: "social-facebook",
    START_CHATTING: "header-cta",
    TRY_NOW_ASK_SEARCH: "try-now-ask-search-cta",
    TRY_NOW_DEEP_RESEARCH: "try-now-deep-research-cta",
    TRY_NOW_DISCOVER: "try-now-discover-cta",
    TRY_NOW_DOCUMENT: "try-now-document-cta",
    TRY_NOW_IMAGE_CREATION: "try-now-image-creation-cta",
    TRY_NOW_WRITER: "try-now-writer-cta",
    UNLOCK_AI_POWER: "unlock-ai-power-cta",
  },
};
