/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export interface MainTitle {
  prefix?: string;
  highlight?: string;
}

export interface Navigation {
  text?: string;
  url?: string;
}

export interface Section2MainTitle {
  prefix?: string;
  highlight?: string;
}

export interface Section2Navigation {
  text?: string;
  url?: string;
}

export interface Section3MainTitle {
  prefix?: string;
  highlight?: string;
}

export interface Navigations {
  navigation?: NavigationsNavigation;
  qrcode?: Qrcode;
}

export interface Section4MainTitle {
  prefix?: string;
  highlight?: string;
}

export interface Section5MainTitle {
  prefix?: string;
  highlight?: string;
}

export interface Section6MainTitle {
  prefix?: string;
  highlight?: string;
}

export interface Section6Navigation {
  text?: string;
  url?: string;
}

export interface SanityImageAssetReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
}

export interface ObjectImage {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
}

export interface Icon {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "icon.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
}

export interface SanityFileAssetReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
}

export interface FeatureFile {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "file.media" in schema
  _type: "file";
}

export interface NavigationsNavigation {
  text?: string;
  desktop?: string;
  ios?: string;
  android?: string;
}

export interface Qrcode {
  text?: string;
  image?: QrcodeImage;
}

export interface QrcodeImage {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "qrcode.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
}

export interface CategoryIcon {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "category.icon.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
}

export interface FeaturesObjectImage {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "features.object.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
}

export interface ReviewerImage {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "reviewerImage.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
}

export interface Style {
  variant?: "primary" | "secondary" | "outline" | "ghost" | "link" | "inverse";
  width?: "auto" | "full";
  align?: "left" | "center" | "right";
  colorBackground?: Color;
  colorText?: Color;
}

export interface AiToolSectionSchema {
  _id: string;
  _type: "aiToolSectionSchema";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  sectionType?: "metric" | "hero" | "feature" | "step";
  en?: AiToolSectionByLocale;
  zh?: AiToolSectionByLocale;
  th?: AiToolSectionByLocale;
  ar?: AiToolSectionByLocale;
  es?: AiToolSectionByLocale;
  ko?: AiToolSectionByLocale;
  ja?: AiToolSectionByLocale;
  hi?: AiToolSectionByLocale;
}

export interface AiToolSectionByLocale {
  _type: "aiToolSectionByLocale";
  richText?: AiToolRichText;
  subTitle?: string;
  items?: {
    image?: AiToolSectionImage;
    title?: string;
    description?: string;
    url?: string;
    _type: "item";
    _key: string;
  }[];
}

export interface AiToolSectionImage {
  _type: "aiToolSectionImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  title?: string;
}

export interface AiToolRichText {
  _type: "aiToolRichText";
  prefix?: string;
  main?: string;
  suffix?: string;
}

export interface AiSnippetSetReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aiSnippetSet";
}

export interface AiToolBanner {
  _type: "aiToolBanner";
  heading?: AiToolRichText;
  description?: string;
  placeholder?: string;
  contentStyle?:
    | "default"
    | "translate"
    | "qa-cards"
    | "qa-simple"
    | "upload-file";
  allowSelectModel?: boolean;
  redirectLink?: string;
  promptSnippets?: ({
    _key: string;
  } & AiSnippetSetReference)[];
}

export interface AiToolPreview {
  _type: "aiToolPreview";
  image?: AiToolSectionImage;
  preview_title?: string;
  preview_description?: string;
}

export interface AiImageUpload {
  _id: string;
  _type: "aiImageUpload";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}

export interface SanityImageCrop {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
}

export interface SanityImageHotspot {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
}

export type AiToolGroups = (
  | "ai-tool-image"
  | "ai-tool-text"
  | "ai-tool-model"
  | "ai-tool-code"
  | "ai-tool-doc"
  | "ai-tool-study"
)[];

export interface AiToolPromptSnippet {
  _type: "aiToolPromptSnippet";
  quickTag?: string;
  fullPrompt?: string;
  imagePrompt?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}

export interface AiSnippetSet {
  _id: string;
  _type: "aiSnippetSet";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  en?: AiToolPromptSnippet;
  zh?: AiToolPromptSnippet;
  th?: AiToolPromptSnippet;
  ar?: AiToolPromptSnippet;
  es?: AiToolPromptSnippet;
  ko?: AiToolPromptSnippet;
  ja?: AiToolPromptSnippet;
  hi?: AiToolPromptSnippet;
}

export interface AiToolFaqItemsByLocale {
  _type: "aiToolFaqItemsByLocale";
  en?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
  zh?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
  th?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
  ar?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
  es?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
  ko?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
  ja?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
  hi?: ({
    _key: string;
  } & AiToolFaqQaPair)[];
}

export interface AiToolFaqQaPair {
  _type: "aiToolFaqQaPair";
  question?: string;
  answer?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  answerPlain?: string;
}

export interface AiSeoReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aiSeo";
}

export interface AiGroupConfig {
  _id: string;
  _type: "aiGroupConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: AiSeoReference;
  en?: AiGroupConfigLocaleContent;
  zh?: AiGroupConfigLocaleContent;
  th?: AiGroupConfigLocaleContent;
  ar?: AiGroupConfigLocaleContent;
  es?: AiGroupConfigLocaleContent;
  ko?: AiGroupConfigLocaleContent;
  ja?: AiGroupConfigLocaleContent;
  hi?: AiGroupConfigLocaleContent;
}

export interface AiGroupConfigLocaleContent {
  _type: "aiGroupConfigLocaleContent";
  title?: string;
  description?: string;
}

export interface AiSeoLocaleContent {
  _type: "aiSeoLocaleContent";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImageAlt?: string;
}

export interface AiToolLinkReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aiToolLink";
}

export interface AiToolCategory {
  _id: string;
  _type: "aiToolCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  categoryTitleByLocale?: AiToolTitleByLocale;
  links?: ({
    _key: string;
  } & AiToolLinkReference)[];
}

export interface AiToolTitleByLocale {
  _type: "aiToolTitleByLocale";
  en?: string;
  zh?: string;
  th?: string;
  ar?: string;
  es?: string;
  ko?: string;
  ja?: string;
  hi?: string;
}

export interface AiToolLink {
  _id: string;
  _type: "aiToolLink";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  linkTitleByLocale?: AiToolTitleByLocale;
  url?: string;
}

export interface BannerContentReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "bannerContent";
}

export interface BlogsConfig {
  _id: string;
  _type: "blogsConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  en?: BlogsConfigByLocale;
  zh?: BlogsConfigByLocale;
  th?: BlogsConfigByLocale;
  ar?: BlogsConfigByLocale;
  es?: BlogsConfigByLocale;
  ko?: BlogsConfigByLocale;
  ja?: BlogsConfigByLocale;
  hi?: BlogsConfigByLocale;
  banner?: BannerContentReference;
}

export interface BlogsConfigByLocale {
  _type: "blogsConfigByLocale";
  richText?: AiToolRichText;
  subTitle?: string;
}

export interface BannerImageConfig {
  _type: "bannerImageConfig";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  href?: string;
}

export interface LlmsTxtConfig {
  _id: string;
  _type: "llmsTxtConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: string;
}

export interface LandingMeta {
  _id: string;
  _type: "landingMeta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  htmlFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
}

export interface Slug {
  _type: "slug";
  current?: string;
  source?: string;
}

export interface FaqsGroup {
  _type: "faqsGroup";
  name?: string;
  title?: {
    en?: string;
    zh?: string;
    th?: string;
    ar?: string;
    es?: string;
    ko?: string;
    ja?: string;
    hi?: string;
  };
  items?: {
    question_name?: {
      en?: string;
      zh?: string;
      th?: string;
      ar?: string;
      es?: string;
      ko?: string;
      ja?: string;
      hi?: string;
    };
    answer?: {
      en?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
      zh?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
      th?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
      ar?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
      es?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
      ko?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
      ja?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
      hi?: {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?: "normal" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }[];
    };
    _type: "faqsItem";
    _key: string;
  }[];
}

export interface AiToolCategoryReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aiToolCategory";
}

export interface Header {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  ctaLabels?: {
    desktop?: string;
    mobile?: string;
  };
  navigationConfigs?: {
    desktop?: string;
    ios?: string;
    android?: string;
  };
  categories?: ({
    _key: string;
  } & AiToolCategoryReference)[];
  extra_categories?: ({
    _key: string;
  } & AiToolCategoryReference)[];
}

export interface Footer {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  footerLinks?: {
    label?: FooterLinkLabel;
    href?: string;
    _type: "footerLinkItem";
    _key: string;
  }[];
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
}

export interface FooterLinkLabel {
  _type: "footerLinkLabel";
  en?: string;
  zh?: string;
  th?: string;
  ar?: string;
  es?: string;
  ko?: string;
  ja?: string;
  hi?: string;
}

export interface Section6 {
  _type: "section6";
  mainTitle?: Section6MainTitle;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: string[];
  navigation?: Section6Navigation;
  title?: string;
  description?: string;
  createdAt?: string;
}

export interface Section5 {
  _type: "section5";
  mainTitle?: Section5MainTitle;
  stats?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }[];
  ratings?: {
    rating?: 1 | 2 | 3 | 4 | 5;
    reviewText?: string;
    reviewerName?: string;
    reviewerImage?: ReviewerImage;
    _key: string;
  }[];
}

export interface Section4 {
  _type: "section4";
  mainTitle?: Section4MainTitle;
  categories?: {
    icon?: CategoryIcon;
    title?: string;
    features?: {
      image?: FeaturesObjectImage;
      title?: string;
      description?: string;
      link?: string;
      _key: string;
    }[];
    _type: "category";
    _key: string;
  }[];
}

export interface Section3 {
  _type: "section3";
  mainTitle?: Section3MainTitle;
  subtitle?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  navigations?: Navigations;
}

export interface Section2 {
  _type: "section2";
  mainTitle?: Section2MainTitle;
  subtitle?: string;
  navigation?: Section2Navigation;
  features?: {
    icon?: Icon;
    title?: string;
    description?: string;
    file?: FeatureFile;
    _type: "feature";
    _key: string;
  }[];
}

export interface Section1 {
  _type: "section1";
  mainTitle?: MainTitle;
  subtitle?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  stats?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }[];
  downloadButtons?: {
    name?: string;
    image?: ObjectImage;
    link?: string;
    _key: string;
  }[];
  navigation?: Navigation;
}

export interface ImageGallery {
  _type: "imageGallery";
  images?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }[];
  caption?: string;
  columns?: number;
}

export interface SignUpButton {
  _type: "signUpButton";
  preset?: string;
}

export interface Button {
  _type: "button";
  text?: string;
  url?: string;
  style?: Style;
}

export interface PageMetadataReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pageMetadata";
}

export interface HomePageConfig {
  _id: string;
  _type: "homePageConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  en?: {
    pageMetadata?: PageMetadataReference;
  };
  zh?: {
    pageMetadata?: PageMetadataReference;
  };
  th?: {
    pageMetadata?: PageMetadataReference;
  };
  ar?: {
    pageMetadata?: PageMetadataReference;
  };
  es?: {
    pageMetadata?: PageMetadataReference;
  };
  ko?: {
    pageMetadata?: PageMetadataReference;
  };
  ja?: {
    pageMetadata?: PageMetadataReference;
  };
  hi?: {
    pageMetadata?: PageMetadataReference;
  };
  categories?: ({
    _key: string;
  } & AiToolCategoryReference)[];
  extra_categories?: ({
    _key: string;
  } & AiToolCategoryReference)[];
}

export interface LandingPage {
  _id: string;
  _type: "landingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  publishedAt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  section1?: Section1;
  section2?: Section2;
  section3?: Section3;
  section4?: Section4;
  section5?: Section5;
  section6?: Section6;
  qna?: {
    text?: string;
    url?: string;
    _type: "link";
    _key: string;
  }[];
}

export interface TranslationMetadata {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: string[];
}

export type InternationalizedArrayReference = ({
  _key: string;
} & InternationalizedArrayReferenceValue)[];

export interface HomePageReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
}

export interface PoliciesReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "policies";
}

export interface BlogsReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogs";
}

export interface CategoryReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
}

export interface BlogTagReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogTag";
}

export interface AiToolReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aiTool";
}

export interface PricingReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pricing";
}

export interface InternationalizedArrayReferenceValue {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomePageReference
    | PageMetadataReference
    | PoliciesReference
    | BlogsReference
    | CategoryReference
    | BlogTagReference
    | AiToolReference
    | PricingReference;
  language?: string;
}

export interface AiToolFAQsReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aiToolFAQs";
}

export interface Pricing {
  _id: string;
  _type: "pricing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "zh" | "th" | "ar" | "es" | "ko" | "ja" | "hi";
  name?: string;
  seo?: AiSeoReference;
  faq?: AiToolFAQsReference;
}

export interface AiToolSectionSchemaReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aiToolSectionSchema";
}

export interface AiTool {
  _id: string;
  _type: "aiTool";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  groupId?:
    | "ai-tool-image"
    | "ai-tool-text"
    | "ai-tool-model"
    | "ai-tool-code"
    | "ai-tool-doc"
    | "ai-tool-study";
  language?: "en" | "zh" | "th" | "ar" | "es" | "ko" | "ja" | "hi";
  slug?: Slug;
  title?: string;
  preview?: AiToolPreview;
  linkAiTool?: {
    richText?: AiToolRichText;
    subTitle?: string;
    groupIds?: (
      | "ai-tool-image"
      | "ai-tool-text"
      | "ai-tool-model"
      | "ai-tool-code"
      | "ai-tool-doc"
      | "ai-tool-study"
    )[];
  };
  banner?: AiToolBanner;
  seo?: AiSeoReference;
  blogTags?: ({
    _key: string;
  } & BlogTagReference)[];
  blogs?: ({
    _key: string;
  } & BlogsReference)[];
  faq?: AiToolFAQsReference;
  sections?: ({
    _key: string;
  } & AiToolSectionSchemaReference)[];
}

export interface AiToolFAQs {
  _id: string;
  _type: "aiToolFAQs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  itemsByLocale?: AiToolFaqItemsByLocale;
}

export interface AiSeo {
  _id: string;
  _type: "aiSeo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  en?: AiSeoLocaleContent;
  zh?: AiSeoLocaleContent;
  th?: AiSeoLocaleContent;
  ar?: AiSeoLocaleContent;
  es?: AiSeoLocaleContent;
  ko?: AiSeoLocaleContent;
  ja?: AiSeoLocaleContent;
  hi?: AiSeoLocaleContent;
}

export interface BlogTag {
  _id: string;
  _type: "blogTag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "zh" | "th" | "ar" | "es" | "ko" | "ja" | "hi";
  tagId?: number;
  name?: string;
  slug?: Slug;
  createdAt?: string;
}

export interface AuthorReference {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
}

export interface Blogs {
  _id: string;
  _type: "blogs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "zh" | "th" | "ar" | "es" | "ko" | "ja" | "hi";
  blogId?: number;
  blogIdString?: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  slug?: Slug;
  brief?: string;
  tags?: ({
    _key: string;
  } & BlogTagReference)[];
  banner?: BannerContentReference;
  category?: CategoryReference;
  author?: AuthorReference;
  content?: (
    | {
        children?: {
          marks?: string[];
          text?: string;
          _type: "span";
          _key: string;
        }[];
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "blockquote"
          | "center"
          | "right"
          | "justify";
        listItem?: "bullet" | "number";
        markDefs?: {
          href?: string;
          _type: "link";
          _key: string;
        }[];
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        link?: string;
        _type: "image";
        _key: string;
      }
    | {
        asset?: SanityFileAssetReference;
        media?: unknown;
        _type: "file";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageGallery)
    | ({
        _key: string;
      } & Table)
    | ({
        _key: string;
      } & Button)
    | ({
        _key: string;
      } & SignUpButton)
  )[];
  createdAt?: string;
  publishedAt?: string;
}

export interface Color {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
}

export interface Author {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  name?: string;
  slug?: Slug;
  email?: string;
  role?: string;
  instagram?: string;
  tiktok?: string;
  facebook?: string;
  biography?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise?: string[];
  education?: {
    institution?: string;
    degree?: string;
  };
  biography_zh?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise_zh?: string[];
  education_zh?: {
    institution?: string;
    degree?: string;
  };
  biography_th?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise_th?: string[];
  education_th?: {
    institution?: string;
    degree?: string;
  };
  biography_ar?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise_ar?: string[];
  education_ar?: {
    institution?: string;
    degree?: string;
  };
  biography_es?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise_es?: string[];
  education_es?: {
    institution?: string;
    degree?: string;
  };
  biography_ko?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise_ko?: string[];
  education_ko?: {
    institution?: string;
    degree?: string;
  };
  biography_ja?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise_ja?: string[];
  education_ja?: {
    institution?: string;
    degree?: string;
  };
  biography_hi?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: {
      href?: string;
      _type: "link";
      _key: string;
    }[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  expertise_hi?: string[];
  education_hi?: {
    institution?: string;
    degree?: string;
  };
}

export interface Category {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "zh" | "th" | "ar" | "es" | "ko" | "ja" | "hi";
  categoryId?: number;
  title?: string;
  description?: string;
  banner?: BannerContentReference;
  slug?: Slug;
  createdAt?: string;
  publishedAt?: string;
}

export interface BannerContent {
  _id: string;
  _type: "bannerContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  en?: BannerImageConfig;
  zh?: BannerImageConfig;
  th?: BannerImageConfig;
  ar?: BannerImageConfig;
  es?: BannerImageConfig;
  ko?: BannerImageConfig;
  ja?: BannerImageConfig;
  hi?: BannerImageConfig;
}

export interface Policies {
  _id: string;
  _type: "policies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "zh" | "th" | "ar" | "es" | "ko" | "ja" | "hi";
  title?: string;
  slug?: Slug;
  content?: {
    children?: {
      marks?: string[];
      text?: string;
      _type: "span";
      _key: string;
    }[];
    style?:
      | "normal"
      | "h1"
      | "h2"
      | "h3"
      | "h4"
      | "blockquote"
      | "center"
      | "right"
      | "justify";
    listItem?: "bullet" | "number";
    markDefs?: (
      | {
          href?: string;
          _type: "link";
          _key: string;
        }
      | {
          color?: Color;
          _type: "textColor";
          _key: string;
        }
    )[];
    level?: number;
    _type: "block";
    _key: string;
  }[];
  seo?: {
    title?: string;
    brief?: string;
  };
  createdAt?: string;
  publishedAt?: string;
}

export interface PageMetadata {
  _id: string;
  _type: "pageMetadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  pageId?: "home" | "guest";
  title?: string;
  description?: string;
  keywords?: string;
}

export interface HomePage {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  appStoreLink?: string;
  chPlayLink?: string;
  hero?: {
    title?: string;
    subtitle?: string;
    cta?: string;
    highlight?: string;
  };
  features?: {
    title?: string;
    subtitle?: string;
    items?: {
      name?: string;
      description?: string;
      link?: string;
      btnId?: string;
      isMore?: boolean;
      _type: "featureItem";
      _key: string;
    }[];
  };
  useCases?: {
    title?: string;
    items?: {
      title?: string;
      content?: string;
      highlight?: string[];
      _type: "useCaseItem";
      _key: string;
    }[];
  };
  plan?: {
    title?: string;
    benefits?: {
      title?: string;
      description?: string;
      isProPlan?: boolean;
      isLimit?: boolean;
      _type: "planBenefit";
      _key: string;
    }[];
  };
  faq?: {
    question?: string;
    answer?: {
      children?: {
        marks?: string[];
        text?: string;
        _type: "span";
        _key: string;
      }[];
      style?: "normal" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: {
        href?: string;
        _type: "link";
        _key: string;
      }[];
      level?: number;
      _type: "block";
      _key: string;
    }[];
    _type: "faqItem";
    _key: string;
  }[];
}

export interface Table {
  _type: "table";
  rows?: ({
    _key: string;
  } & TableRow)[];
}

export interface TableRow {
  _type: "tableRow";
  cells?: string[];
}

export interface RgbaColor {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
}

export interface HsvaColor {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
}

export interface HslaColor {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
}

export interface MediaTag {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
}

export interface SanityImagePaletteSwatch {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
}

export interface SanityImagePalette {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
}

export interface SanityImageDimensions {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
}

export interface SanityImageMetadata {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
}

export interface SanityFileAsset {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
}

export interface SanityAssetSourceData {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
}

export interface SanityImageAsset {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
}

export interface Geopoint {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
}

export type AllSanitySchemaTypes =
  | MainTitle
  | Navigation
  | Section2MainTitle
  | Section2Navigation
  | Section3MainTitle
  | Navigations
  | Section4MainTitle
  | Section5MainTitle
  | Section6MainTitle
  | Section6Navigation
  | SanityImageAssetReference
  | ObjectImage
  | Icon
  | SanityFileAssetReference
  | FeatureFile
  | NavigationsNavigation
  | Qrcode
  | QrcodeImage
  | CategoryIcon
  | FeaturesObjectImage
  | ReviewerImage
  | Style
  | AiToolSectionSchema
  | AiToolSectionByLocale
  | AiToolSectionImage
  | AiToolRichText
  | AiSnippetSetReference
  | AiToolBanner
  | AiToolPreview
  | AiImageUpload
  | SanityImageCrop
  | SanityImageHotspot
  | AiToolGroups
  | AiToolPromptSnippet
  | AiSnippetSet
  | AiToolFaqItemsByLocale
  | AiToolFaqQaPair
  | AiSeoReference
  | AiGroupConfig
  | AiGroupConfigLocaleContent
  | AiSeoLocaleContent
  | AiToolLinkReference
  | AiToolCategory
  | AiToolTitleByLocale
  | AiToolLink
  | BannerContentReference
  | BlogsConfig
  | BlogsConfigByLocale
  | BannerImageConfig
  | LlmsTxtConfig
  | LandingMeta
  | Slug
  | FaqsGroup
  | AiToolCategoryReference
  | Header
  | Footer
  | FooterLinkLabel
  | Section6
  | Section5
  | Section4
  | Section3
  | Section2
  | Section1
  | ImageGallery
  | SignUpButton
  | Button
  | PageMetadataReference
  | HomePageConfig
  | LandingPage
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomePageReference
  | PoliciesReference
  | BlogsReference
  | CategoryReference
  | BlogTagReference
  | AiToolReference
  | PricingReference
  | InternationalizedArrayReferenceValue
  | AiToolFAQsReference
  | Pricing
  | AiToolSectionSchemaReference
  | AiTool
  | AiToolFAQs
  | AiSeo
  | BlogTag
  | AuthorReference
  | Blogs
  | Color
  | Author
  | Category
  | BannerContent
  | Policies
  | PageMetadata
  | HomePage
  | Table
  | TableRow
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
